### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gepikej** [TIBCOSoftware/jasperreports#101]
Dear @teodord 
I have read the license and i'm getting confused about the limitations and the restriction.
the picture on the git state that i can use it for commercial but the license document isn't clear about that part.
in my case I have a commercial application where i have used the jasper report library without any modifications.
is that legal ? does the license cover that part?
do i need to distribute my application code ??

I really appreciate your quick response.

Thanks.

**Comment by teodord** [comment]
Hi,

The JasperReports Library is published under the terms of the LGPL license and can be used in commercial applications.
https://github.com/TIBCOSoftware/jasperreports/blob/master/LICENSE

I hope this helps.
Teodor

**Comment by gepikej** [comment]
> Hi,
> 
> The JasperReports Library is published under the terms of the LGPL license and can be used in commercial applications.
> https://github.com/TIBCOSoftware/jasperreports/blob/master/LICENSE
> 
> I hope this helps.
> Teodor

So no need to publish my application source code , right ?

**Comment by teodord** [comment]
No need to publish your code.

**Comment by KenobySky** [comment]
> Hi,
> 
> The JasperReports Library is published under the terms of the LGPL license and can be used in commercial applications.
> https://github.com/TIBCOSoftware/jasperreports/blob/master/LICENSE
> 
> I hope this helps.
> Teodor

Does this answer still applies?
Ive read somewhere that, to use the jasper report library you have to buy a license

**Comment by dadza** [comment]
Yes, the answer still applies as the JasperReports library is still distributed under the terms of LGPL v3.0, as you can see in the GitHub repository and in the release files.

If you read somewhere that you need a commercial license to use the JasperReports library, you can inform the author of that statement that it's wrong.
