### ISSUE TITLE
how to remove extra space between firstName and lastName using jasperReport.

### ISSUE THREAD

**Issue by sachinharsh** [TIBCOSoftware/jasperreports#108]
I have two textfield customerFirstName and customerLastName. When I am using jasperReport to print the customerName then I am getting the extraspace between firstName and lastName. I have tried many ways like trim() in textfield and changes in java code but issue still remains the same.
Please find the below java code.
`    /**
     * Method to build customer Label
     *
     * @param shipment  - shipment
     * @return - returns byte array of the report content.
     * @throws B2BTransactionFailed - the underlying transaction failed.
     */
    public byte[] buildCustomerLabel(Shipment shipment) throws B2BTransactionFailed {
        if (LOG.isInfoEnabled()) {
            LOG.info("Started customer label report...");
        }

        byte[] reportStream;

        ReportLoader reportLoader = ReportLoader.newInstance();
        ReportLayoutDefinition customerLabelLayoutDef = reportLayoutDefinitionDAO.getByRefName(
                CUSTOMER_LABEL_LAYOUT_DEFINITION_REF_NAME, APP_CANTATA_DATA_DOMAIN);

        if (customerLabelLayoutDef == null) {
            if (LOG.isErrorEnabled()) {
                LOG.error("Could not found Report layout definition with refName "
                        + CUSTOMER_LABEL_LAYOUT_DEFINITION_REF_NAME
                        + " in the " + APP_CANTATA_DATA_DOMAIN + " data domain");
            }
            throw new ReportLoadException("Could not found Report layout definition with refName "
                    + CUSTOMER_LABEL_LAYOUT_DEFINITION_REF_NAME
                    + " in the " + APP_CANTATA_DATA_DOMAIN + " data domain");
        }
        reportLoader.setReportLayoutDefinition(customerLabelLayoutDef);
        JasperReport jasperReport = reportLoader.loadJasperReport();

        JRBeanCollectionDataSource beanColDataSource =
                new JRBeanCollectionDataSource(buildCustomerLabelReportDataList(shipment));
        try {
            reportStream = JasperExportManager.exportReportToPdf(JasperFillManager.fillReport(jasperReport,
                    null, beanColDataSource));
        } catch (JRException e) {
            throw new ReportLoadException("Failed to build the report", e);
        }
        return reportStream;
    }

    /**
     * Method to customer data set
     *
     * @param shipment - shipment
     * @return - returns the list of customer label details
     * @throws B2BTransactionFailed - the underlying transaction failed.
     */
    public List<CustomerLabelReportBean> buildCustomerLabelReportDataList(Shipment shipment )
            throws B2BTransactionFailed {
        if (LOG.isInfoEnabled()) {
            LOG.info("Build customer label data");
        }
        List<CustomerLabelReportBean> orderCustomerLabelList = new ArrayList<>();

        CustomerLabelReportBean orderCustomerLabelReportBean = new CustomerLabelReportBean();
        orderCustomerLabelReportBean.setOrderNumber(shipment.getOrderNumber());
        orderCustomerLabelReportBean.setCustomerNumber(shipment.getCustomer().getCustomerNumber());
        orderCustomerLabelReportBean.setCustomerFirstName(shipment.getCustomer().getContacts().get(0).getFirstName());
        orderCustomerLabelReportBean.setCustomerLastName(shipment.getCustomer().getContacts().get(0).getLastName());
        orderCustomerLabelList.add(orderCustomerLabelReportBean);

        if (LOG.isInfoEnabled()) {
            LOG.info("Customer label data", orderCustomerLabelList);
        }
        return orderCustomerLabelList;
    }
`
Please find the below jasperReport for the same.
`<jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"customer_Label\" pageWidth=\"595\" pageHeight=\"842\" columnWidth=\"555\" leftMargin=\"20\" rightMargin=\"20\" topMargin=\"20\" bottomMargin=\"20\" uuid=\"3d6833b4-8658-449d-b99d-78443b2738fb\"><property name=\"com.jaspersoft.studio.data.defaultdataadapter\" value=\"One Empty Record\"/><queryString><![CDATA[]]></queryString><field name=\"orderNumber\" class=\"java.lang.String\"><fieldDescription><![CDATA[orderNumber]]></fieldDescription></field><field name=\"customerNumber\" class=\"java.lang.String\"><fieldDescription><![CDATA[customerNumber]]></fieldDescription></field><field name=\"customerFirstName.trim()\" class=\"java.lang.String\"><fieldDescription><![CDATA[customerFirstName]]></fieldDescription></field><field name=\"customerLastName.trim()\" class=\"java.lang.String\"><fieldDescription><![CDATA[customerLastName]]></fieldDescription></field><pageHeader><band height=\"39\" splitType=\"Stretch\"><staticText><reportElement x=\"0\" y=\"4\" width=\"140\" height=\"20\" uuid=\"dc6863da-a160-4fdc-9f1e-5c5597dc0397\"/><textElement verticalAlignment=\"Middle\"/><text><![CDATA[Customer Label]]></text></staticText><textField pattern=\"MMM dd yyyy  h:mm a\"><reportElement x=\"415\" y=\"3\" width=\"139\" height=\"21\" uuid=\"90aafff0-e36e-4515-8d00-1778a6e8b00d\"/><textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/><textFieldExpression><![CDATA[new java.util.Date()]]></textFieldExpression></textField><line><reportElement x=\"0\" y=\"25\" width=\"554\" height=\"1\" uuid=\"6f81129c-963d-4e09-a025-2f85c24bd43c\"/></line></band></pageHeader><detail><band height=\"763\" splitType=\"Stretch\"><staticText><reportElement x=\"30\" y=\"43\" width=\"180\" height=\"27\" uuid=\"150837fb-c719-404d-9c3a-9ffd6f1a0044\"/><textElement><font size=\"19\" isBold=\"true\"/></textElement><text><![CDATA[Customer# :]]></text></staticText><staticText><reportElement x=\"30\" y=\"80\" width=\"180\" height=\"30\" uuid=\"4d7b9ec8-2691-4cc9-acf4-b11e3fed5913\"/><textElement><font size=\"19\" isBold=\"true\"/></textElement><text><![CDATA[Customer Name:]]></text></staticText><staticText><reportElement x=\"30\" y=\"120\" width=\"180\" height=\"30\" uuid=\"f4504c11-c58a-474b-b8b2-3d56b593bb76\"/><textElement><font size=\"19\" isBold=\"true\"/></textElement><text><![CDATA[Order# :]]></text></staticText><textField><reportElement x=\"230\" y=\"43\" width=\"210\" height=\"27\" uuid=\"45b5d8ec-2c70-4af7-9604-5d13d3bc74c8\"/><textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"><font size=\"19\" isBold=\"true\"/></textElement><textFieldExpression><![CDATA[$F{customerNumber}]]></textFieldExpression></textField><textField><reportElement x=\"230\" y=\"120\" width=\"210\" height=\"30\" uuid=\"76f98e78-9f8f-41ef-a63a-a18e7b7db1a0\"/><textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"><font size=\"19\" isBold=\"true\"/></textElement><textFieldExpression><![CDATA[$F{orderNumber}]]></textFieldExpression></textField><textField><reportElement x=\"230\" y=\"80\" width=\"110\" height=\"30\" uuid=\"102aae92-86c8-4cab-88c0-fea9d91f362d\"/><textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"><font size=\"19\" isBold=\"true\"/></textElement><textFieldExpression><![CDATA[$F{customerFirstName}]]></textFieldExpression></textField><textField><reportElement x=\"340\" y=\"80\" width=\"110\" height=\"30\" uuid=\"968dae6a-76ed-4e4c-8a0c-a5abb9f94391\"/><textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"><font size=\"19\" isBold=\"true\"/></textElement><textFieldExpression><![CDATA[$F{customerLastName}]]></textFieldExpression></textField></band></detail></jasperReport>`

**Comment by teodord** [comment]
Unfortunately, the JRXML you posted is incomplete. Try post it in a new comment and if it does not fit, then try put it on some file sharing website.
We don't see the text fields were you display the customer name values.
In any case, calling methods like trim() when declaring the field name is not supposed to work. If you really want to trim the value of a field, then create a report variable and use something like this in its expression:

<variable name="trimmedCustomerFirstName" class="java.lang.String" calculation="None">
<variableExpression>$F{customerFirstName}.trim()</variableExpression>
</variable>

**Comment by teodord** [comment]
Feel free to reopen this if you still have the problem and can provide more details about it.
