### ISSUE TITLE
iText dependency in version 2.1.7.js7 is not available in Maven Central

### ISSUE THREAD

**Issue by wilx** [TIBCOSoftware/jasperreports#109]
Using `net.sf.jasperreports:jasperreports:6.10.0` fails to retrieve its iText dependency in version 2.1.7.js7 from Maven Central.

**Comment by teodord** [comment]
Notice the repository we specify in the JR Lib pom.xml file:
http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/
It should help resolve this dependency.

**Comment by teodord** [comment]
We use a modified version of iText which we published on that jfrog.io public repository. You need access to it from the machine you are performing the build. I'm afraid there is no workaround.
