### ISSUE TITLE
Can't change QR encoding

### ISSUE THREAD

**Issue by Canos** [TIBCOSoftware/jasperreports#11]
As I've seen in `QRCodeSVGImageProducer` and `QRCodeRasterizedImageProducer`

The charset is being hardcoded
```
hints.put(EncodeHintType.CHARACTER_SET, QRCodeComponent.PROPERTY_DEFAULT_ENCODING);
```
QRCodeComponent.PROPERTY_DEFAULT_ENCODING is "UTF-8"
QRCodes are always in UTF-8, that gives us problems with DATALOGIC scan readers which can't support UTF-8.

a parameter config like 
```
net.sf.jasperreports.components.barcode4j.qrcode.encoding=UTF-8
net.sf.jasperreports.components.barcode4j.qrcode.encoding=ISO-8859-1
```
would be perfect

**Comment by dadza** [comment]
Implemented, the property is called `net.sf.jasperreports.components.qrcode.character.encoding`
