### ISSUE TITLE
Modularized Java 11 Project (Template) with Jasperreports

### ISSUE THREAD

**Issue by danielpeintner** [TIBCOSoftware/jasperreports#114]
Hi,

I am working on a Java 11 project/template to show how Jasperreports can be used in a  *modular*  environment (see https://github.com/danielpeintner/Java11Test).

Unfortunately I fail to making it work using `jlink` image.

Running `gradlew run` starts the program just fine and I can create a Jasperreports and viewing them with JasperViewer.

Running `gradlew jlink` creates a valid runtime image which I can start. Once I push the button to create a Jasperreports I get an exception that is not very useful:
`Exception in thread "JavaFX Application Thread"`

No stack trace or anything!?

In the beginning I got
```
java.util.logging.ErrorManager: 5
Handler.reportError caught:
```
similar to the issue reported [here](https://community.jaspersoft.com/questions/1037691/no-log-messages-eclipse-console) but I managed to make  this work by adding `log4j` dependencies.

At the moment, I don't really know how to nail down the issue any further. Hence the question whether you or someone else worked already on a _modularized_ Java 11 application and knows what is missing/wrong.

Thanks for any feedback!

**Comment by danielpeintner** [comment]
FYI: non-modularized projects work fine (see https://github.com/danielpeintner/Java11Test/tree/non-modular) with same tweaks as reported already in https://github.com/TIBCOSoftware/jasperreports/issues/61

**Comment by teodord** [comment]
Can we close this now? I don't think this is an issue with the JasperReports library, is it?

**Comment by danielpeintner** [comment]
I close the issue even though I think there are still 2 remaining issues
1. One cannot create a modularized Java11 library (not sure why though)
2. There seems to be a logging issue in *some* cases (see my `java.util.logging.ErrorManager: 5` error or [here](https://community.jaspersoft.com/questions/1037691/no-log-messages-eclipse-console))

**Comment by teodord** [comment]
Feel free to reopen if you think there is something we need to do in the JasperReports library.
Thanks!
