### ISSUE TITLE
JRResultSetDataSource getColumnIndex sequence seems strange (or at least is not working correct for me)

### ISSUE THREAD

**Issue by fireplace009** [TIBCOSoftware/jasperreports#115]
Hello,

I'm using jasperreports to export a report by passing in a Query & my datasource connection.
My query resultSet contains two columns with the same name ('NM'), but different labels

![image](https://user-images.githubusercontent.com/19831551/70540161-03588080-1b65-11ea-9522-22e39827ca3c.png)

When generating report, what happens for me, is that because in JRResultSetDataSource::getColumnIndex the Name is used first instead of the label, the result in my export is incorrect (it shows twice the same name (taking the first NM it comes alongin the metaData) and not the value linked to the specific labels (that would result in two different values))

It doesn't seem logic to me that the non-unique 'name' is used before the unique 'label' ...
Is this a bug? Or is this just me not understanding it correctly?

Kind regards,
B;

**Comment by teodord** [comment]
Did you try to use this in your field definition?
http://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.sql.field.column.label

**Comment by fireplace009** [comment]
Ok ... Damn, indeed I made a mistake in my code. :(

I was doing: 
columnProperty.addFieldProperty(JRResultSetDataSource.PROPERTY_FIELD_COLUMN_NAME, alias);

And of course ... I should use

columnProperty.addFieldProperty(JRResultSetDataSource.PROPERTY_FIELD_COLUMN_**LABEL**, alias);

Thank you very much for pointing this out.
Kind regards,
B;
