### ISSUE TITLE
TextAdjust options dont work at all. The replacement of "Stretch With Overflow" with textAdjust is not backwards compatible.

### ISSUE THREAD

**Issue by telmas** [TIBCOSoftware/jasperreports#116]
TextAdjust options dont work at all. The replacement of "Stretch With Overflow" with textAdjust is not backwards compatible. (Error with JRXML file when opening from version 6.10)

**Comment by teodord** [comment]
Seems we have different understanding of backwards compatibility.
You want to open a newer version of a file format with an older version of a product.
It is like saying: I want to open a Word 2016 DOCX file with MS Office 2003. Do you think that would work?
For us, backward compatibility of JRXML means a JRXML created 10 years ago, would work with latest JasperReports. In MS Word terms, it would mean a DOC file created in 2003 can be opened with MS Word 2016.

**Comment by teodord** [comment]
BTW, Jaspersoft Studio has an option to let you save a JRXML in an older version. So if you want to run it with JR 6.10.0, you can save it in 6.10.0 format from JSS.
