### ISSUE TITLE
jasperreports.properties being ignored

### ISSUE THREAD

**Issue by Canos** [TIBCOSoftware/jasperreports#120]
I deploy an ear application in multiple servers, without any logic behind, some of them are ignoring jasperreports.properties but others are working as expected (taking the configuration from jasperreports.properties).

Is there a way to use a more precise programatic way to config the tool?

Versions: 
Ubuntu 18.04
Java 8
Jasper: 6.11
The application is running on a Glassfish 5

**Comment by Canos** [comment]
Well I ended up configuring programatically and it seems to be more predictible. 

```java
JasperReportsContext jasperReportsContext = DefaultJasperReportsContext.getInstance();
              
jasperReportsContext.setProperty("net.sf.jasperreports.components.qrcode.character.encoding", "");
jasperReportsContext.setProperty("net.sf.jasperreports.components.barcode4j.image.producer", "svg");
jasperReportsContext.setProperty("net.sf.jasperreports.components.barcode4j.qrcode.producer.svg", "my.package.QRCodeSVGImageProducer");

```

**Comment by teodord** [comment]
This seems to be some deployment classpath related issue. I don't think it is related to JasperReports Library itself but rather to the way the server is dealing with class loading.
