### ISSUE TITLE
Now deprecated isStretchWithOverflow not working with 6.11.0 or 6.12.0

### ISSUE THREAD

**Issue by jannesep** [TIBCOSoftware/jasperreports#124]
We have multiple reports using isStretchWithOverflow which work just fine with for example 6.9.0. Since isStretchWithOverflow now deprecated it should still work though? Now it prints only the first line. If the attribute is changed to textAdjust it works as expected but that is really not possible to do right now.

Here's an example textfield which is not working as expected:
```
<textField isStretchWithOverflow="true" pattern="" isBlankWhenNull="true">
    <reportElement key="textField-11" mode="Transparent" x="88" y="40" width="170" height="13" forecolor="#000000" backcolor="#FFFFFF" uuid="4a310c50-0c94-4357-9cf8-6232314bbe9c"/>
    <box>
       <topPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
       <leftPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
       <bottomPen lineWidth="0.5" lineStyle="Solid" lineColor="#000000"/>
       <rightPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
    </box>
    <textElement rotation="None">
      <font fontName="SansSerif" size="10" isBold="false" isItalic="false" isUnderline="false" isStrikeThrough="false"/>
      <paragraph lineSpacing="Single"/>
    </textElement>
    <textFieldExpression><![CDATA[$P{cust_katuosoite}+"\n"+$P{cust_postinro}+" "+$P{cust_postitoimipaikka}]]></textFieldExpression>
</textField>
```

**Comment by teodord** [comment]
Indeed, the bug can be seen at this line:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/src/net/sf/jasperreports/engine/base/JRBaseTextField.java#L381
If you recompile your JRXML with the newer version, it would work for you. Is just that the old compiled *.jasper files have the problem. We'll fix it for the next release.

**Comment by teodord** [comment]
Just made release 6.12.1 to fix this.

**Comment by jannesep** [comment]
Thank you for a really quick fix!
