### ISSUE TITLE
a bug of Stretch with overflow 

### ISSUE THREAD

**Issue by snow-flowers** [TIBCOSoftware/jasperreports#125]
Hello,i am creating a template and use it in a java application.
I use ireport, export pdf. In the process of using text field，I set stretch with overflow is true, and the font name is simsun。but the stretch with overflow is not working。and less text display。

I checked the information, my friend said that ireport calculates the width of Chinese is not true。

how solve it? override net.sf.jasperreports.engine.util.JRTextMeasurerFactory?
if you understand Chinese,you can see this article.
http://www.dutycode.com/post-21.html.

**Comment by snow-flowers** [comment]
my override class is:
package com.sinotrans.gd.wlp.util;

import net.sf.jasperreports.engine.JRCommonText;
import net.sf.jasperreports.engine.fill.JRMeasuredText;
import net.sf.jasperreports.engine.fill.JRTextMeasurer;
import net.sf.jasperreports.engine.fill.JRTextMeasurerFactory;
import net.sf.jasperreports.engine.fill.TextMeasurer;
import net.sf.jasperreports.engine.util.JRStyledText;

import java.awt.*;
import java.awt.font.TextAttribute;
import java.text.AttributedCharacterIterator;
import java.util.Map;

public class MyTextMeasurerFactory implements JRTextMeasurerFactory {
    @Override
    public JRTextMeasurer createMeasurer(JRCommonText jrCommonText) {
        return new TextMeasurer(jrCommonText){
            @Override
            public JRMeasuredText measure(JRStyledText styledText, int remainingTextStart, int availableStretchHeight, boolean canOverflow) {
                Map<AttributedCharacterIterator.Attribute, Object> grobalAttrMap = styledText.getGlobalAttributes();
                if ("宋体".equalsIgnoreCase((String) grobalAttrMap.get(TextAttribute.FAMILY))){
                    boolean isBold = TextAttribute.WEIGHT_BOLD.equals(grobalAttrMap.get(TextAttribute.WEIGHT));
                    int fontStyle = (isBold ? Font.BOLD : Font.PLAIN);
                    float fontSize = (Float) grobalAttrMap.get(TextAttribute.SIZE);
                    Font font = new Font("宋体",fontStyle,12);
                    styledText.getAttributedString().addAttribute(TextAttribute.FONT, font.deriveFont(fontStyle, fontSize));
                }

                return super.measure(styledText, remainingTextStart, availableStretchHeight, canOverflow);
            }
        };
    }
}

-------------------------------------------------------
I haved override method, and it is very important. How should I declare my own class when exporting pdf？and the method is not necessarily correct

**Comment by teodord** [comment]
This is a typical font mismatch problem. You need to make sure the font you are using is available to the Java Virtual Machine both at report fill time, when text size is calculated, and at report export time, when the font is embedded into PDF.
You need to package your font as a font extension. Note that iReport is no longer maintained for many years, but I think it does have a font extension wizard.
You can use Jaspersoft Studio.
Feel free to reopen this if you still have the problem and can provide more details about it so that we can reproduce it.
