### ISSUE TITLE
Subpixel precision in templates

### ISSUE THREAD

**Issue by roman-garcia** [TIBCOSoftware/jasperreports#126]
Hello,

A few years ago, I had to build a small jrxml template for "price stickers", that each basically contained a price and a label.

As you all know, in jasperreports the template dimensions use pixels as the main unit. However a problem arose in my case, as my little templates, which were repeated across the whole height and width of an A4 page (sometimes 5 horizontal ones, and 25 vertical ones) quickly became misplaced. The small margin of error introduced by sizing my jasperreports bands in pixel gets accumulated throughout the whole page, and you can end up with a whole line not being able to fit in the page at the bottom.

A solution was to be able to use subpixel precision to define our template dimensions. In coding terms, that meant to convert a whole lot of ints to floats, which we did on a fork. Here's the diff if you want to see how it looks today : https://github.com/Cosium/jasperreports/commit/2a33e3f101f5353928b51583825affa850c33142

It might need a bit of more work, as it was done a few years ago, but would you be willing to examine a pull request implemeting such a change in jasperreports ?

**Comment by teodord** [comment]
It would be very difficult to introduce sub-pixel dimensions in JasperReports templates.

Not sure how you consume the reports you create, but maybe you can have the original report exported to SVG and then refit it into a different template at the desired size and the SVG labels would scale to fit.
