### ISSUE TITLE
Support for Groovy 3.x

### ISSUE THREAD

**Issue by slovdahl** [TIBCOSoftware/jasperreports#131]
Are there any plans for supporting Groovy 3.x in jasperreports? At the moment, updating Groovy to 3.0 while using version 6.4.0 of jasperreports gives the following exception when `JasperCompileManager.compileReport(jasperDesign)` is called:

```
java.lang.IncompatibleClassChangeError: class net.sf.jasperreports.compilers.JRGroovyCompiler$ClassCollector has interface org.codehaus.groovy.control.CompilationUnit$ClassgenCallback as super class
	at net.sf.jasperreports.compilers.JRGroovyCompiler.compileUnits(JRGroovyCompiler.java:98)
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:203)
	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:357)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReport(JasperCompileManager.java:617)
```

I checked the jasperreports source code, and there haven't been any changes related to this, which leads me to conclude that the latest version would give the same exception as well. `org.codehaus.groovy.control.CompilationUnit.ClassgenCallback` has been changed from an abstract class to an interface, hence the exception.

**Comment by slovdahl** [comment]
Is there anything I can do to help drive this forward?

**Comment by dadza** [comment]
Upgrading the Groovy dependency in JasperReports to 3.x is planned, but at this moment I can't say when there will be a release with the upgrade.

**Comment by soc** [comment]
I'm also interested in this, as Groovy 2.x doesn't seem to run on modern JDKs anymore.

**Comment by soc** [comment]
@dadza Is this fix a matter of deciding on the right timing, or someone doing the work?

Groovy 2 basically means we are stuck with Java 11 as the last LTS version Groovy 2 runs on, and that it turn means JasperReports is stuck on that, and that means everything else depending on JasperReports is, too.

**Comment by dadza** [comment]
Upgraded to Groovy 3 at https://github.com/TIBCOSoftware/jasperreports/commit/805f18797178404418521f8b9bbbbd89b9f37f17

The change will be part of the next JasperReports release.

**Comment by soc** [comment]
Thanks a lot @dadza!

**Comment by soc** [comment]
Hey @dadza, is there any time plan on when the next release including this change will happen?

**Comment by aggregat4** [comment]
@dazda or  @teodord  is a release of jasperreports with the upgrade to Groovy 3 imminent?

**Comment by soc** [comment]
Hey, is there anything I can do to help move this forward?

**Comment by slovdahl** [comment]
Seems like there is a 6.17.0 release with upgraded Groovy available now :tada:

**Comment by soc** [comment]
Thanks to everyone involved!

(Though it turns out that Groovy 3 didn't manage to actually fix the split package problems, so I guess there will be a desire to move to Groovy 4 from interested parties...)
