### ISSUE TITLE
How to use Jasper Reports in IntelliJ IDEA with OpenJDK11

### ISSUE THREAD

**Issue by raoufOnGithub** [TIBCOSoftware/jasperreports#134]
So I've been using Jasper Reports on JDK8 (Netbeans 11.1 & JavaFX 2) and everything was simple. Now I am migrating from JDK8 to OpenJDK11 with gradle (IntelliJ IDEA & JavaFX 14) and I am stuck with Jasper Reports. I tried to add the dependency compile 'net.sf.jasperreports:jasperreports:6.12.2' and the jar files were downloaded successfully, but when I go to my code and try to import the necessary libraries I can't find them.

Here's the code I was using in JDK8 (which I think should be the same in OpenJDK11) :
```
@FXML
public void print(ActionEvent actionEvent) {
        // My report
        JasperReport jreport = JasperCompileManager.compileReport("path\\to\\my\\report\\newReport.jrxml");

        // The data source to use to create the report
        JRBeanCollectionDataSource jcs = new JRBeanCollectionDataSource(list);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, jcs);

        // Viewing the report
        JasperViewer.viewReport(jprint, false);
    }
```
and here's the libraries I need (net.sf was not detected at all eventhought the jar file is downloaded):
```
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
```

**Comment by teodord** [comment]
What exactly is the error you get? Can we see a stack trace?

**Comment by teodord** [comment]
I don't think this is related to JasperReports. It is more related to how things work in IntelliJ vs Netbeans. Maybe you can get better help on the IntelliJ forums.

**Comment by raoufOnGithub** [comment]
@teodord indeed, the problem was not with JasperReports, I have found the solution: I had to add `    requires jasperreports` in **module-info.java** (after adding the dependency in the **build.gradle**) and then I can proceed to import the necessary.
But now I am facing a new problem about _itext_, here's the stack trace:
```
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/lowagie/itext/2.1.7.js7/itext-2.1.7.js7.pom
  - https://repo.maven.apache.org/maven2/com/lowagie/itext/2.1.7.js7/itext-2.1.7.js7.jar
Required by:
    project : > net.sf.jasperreports:jasperreports:6.12.2

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by teodord** [comment]
JasperReports works with a customized version of iText which is published on a public Maven artifactory here:
https://jaspersoft.jfrog.io/jaspersoft/webapp/#/artifacts/browse/tree/General/third-party-ce-artifacts/com/lowagie/itext

You can see this public artifactory being mentioned in the pom.xml file of the JasperReports library:
https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports/6.12.2/jasperreports-6.12.2.pom

So you need to declare this public repository as instructed by IntelliJ.

**Comment by raoufOnGithub** [comment]
Thank you very much for your help! Everything works fine now.
For gradle users, just add this in the dependencies to add iText to your project:
`implementation 'com.lowagie:itext:2.1.7'`

in addition of:
```
implementation 'net.sf.jasperreports:jasperreports:6.12.2'
implementation 'net.sf.jasperreports:jasperreports-fonts:6.12.2'
```
