### ISSUE TITLE
Unable to register 2 font extensions

### ISSUE THREAD

**Issue by tbuckel** [TIBCOSoftware/jasperreports#139]
Hi,

I wanted to register 2 font extensions, but only one is loaded. There is a warning in the logs by DefaultExtensionsRegistry which flags the font extensions being the same:

`DefaultExtensionsRegistry - Extension resource jar:file:/<omitted>/ArialUnicode/2.1/ArialUnicode-2.1.jar!/jasperreports_extension.properties was found to be a duplicate of jar:file:/<omitted>/DynamicJasper-core-fonts/1.0/DynamicJasper-core-fonts-1.0.jar!/jasperreports_extension.properties in classloader sun.misc.Launcher$AppClassLoader@18b4aac2`

Both font extension Jars have different properities in their respective jasperreports_extension.properties file:

```
net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.extensions.SpringExtensionsRegistryFactory
net.sf.jasperreports.extension.fonts.spring.beans.resource=fonts/fonts1334623843090.xml

```

```
net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.extensions.SpringExtensionsRegistryFactory
net.sf.jasperreports.extension.fonts.spring.beans.resource=fonts/fonts.xml
```

Having tracked down the behaviour a bit more, it looks like there's a bug in `net.sf.jasperreports.engine.util.ObjectUtils` when it compares JRPropertiesMaps:

```
public static boolean equals(JRPropertiesMap p1, JRPropertiesMap p2)
.....
for (int i = 0; i < names1.length; i++)
{
  String name1 = names1[i];
  String name2 = names2[i];
  if (!equals(name1, name2))
  {
    return false;
  }

  String value1 = p1.getProperty(name1);
  String value2 = p1.getProperty(name1);  <==== SHOULD BE p2.getProperty(name1);
  if (!equals(value1, value2))
  {
    return false;
  }
}

```

**Comment by dadza** [comment]
Thank you for investigating and reporting the problem.
