### ISSUE TITLE
PrintDrawVisitor - Duplicated Code

### ISSUE THREAD

**Issue by DaveJarvis** [TIBCOSoftware/jasperreports#14]
https://github.com/Jaspersoft/jasperreports/blob/master/jasperreports/src/net/sf/jasperreports/engine/export/draw/PrintDrawVisitor.java all the `visit` methods are duplicated code that can be refactored to a single method call that iterates over a single `List` that contains the following instance variables:

``` .java
private final LineDrawer lineDrawer;
private final RectangleDrawer rectangleDrawer;
private final EllipseDrawer ellipseDrawer;
private final ImageDrawer imageDrawer;
```

A List of their common super interfaces would be more generic, leading the way to allowing third-party additions (e.g., a rectangle with drop-shadow).

**Comment by teodord** [comment]
Not sure what you mean, Dave. But if you already made this improvement on your side, maybe you could share it with us through a pull request? I'm closing it for now as it does not seem critical. Feel free to reopen if you can provide more details.
