### ISSUE TITLE
Spring Boot - Pool connections 

### ISSUE THREAD

**Issue by miamilabs** [TIBCOSoftware/jasperreports#143]
Hi Community,

i am working with Spring Boot and implemented JasperReport into my Project.
Current Setup is Spring Boot 2.3.1 with MySQL Database.

Issue Description: 

When i pull multiple reports at in short time than all my connections from pool are active.

`19:51:24.403 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=10, idle=0, waiting=1) 
19:51:24.403 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool is at sufficient level. 
19`

Code Example : 

@Service
@RequiredArgsConstructor
@Slf4j
public class ReportingServiceImpl implements ReportingService {

    private final DataSource connector;

    private void createPdfReportAsStream(OutputStream outStream, DeviceReportFilter filter) {
        final InputStream stream = new FileInputStream(config.getPath() + File.separator + filter.getFileName());
        final JasperReport report = JasperCompileManager.compileReport(stream);
        final JasperPrint print = JasperFillManager.fillReport(report, null, connector.getDataSource().getConnection());

        if (filter.getReportType().equals(ReportType.PDF)) {
            JasperExportManager.exportReportToPdfStream(print, outStream);
        }
    }
}

I am more than sure that i forgot something, and it is not a bug, but maybe some one can tell me more. 

Thank you.

**Comment by dadza** [comment]
Did you try to close the connection after the JasperFillManager.fillReport call?

**Comment by miamilabs** [comment]
Yes i did, same result.
Looks like Jasper is keeping the connection while using Hikari Pool.
Currently i did resolve this by creating another connection 

`         String dbUrl = "jdbc:mysql://localhost:3306/****?useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC";
            String dbDriver = "com.mysql.cf.jdbc.Driver";
            String dbUname = "****";
            String dbPwd = "****";
            Class.forName(dbDriver);
            Connection conn = DriverManager.getConnection(dbUrl, dbUname, dbPwd);

`

**Comment by teodord** [comment]
In JasperReports we are not keeping connections.
There must be some other problem in your environment that causes this.

Thank you,
Teodor
