### ISSUE TITLE
Templates would not compile after migration from 6.12 to 6.13 

### ISSUE THREAD

**Issue by mikhailChibel** [TIBCOSoftware/jasperreports#147]
Hi there, 

We tried to migrate from older version to 6.14 and found that once we on the version 6.13 some of our reports will not compile anymore. The message would be something 
`1. Type mismatch: cannot convert from boolean to Object
value = ((com.***Entity)parameter_quotation.getValue()).getBranding().getShortName() != null && !((com.***Entity)parameter_quotation.getValue()).getBranding().getShortName().trim().isEmpty(); //$JR_EXPR_ID=9${code}
`

I looked a bit dipper and found that this change of behavior introduced with the following commit 
https://github.com/TIBCOSoftware/jasperreports/commit/1decb71102d44169bde2e9a9352c4778523709c0 

I'm not sure what it meant to fix but it definitely broke my reports, I also can't say I understand what actually it complaining about as the expression used to work for ages. The current workaround for me is to override dependencies in my project like 

![image](https://user-images.githubusercontent.com/8921222/94090508-df52fb00-fe69-11ea-86e3-16db573865f1.png)

Can someone please shed some light on why it changed and why reports wouldn't compile anymore? I can't really change templates to fix them as it too many of them and some of them not owned by me and out of my reach, leaving out that I'm not even sure how to fix them.

**Comment by teodord** [comment]
What is you Java version and on which operating system are you running? Can you reproduce the problem with a simpler expression that does not have custom classes of your own, so that you can share the JRXML with us?

**Comment by mikhailChibel** [comment]
The issue reproducible in Open JDK 11 on Ubuntu 18 TLS as well as Oracle Java 8_196 Windows 10. I will try to comeup with a simple reproducible template and come back to you.

**Comment by teodord** [comment]
Mikhail, can you still provide a report to help reproduce it? Thanks!

**Comment by mikhailChibel** [comment]
@teodord  I've tried to create a reproducible test case and figure out what is the problem, we have dependency to 
`    <dependency>
            <groupId>com.mysema.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>${querydsl.version}</version>
        </dependency>`
and it has org.eclipse.jdt.core.compiler:ecj:jar:4.3.1 in subdependency, which clashing now with org.eclipse.jdt:ecj:jar:3.21.0:compile from Jasper reports. I guess it just unfortunate an you can close the issue.

**Comment by teodord** [comment]
thanks for letting us know.
