### ISSUE TITLE
ClassCastException with java.time.LocalDateTime parameter (Java8)

### ISSUE THREAD

**Issue by mwithi** [TIBCOSoftware/jasperreports#151]
passing a **Java8** `java.time.LocalDateTime` as parameter to `JasperFillManager.fillReport(jasperReport, localParameters, connection)` causes `ClassCastException` here:

https://github.com/TIBCOSoftware/jasperreports/blob/c2af9544d489f3f82b009fa293f6d1882a0fd9f0/jasperreports/src/net/sf/jasperreports/engine/query/JRJdbcQueryExecuter.java#L870

and probably here (with debug disabled):

https://github.com/TIBCOSoftware/jasperreports/blob/c2af9544d489f3f82b009fa293f6d1882a0fd9f0/jasperreports/src/net/sf/jasperreports/engine/query/JRJdbcQueryExecuter.java#L875

I didn't find any issue about this but only [workaround](https://stackoverflow.com/a/38831506/5309541).

This is suggesting the library is not supporting **java.time.* packages** natively, do you confirm?

**Comment by teodord** [comment]
What did you set as class attribute for the parameter definition in the JRXML report template?
Note that the type of value passed to the report needs to match the type of the parameter declared in the report.

Thank you,
Teodor

**Comment by teodord** [comment]
The JDBC API does not work with values of type java.time.LocalDateTime, so you need to provide appropriate values for your query parameters. It is your responsibility to convert these values using the <defaultValueExpression> of a helper report parameter that you then use in the query.

I hope this helps,
Teodor

**Comment by marschall** [comment]
> The JDBC API does not work with values of type java.time.LocalDateTime, so you need to provide appropriate values for your query parameters.

Starting with JDBC 4.2 (Java 1.8) the JDBC API supports `LocalDateTime` through `#getObject(int|String, Class)` and `#setObject(int, Class)`, see tables B-4 and B-5 in the [JDBC specification](https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index2.html).

**Comment by teodord** [comment]
> Starting with JDBC 4.2 (Java 1.8) the JDBC API supports `LocalDateTime` through `#getObject(int|String, Class)` and `#setObject(int, Class)`, see tables B-4 and B-5 in the [JDBC specification](https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index2.html).

Fair enough!  :-)
I only briefly looked at the Javadoc and not into the actual specifications. Now that we clarified that, I have upgraded HSQLDB version for our sample DB and added LocateDate, LocalDateTime and LocalTime to the supported parameter types for the JDBC query executer.

Thanks for letting us know!
Teodor
