### ISSUE TITLE
PDF form fields do not honor landscape page orientation 

### ISSUE THREAD

**Issue by oyarzun** [TIBCOSoftware/jasperreports#154]
If you have a report with landscape page orientation and a PDF form field, the form field text is in the wrong orientation in the exported pdf.

<img width="1063" alt="Screen Shot 2020-11-05 at 9 57 01 AM" src="https://user-images.githubusercontent.com/2364606/98257209-673e2180-1f4d-11eb-9a93-576ec13c57d7.png">
<img width="1507" alt="Screen Shot 2020-11-05 at 9 57 32 AM" src="https://user-images.githubusercontent.com/2364606/98257218-6907e500-1f4d-11eb-907d-15f3b6054f54.png">

[Blank_Letter_Landscape.jrxml.zip](https://github.com/TIBCOSoftware/jasperreports/files/5495148/Blank_Letter_Landscape.jrxml.zip)

**Comment by teodord** [comment]
Thanks for the fix! Will be part of a future release.

**Comment by mattraydub** [comment]
@teodord @oyarzun I don't think this has fully fixed it. Do you have example of a working PDF in landscape?

I've tried on v 6.19.1. I will try on latest 6.20.6 to see if it's fixed there.

**Comment by mattraydub** [comment]
still issue in v6.20.6

<img width="1380" alt="image" src="https://github.com/TIBCOSoftware/jasperreports/assets/6732051/7cdd709c-971f-4e4b-9163-74107d1a320d">

**Comment by oyarzun** [comment]
> @teodord @oyarzun I don't think this has fully fixed it. Do you have example of a working PDF in landscape?
> 
> I've tried on v 6.19.1. I will try on latest 6.20.6 to see if it's fixed there.

@mattraydub using the latest version still works for me. Can you share your jrxml?
