### ISSUE TITLE
Bug on MacOS Big Sur

### ISSUE THREAD

**Issue by matteobaldassin** [TIBCOSoftware/jasperreports#157]
Hi!

With the new release of Mac OS (Big Sur), Jaspersoft became unusable.

The graphic interface have a bug/glitch:

When you move, delete, edit some field, the source code will update but the UI doesn't show the update.

**Comment by teodord** [comment]
This is the JasperReports Library project, which does not have any UI. It is not an application.
About which graphic interface are you talking about and where do you move, delete and edit fields?

**Comment by matteobaldassin** [comment]
I'm referring to Jaspersoft Studio Software.
Should i open an issue on this repo? (https://github.com/TIBCOSoftware/jaspersoft-studio-ce)

**Comment by karfidoff** [comment]
Hi, I have the same issue. JasperReports Studio 16 (the same is in 14th). No changes in UI until you scroll the window.

**Comment by teodord** [comment]
Yes, please log this on the Jaspersoft Studio project, as this is not related to the JasperReports Library project.
https://github.com/TIBCOSoftware/jaspersoft-studio-ce
https://community.jaspersoft.com/bug-tracker?field_bug_project_target_id=496

**Comment by VeaceslavChicu** [comment]
We don't recommend to update to Mac OSx Big Sur right now. Please, wait a bit. We face problems with many other software too. We'll fix it as soon as possible. I suppose also Apple will release some updates soon.

**Comment by matteobaldassin** [comment]
@VeaceslavChicu so it's an apple problem? Do you have any hypothetical fix date for that?

**Comment by teodord** [comment]
No, I don't think there is anything we could fix on our side. Unless there is some Eclipse platform update that would fix these issues, because we experience them with Eclipse itself.
I'm closing this here as it is not a JasperReports library issue

**Comment by lucasmarcondes** [comment]
For those still facing this issue, someone just posted a fix for this.

https://community.jaspersoft.com/jaspersoft-studio/issues/13296#comment-871206
