### ISSUE TITLE
Add option to set the compiler release version

### ISSUE THREAD

**Issue by Thihup** [TIBCOSoftware/jasperreports#163]
Right now we are moving our projects to run with JDK 15.
However, we need to compile the reports with the Java 8 release, unfortunately, the API only calls the compiler without having any way of changing it.
We are building the reports using the _JRAntCompileTask_

The option I need is the '--release' or '--source' and '--target', but maybe allowing to pass arbitrary options would be better.

**Comment by teodord** [comment]
Don't you have the Eclipse JDT compiler JAR in your classpath when you compile your reports?
If you would have it, you would not depend on the JDK compiler and its version.

**Comment by dadza** [comment]
The report compiler based on JDT compiles for Java 8 by default, see https://github.com/TIBCOSoftware/jasperreports/blob/fd32e7799a91d78fde94e003dad7a8564b92772f/jasperreports/src/default.jasperreports.properties#L10

**Comment by Thihup** [comment]
Thank you! Including the JDT it worked fine.
