### ISSUE TITLE
Not an Issue : Custom Validations in jasperreports

### ISSUE THREAD

**Issue by jaspreetsingh96** [TIBCOSoftware/jasperreports#164]
I want to add custom validations on the parameters in jrxml file such that the validations are executed before a report is generated throwing an error if needed. Does the jasperreports library provide a way to do so?

**Comment by teodord** [comment]
This is the responsability of the parent application making calls to our reporting library.
JasperReports is totally agnostic about the way it is called and does not have any UI.
