### ISSUE TITLE
Split type: prevent does not work on first page

### ISSUE THREAD

**Issue by RafikAlhallak** [TIBCOSoftware/jasperreports#167]
Hi,
i  created a new band with split type prevent.
on all the pages works fine except first page the band does not move to the next page because the space is not enough.

**Comment by teodord** [comment]
Do you have some files to show us the problem?
A band with splitType=Prevent would not move onto the next page if it is rendered on what is already a new page.

**Comment by teodord** [comment]
Feel free to reopen this one if you can provide more details about it.

Thank you,
Teodor
