### ISSUE TITLE
Does the Community Edition support the Customized Roles?

### ISSUE THREAD

**Issue by huazhenhz** [TIBCOSoftware/jasperreports#171]
In the Community Edition Jasper Server, I created a New Role named "NORMAL_USER" and a New User named "ReportUser1".
The ReportUser1's Role was assigned to the "NORMAL_USER".
I gave the "Administer" Permission to the "NORMAL_USER" Role.
But when I logged into the Jasper Server Home Page with the "ReportUser1", the page showed the "Access Denied" Title, and "You do not have permission to view this page." Message.
So, I need to make sure whether the Community Edition Jasper Server can support the User-customized Roles.
Many thanks for your help!

![image](https://user-images.githubusercontent.com/8695237/103771314-18e6f500-505a-11eb-9e87-a232ae502b11.png)
![image](https://user-images.githubusercontent.com/8695237/103771372-3320d300-505a-11eb-8533-72d4971a1b47.png)
![image](https://user-images.githubusercontent.com/8695237/103771622-a88ca380-505a-11eb-82e9-6e8cefcff301.png)
![image](https://user-images.githubusercontent.com/8695237/103771410-42078580-505a-11eb-99b5-3cc385a6756f.png)

**Comment by huazhenhz** [comment]
Do I need to do anything in the configuration files (such as .xml file or .properties file)?

**Comment by seoulaja** [comment]
Hi @huazhenhz 

I had similar issue as well, I think somehow the ROLE_USER is mandatory role. So if you add ROLE_USER back to the ReportUser1, the user then can get the access based on the new role, just give it a trt.

**Comment by huazhenhz** [comment]
> I had similar issue as well, I think somehow the ROLE_USER is mandatory role. So if you add ROLE_USER back to the ReportUser1, the user then can get the access based on the new role, just give it a trt.

Yes, I also found this case as you mentioned.
So, that means we still need to depend on the "ROLE_USER" if we want to manage the Report User's Permissions with our Customized Roles, right!

Many thanks for your reply!

**Comment by teodord** [comment]
Happy you found a solution.

But you posted in the wrong project. This is the JasperReports Library project, not the JasperReports Server.
Please post questions about JasperReports Server on its public forums at:
https://community.jaspersoft.com/project/jasperreports-server/answers
