### ISSUE TITLE
JRAbstractJavaCompiler.loadEvaluator : memory leak

### ISSUE THREAD

**Issue by G-bug** [TIBCOSoftware/jasperreports#172]
I use dynamic report generation. When I call this method, a class will be generated every time, which leads to unlimited class loading. Therefore, Metaspace leaks. Is there a solution

version-6.3.1

**Comment by dadza** [comment]
JasperReports doesn't keep any hard references to the compiled classes after the report is filled.  Under these circumstances, the classes are available for class unloading and the JVM should take care of that.   I ran a quick test now and saw that compiled report classes do get unloaded after a while (and Metaspace size decreases periodically).

Please attach a self contained test case to reproduce the Metaspace leak.  Also include details on the Java version and JVM options.

**Comment by teodord** [comment]
Feel free to reopen this in case you can provide more details about this.

Thank you,
Teodor
