### ISSUE TITLE
Mac M1 NullPointException

### ISSUE THREAD

**Issue by a7168837** [TIBCOSoftware/jasperreports#174]
there is no problem when use jasper report6.6.0 on Mac x86 , while I install it on Mac M1,frequence appear NullPointException, and the button of 'see error detail' on the erroring frame not working.

**Comment by teodord** [comment]
Is this about the Jaspersoft Studio? Because JasperReports Library is not something you would install.
If it is about Jaspersoft Studio on Mac, please log the problem on the Jaspersoft Studio project web page here:
https://github.com/TIBCOSoftware/jaspersoft-studio-ce/issues
