### ISSUE TITLE
Property minHeightToStartNewPage does not seem to work in version 6.16.0 

### ISSUE THREAD

**Issue by noorefatemahsuhabuth** [TIBCOSoftware/jasperreports#175]
having migrated from version 6.2.0 to 6.16.0, I noticed that the minHeightToStartNewPage property does not seem to work. The same used to work perfectly before the migration. I have tried to debug the source code, but the part where the property is set does not seem to be triggerd. Grateful if assistance can be provided

**Comment by teodord** [comment]
Can you provide an example report so that we can reproduce it?

Thank you,
Teodor

**Comment by teodord** [comment]
Maybe the change you experience is related to this fix:
https://github.com/TIBCOSoftware/jasperreports/commit/6f8ee5942c39d5bcfdca72f9d691b1688f72bc4d

**Comment by teodord** [comment]
Feel free to reopen this if you can provide more details about the problem.

Thank you,
Teodor
