### ISSUE TITLE
List fill did not complete

### ISSUE THREAD

**Issue by fcecchin** [TIBCOSoftware/jasperreports#176]
I have a XLS report that prints a list of lists. But, sometimes I'm getting this warning _"list fill did not complete, closing previous dataset run"_  and my report does not complete the work, in another words, not all lists are printed.

Can someone help me?

JasperStudio 6.16.0.final and JasperReports Library 6.5.1, but I'd tested in others versions and the bug persist.

**Comment by brentam** [comment]
HI, Any luck finding any solutions. I have the same problem.

**Comment by fcecchin** [comment]
Unfortunately not! I'd changed my report design to fix this issue. :(

**Comment by teodord** [comment]
Hi,

Can you provide a self-contained example, maybe similar to how our project samples work inside /demo/samples folder?

Thank you,
Teodor

**Comment by teodord** [comment]
In the absence of an example that would allow us to reproduce the problem, I would have to close this.
Feel free to reopen it in case you have an example for us.

Thank you,
Teodor
