### ISSUE TITLE
Merge cell problems

### ISSUE THREAD

**Issue by wang7621422811** [TIBCOSoftware/jasperreports#179]
![image](https://user-images.githubusercontent.com/52541372/111259165-5e76fe00-8659-11eb-947c-bdc45023a362.png)
The next page is blank when the cells are merged, as shown in the figure

**Comment by teodord** [comment]
It would be good to see your report templates to understand how the table is put together.
But in general, solving this issue involves using some empty frames just to draw the borders and use isPrintWhenDetailOverflows=true for them.

I hope this helps.
Teodor
