### ISSUE TITLE
Is there a roadmap for Java 9 support?

### ISSUE THREAD

**Issue by robotsnowfall** [TIBCOSoftware/jasperreports#18]
Since Oracle is stopping public updates of jdk8 in January, I would like to know if there is a plan or timeline to support jdk9 (and successors) in JasperReports?

**Comment by teodord** [comment]
Did you try JasperReports with Java 9 and it didn't work for you?

**Comment by robotsnowfall** [comment]
Not yet, but I'm more interested in if it's a supported JDK, not if it merely doesn't break.

**Comment by teodord** [comment]
I think any application or library build for Java 7 or Java 8 (as it is the case with JasperReports Librar), is supposed to work with Java 9 without any issue.
I did not hear anything about Java 9 breaking backward compatibility for code compiled against older Java.
Our tests did not show any problem, so I thought you came across something.
If not, then we can close this.
