### ISSUE TITLE
JavaScriptEvaluatorScope is closing current context

### ISSUE THREAD

**Issue by EduFrazao** [TIBCOSoftware/jasperreports#181]
Hi.
My application relies on Rhino as mutch as Jasper. We have some JavaScript scripts that invokes Jasper to generate report files. Some of this reports can use JavaScript too, and in this case, JavaScriptEvaluatorScope closes our Current Context, decreasing ThreadLocal Context count, causing our code to fail when we call Context.close() (as expected).

That is the code that closes whatever current context.
`
// exit the current context if any
if (currentContext != null)
{
	Context.exit();
}
`

Its possible to suppres this code, because:
`
Context newContext = ContextFactory.getGlobal().enterContext(context);
`
This code will put the current Japer Evaluator context as the active one, and another calls will be able to close their previous Contexts at the end of the execution.

**Comment by dadza** [comment]
Resolved by only exiting contexts created by JavaScriptEvaluatorScope, other contexts will no longer be affected.

**Comment by EduFrazao** [comment]
Very nice. Thank you for this feedback.
