### ISSUE TITLE
Velocity 1.7 dependency

### ISSUE THREAD

**Issue by edu-de** [TIBCOSoftware/jasperreports#187]
JasperReports 6.16.0 has an (optional) dependency to velocity 1.7, which is very old (2010), which has in turn a dependenciy to apache oro, which is outdated and retired: https://jakarta.apache.org/oro/ "As of 2010-09-01, the ORO project is retired. This is an archived site."

The newest velocity version is 2.3:
https://mvnrepository.com/artifact/org.apache.velocity/velocity-engine-core/2.3
https://github.com/apache/velocity-engine

Are any plans to upgrade this dependency soon?

**Comment by teodord** [comment]
Upgraded to Velocity 2.3.
