### ISSUE TITLE
Expression evaluation: evaluate only once

### ISSUE THREAD

**Issue by pandziak** [TIBCOSoftware/jasperreports#192]
Hey.
I'm trying to evaluate some expressions fetched from Jasper xml, but it happens only once. Not only once per expression for example or once per jasperReport object, but only once at all, only on first method call.

PDF is generating fine, everything evaluates good in the result report. But I need to evaluate some expression before that and I'm having problems with evaluation via JREvaluator.

One line snippet:
`JasperCompileManager.loadEvaluator(jasperReport).evaluate(expression)`

(and here whole Java demo: https://github.com/pandziak/jasper-expression-evaluation/blob/main/src/main/java/pl/kwl/jasper/JasperMain.java )

First thought leads me to think that somewhere is some state used. And I would love to look for it and debug this evaluation, but I have problems with debbuger and I cannot go further than 'evaluate(expressionId)' inside this 'JREvaluator#evaluate(expression)'.
Here: https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/src/net/sf/jasperreports/engine/fill/JREvaluator.java - line 313.
And I'm having problems with finding out in my project, which implementation is used.

Does anyone tried to evaluate expressions outside this whole generating process via these JREvaluators? Is this the best solution (or only...) or maybe there is another way to do that?

Thanks in advance!

**Comment by teodord** [comment]
Have you looked at scriptlets?
http://jasperreports.sourceforge.net/sample.reference/scriptlet/index.html#scriptlet

I hope this helps.
Teodor

**Comment by dadza** [comment]
You need to evaluate expression for the compiled report (`JasperReport`) and not from the design report (`JasperDesign`).  It only works the first time due to a coincidence in expression IDs.

See changes at https://github.com/pandziak/jasper-expression-evaluation/pull/1

**Comment by pandziak** [comment]
Thank You so much! Extremely fast answer :)

**Comment by pandziak** [comment]
I know this is closed, but maybe You could help me a little further? Still stuck with these expressions. It evaluates fine now, but I would like to evaluate these expressions with provided parameters. I know there is method called 'init' in evaluator:
```
public void init(
			Map<String, JRFillParameter> parametersMap, 
			Map<String, JRFillField> fieldsMap, 
			Map<String, JRFillVariable> variablesMap, 
			WhenResourceMissingTypeEnum resourceMissingType,
			boolean ignoreNPE
			) throws JRException
```
But I do not know how to pass maps with values there, cannot create JRFillParameter on my own? 
Additionally, even when I evaluate expression with default parameters, these maps in evaluator are null. Default is not working and `evaluator.evaluate(expression)` returns null. Don't know even how to find these defaults in JR objects. 
Thanks again and sorry for trouble, but I'm stuck for a while now with this.
