### ISSUE TITLE
itext dependency

### ISSUE THREAD

**Issue by adelebendayan** [TIBCOSoftware/jasperreports#193]
Hi,
Is there a version of jasperreports where the CVE from the itext library are fixed?
I'm searching for one where [this one](https://ossindex.sonatype.org/vulnerability/9a9a3093-8992-4530-9de5-4361cb866b38?component-type=maven&component-name=com.lowagie) is fixed

Thanks

**Comment by marschall** [comment]
I believe the recommendation is to switch to OpenPDF instead.

**Comment by adelebendayan** [comment]
that's what i did in the end, thanks
i'm closing this
