### ISSUE TITLE
How could I show image component(online url src[read from DB]) with Text Field(Markup html)

### ISSUE THREAD

**Issue by DearMrJ** [TIBCOSoftware/jasperreports#195]
As to the title, I have tried it in text field(just put the data read from DB into textfield, includes text and image), but it did not work, in addition, the text after the image component would lost.

**Comment by teodord** [comment]
Text elements can only display formatted text, meaning you can control the color, size, font, style of text. The text element markup feature is not about rendering web pages.

You might want to take a look at the /demo/samples/htmlcomponent sample inside the JasperReports project distribution package, but that component is made just to show people that embedding HTML content into reports is usually a dead end.

Thanks,
Teodor
