### ISSUE TITLE
possible xsd file error

### ISSUE THREAD

**Issue by sbelodon** [TIBCOSoftware/jasperreports#199]
hi all,

I got same problem with jr:list
https://community.jaspersoft.com/questions/817956/element-jrtable-not-allowed-here-issue

please fix this.
Thanks

**Comment by teodord** [comment]
Having the same problem means you are also opening the JRXML file in IntelliJ IDE?

**Comment by sbelodon** [comment]
Yes

**Comment by teodord** [comment]
As long as the JRXML is working with JasperReports Library, Jaspersoft Studio, iReport or JasperReports Server, you should not worry about it.
The fact that IntelliJ does not understand the XSD definitions, it is not a concern for us.
Maybe you want to check that with IntelliJ.
