### ISSUE TITLE
Implementing PDF/A-2 ?

### ISSUE THREAD

**Issue by jwkaltz** [TIBCOSoftware/jasperreports#200]
Hi,
JasperReports supports PDF/A-1, but not yet the newer standard PDF/A-2. 
Are there already plans to implement that? Or a first estimation of what that would imply?

Thanks for any insight on this,
Wolfgang

**Comment by thetuxinator** [comment]
Any update on this? We would also be interested in the newer PDF/A Versions, as they bring transparency support

**Comment by thetuxinator** [comment]
By browsing the code, i discovered in ivy.xml the dependency points to org="com.lowagie" name="itext" rev="2.1.7.js11-2-SNAPSHOT" as itext seems to be at version 7.2.4 and you point to a snapshot version, shouldn't it be upgraded to use a later itext version?

**Comment by thetuxinator** [comment]
Instead of switching to OpenPDF it could help to switch to the Itext 7 AGPL Version, a comparison can be found here: https://itextpdf.com/how-buy because Itext 7 comes with PDF/A-2 support

**Comment by teodord** [comment]
We have improved support for PDF A-2 since version 6.21.0.

Thank you,
Teodor

**Comment by jwkaltz** [comment]
Thanks @teodord for the information, I will plan tests to see if that works as expected in our environment.
