### ISSUE TITLE
Upgrading to Jasper 6.16

### ISSUE THREAD

**Issue by MohamedGabrFadl** [TIBCOSoftware/jasperreports#202]
I am trying to upgrade to 6.16.0 from 1.3.1 and was successfully able to parse most of the needed values any help in the issue below will be grateful 
`lineBox = frame.getLineBox().clone(this);
`
Always null 
I may provide any needed data to resolve this issue

**Comment by dadza** [comment]
It's not clear what the problem is, please provide a minimal self contained test case to reproduce what you're experiencing.

**Comment by dadza** [comment]
Where is the report coming from?  Do you have a *.jasper file compiled with an old version of JasperReports?

**Comment by MohamedGabrFadl** [comment]
Actually, I have many *.jrxml that being created long ago and am trying to upgrade the library used and I searched a lot and I found that it might be due to the XML parsing and I used Xerces and apache XML graphics libraries and it was able to parse some elements in the .jrxml file but yet the lineBox where not being able to be extracted

**Comment by MohamedGabrFadl** [comment]
I am using  
**```
<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>3.1.0.RELEASE</version>
        </dependency>
```**

**Comment by MohamedGabrFadl** [comment]
I am using java to extract the report org.springframework/spring-core/3.1.0.RELEASE

**Comment by dadza** [comment]
Do you compile the JRXMLs with JasperReports 6.16, or do you use previously compiled reports (*.jasper files)?

**Comment by MohamedGabrFadl** [comment]
Yes it was successfully compiled in JasperStudio and was able to generate the .jasper files but the problem is that I don`t want to generate it from JasperReports what am looking for is to use the library of jasper reports in my java project with latest version or near too it anyway just the problem above in code happens do you know a way to bypass or solve this issue ?

**Comment by dadza** [comment]
Are you using reports compiled with an older JasperReports version in your java project?

**Comment by MohamedGabrFadl** [comment]
> Are you using reports compiled with an older JasperReports version in your java project?

Yes

**Comment by dadza** [comment]
Please attach a compiled report (*.jasper file) here and specify which JasperReports version it was compiled with.

**Comment by MohamedGabrFadl** [comment]
Brother the files are being compiled with Java using JasperReports Dependancy and it automatically generates the needed files which in my case PDF file I have no compiled reports here only JRXML files

**Comment by teodord** [comment]
You confirmed above that you are compiling the JRXML files using an older version of the JasperReports Library. And then you contradicted yourself by saying you are compiling, filling and exporting to PDF in one go without saving intermediate *.jasper files.
There is a lot of misunderstanding here and it makes it difficult to help you.

**Comment by teodord** [comment]
Feel free to reopen this if you still have the problem.
