### ISSUE TITLE
New Feat. XLSX Template Support

### ISSUE THREAD

**Issue by f-aubert** [TIBCOSoftware/jasperreports#21]
I apologize if I shouldn't be opening a new issue, but I would like to see the templating feature in JrXlsExporter extended to JrXlsXExporter, in other words supports of Templates in the XLSX Format.
Maybe the JrXlsExporter could be updated to use the generic POI Model SS API supporting both XLS and XLSX using the same model classes. I'd happily assist a Developper in this, and test the solution as well.
Thanks in advance

**Comment by teodord** [comment]
What about exporting to XLS first, because our JRXlsExporter supports templating feature, and then convert from XLS to XLSX using something like the following:
https://www.oodlestechnologies.com/blogs/Convert-XLS-to-XLSX--File-Using-Apache-POI

Would you give it a try and let us know how it goes?

**Comment by teodord** [comment]
I don't think we are going to do anything about this as there seem to be workarounds.
