### ISSUE TITLE
Changes made to a jasperreport image running in the Openshift/k8s environment are not reflected

### ISSUE THREAD

**Issue by Haydar-Rap** [TIBCOSoftware/jasperreports#220]
By default, sequential file names by timestamp and timestamp pattern changes are not reflected on the "new schedule" screen.

Jasper report docker bitnami image : 7.5.0-debian-10-r43

https://knowledge.broadcom.com/external/article/214320/jasperserver-scheduled-reports-default.html

I'm throwing the operations specified in the link below into the container by providing operations in the Dockerfile and app-entrypoint.sh file.

app-entrypoind.sh file
cp /jobModel.js /opt/bitnami/jasperreports/optimized-scripts/scheduler/model/jobModel.js 
OR
​​​​​​​cp /jobModel.js /opt/bitnami/jasperreports/scripts/scheduler/model/jobModel.js
AND
export JAVA_OPTS="$JAVA_OPTS -Duser.timezone=Europa/Istanbul"
DockerFile
ADD ./jobModel.js /jobModel.js
OR 
COPY jobModel.js /opt/bitnami/jasperreports/optimized-scripts/scheduler/model/jobModel.js

​​​​​​​After changing the relevant files, I am experimenting as follows. But after the container starts, the related files and the changes in it are reflected, but when the jasperreport stands up, I see that the change is not reflected. How can I overcome this situation? I couldn't find the solution.[](url)

**Comment by teodord** [comment]
This seems to be about JasperReports Server product and not the JasperReports Library.
You could log this on the JasperReports Server community page or contact TIBCO support, if you are a customer:
https://community.jaspersoft.com/bug-tracker?text=&status=Open&severity=All&priority=All&category=All&resolution=All&field_bug_project_target_id=212

**Comment by Haydar-Rap** [comment]
Thank you for your help. It didn't happen because I typed wrong letter in defining environment on Dockerfile. I fixed it now. Problem is solved.
