### ISSUE TITLE
Table first row missing at report

### ISSUE THREAD

**Issue by DarrMirr** [TIBCOSoftware/jasperreports#221]
**Affected version:** 6.4.3 - 6.17.0

**Steps to reproduce bug:**

1. Create report template with table element 
1. Add columns (header and value) `firstName` and `lastName` to table elements
1. Set dataset parameter `<datasetParameterExpression><![CDATA[$P{REPORT_DATA_SOURCE}]]></datasetParameterExpression>` to dataset table element
1. Create List<Map<String, Object>> object at Java application with jasperreports dependency
1. Create two Map<String, Object> and put random values with `firstName` and `lastName` keys to them
1. Add each created map to List<Map<String, Object>> 
1. Create JRMapCollectionDataSource and pass List<Map<String, Object>> to its constructor
1. Compile template
1. Fill report pdf using by compiled template and empty parameters map and JRMapCollectionDataSource 

**Expected result:**
- 2 rows are displayed at report

**Actual result:**
- 1 row is displayed at report

It looks like the problem in method `fillReport` at `net.sf.jasperreports.engine.fill.JRVerticalFiller` class [source code](https://github.com/TIBCOSoftware/jasperreports/blob/34f5cb9f761b103549bd0b51792f8fef88630d59/jasperreports/src/net/sf/jasperreports/engine/fill/JRVerticalFiller.java#L113)

Method `next` called twice at begining of the method
```java
if (next())
		{
			fillReportStart();

			while (next())
			{
				fillReportContent();
			}

			fillReportEnd();
		}
```

**Suggestion:**
Maybe use do...while loop instead of while one?

```java
if (next())
		{
			fillReportStart();

			do
			{
				fillReportContent();
			} while (next());

			fillReportEnd();
		}
```

**Comment by dadza** [comment]
Do not pass `$P{REPORT_DATA_SOURCE}` (the data source used by the main dataset) to the table subdataset.

A data source gets consumed/iterated on by the dataset that uses it, so what happens in your case is that the main dataset fetches the first record from `$P{REPORT_DATA_SOURCE}` and then passes it to the table subdataset, which fetches the second and subsequent records from the data source.

Data source instances are not generally meant to be shared by multiple datasets, so you'll need to create a fresh data source object for the table subdataset.  Data sources that implement [JRRewindableDataSource](http://jasperreports.sourceforge.net/api/net/sf/jasperreports/engine/JRRewindableDataSource.html) can be reused in theory, but you'd need to find a place to call the `moveFirst` method.

**Comment by DarrMirr** [comment]
@dadza thank you for your reply. It looks filling report a little bit more complicated process than I supposed. Unfortunately, passing custom `JRDataSource` as parameter to table subdataset does not works. Empty space on page is displayed in such case.  Therefore, I pass `$P{REPORT_DATA_SOURCE}` and it works.

**Comment by DarrMirr** [comment]
>Unfortunately, passing custom JRDataSource as parameter to table subdataset does not works.

I found out what error is. The problem is at function invocation order. There is method `createHandle` at `AsynchronousFillHandle` class:

```java
public static AsynchronousFillHandle createHandle(JasperReport jasperReport, Map<String, Object> parameters, JRDataSource dataSource) { }
```
And at my project method above is invoked lile this:
```java
AsynchronousFillHandle.createHandle(getTemplate(), getParameters(), getDataSource());
```
Method `getDataSource` connect to dbms and build `JRDataSource`. Inside this method I put `JRDataSource` to parameters map (because all three methods are defined at one class, I have access to parameters internally). I change invocation order of `getDataSource` and `getParameters` methods and passing custom `JRDataSource` as parameter to table subdataset works!
