### ISSUE TITLE
MapFillComponent accumulates paths from preceding dataset entries

### ISSUE THREAD

**Issue by chris-landclan** [TIBCOSoftware/jasperreports#231]
https://github.com/TIBCOSoftware/jasperreports/blob/ba5628a14fceab617534e4510e2634abdb6e0c47/jasperreports/src/net/sf/jasperreports/components/map/fill/MapFillComponent.java#L228

Scenario: Report has a map component and is given a datasource with multiple entries, say 3, each row has different path data.

When the report is filled, the MapFillComponent does not reset the path data from the preceding entries such that the pathDataList.get(0).evaluatedItems is accumulating the paths from previous entries. The outcome is that the first entry shows it's path ok, the second entry shows both its own path and the path for entry 1 as one path, and the third entry shows all three paths, again all joined up as one path.

Shouldn't the paths be reset for each entry? See map examples below.

Entry 1
![image](https://user-images.githubusercontent.com/89860008/140511520-200190ad-c5e3-4420-a9f2-966003f7ec96.png)

Entry 2
![image](https://user-images.githubusercontent.com/89860008/140511627-2166fbc3-ca30-4f50-9d97-c308c805f17b.png)

Entry 3
![image](https://user-images.githubusercontent.com/89860008/140511675-9d5c9134-94ac-437b-92f7-677814c4fc85.png)

**Comment by teodord** [comment]
You mean you want to ave 3 independent regions without them being linked with lines. You want 3 islands, right?

Thank you,
Teodor

**Comment by chris-landclan** [comment]
> You mean you want to ave 3 independent regions without them being linked with lines. You want 3 islands, right?

No, I am saying that the connected island phenomenon is a bug that becomes apparent when you have more than one row in your dataset. Each map should only show one of the polygons, but the dataset rows are not resetting the map data from the previous row such that they are accumulating as the report adds more entries. If there is only one item in your report (i.e. one map, if each item has one map), then this bug is not apparent.

**Comment by teodord** [comment]
Fixed at https://github.com/TIBCOSoftware/jasperreports/commit/a8fa4eaa0673ab9521c65b1d7517f14b19478633

Thank you,
Teodor
