### ISSUE TITLE
itext error - Could not resolve com.lowagie:itext:2.1.7.js9.

### ISSUE THREAD

**Issue by samanta-widjaja** [TIBCOSoftware/jasperreports#234]
i already add this in my build.gradle and settings.gradle 
maven { url "https://jaspersoft.jfrog.io/artifactory/third-party-ce-artifacts/" }

my gradle plugin 7.0.3 and my gradle version 7.0.2

but i still got Could not resolve com.lowagie:itext:2.1.7.js9.

**Comment by mingyujiao** [comment]
You need to exclude com.lowagie:itext:2.1.7.js9
Import com.lowagie.itext 2.1.7

     
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.18.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.lowagie</groupId>
                    <artifactId>itext</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.lowagie</groupId>
            <artifactId>itext</artifactId>
            <version>2.1.7</version>
        </dependency>

**Comment by teodord** [comment]
As you can see by browsing the jfrog repo, the artifact is there alright.
https://jaspersoft.jfrog.io/ui/native/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js9
There must be some problem with your local gradle configuration.

Thanks,
Teodor
