### ISSUE TITLE
Changing JasperReports from version 6.18.1 to 6.19.0 causes text escape issues

### ISSUE THREAD

**Issue by danielpeintner** [TIBCOSoftware/jasperreports#257]
I have a `textField` with `markup="styled"`

			<textField textAdjust="StretchHeight" isBlankWhenNull="true">
				<textElement textAlignment="Left" verticalAlignment="Middle" markup="styled">
					<font size="8" isBold="false"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{kurzbeschreibung1Styled}]]></textFieldExpression>
			</textField>

In version `6.18.1` one could use the following input `&lt;` and it got rendered accordingly as HTML
<

In version `6.19.0` it gets rendered as the HTML syntax.
`&lt;`

The _interesting_ part is that  once I add style information in the same string it renders correctly again.
The input `&lt; <style isBold='true'>BOLD</style>` becomes
< **BOLD**

This means I would need to change characters, depending on whether `<style>` tags are added or not.
Has this been changed on purpose?

**Comment by teodord** [comment]
Indeed, this regression was introduced with this occasion:
https://github.com/TIBCOSoftware/jasperreports/issues/236

**Comment by teodord** [comment]
You can download a JAR with the fix from here:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/master-SNAPSHOT/
