### ISSUE TITLE
ExifUtil 6.19.0 fails sometimes

### ISSUE THREAD

**Issue by com-github-michael** [TIBCOSoftware/jasperreports#258]
The Release Notes of Jaspersoft Library 6.19.0 state:
> honour the EXIF orientation information found in photos taken with mobile digital cameras and
> thus match the way browsers make use of this information to auto-rotate photos in HTML;

This seems to be realized by using a additional third-part libary:
> `<dependency org="com.drewnoakes" name="metadata-extractor" rev="2.16.0" conf="compile->*"/>`

And in `net.sf.jasperreports.engine.util.ExifUtil` we find:
```
public static ExifOrientationEnum getExifOrientation(byte[] data)
{
	ExifOrientationEnum exifOrientation = null;
	
	try 
	{
		Metadata metadata = ImageMetadataReader.readMetadata(new ByteArrayInputStream(data));
		ExifIFD0Directory directory = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
		if (directory != null)
		{
			exifOrientation = ExifOrientationEnum.getByValue(directory.getInt(ExifIFD0Directory.TAG_ORIENTATION));
		}
	}
	catch (ImageProcessingException | IOException | MetadataException e) 
	{
		throw new JRRuntimeException(e);
	}
	
	return exifOrientation;
}
```
Unfortunately, this code fails for some (legal) JPG files and therefore the whole report cannot be filled correctly.
I have a attached such a (very small) JPG file (Dallas.jpg) to demonstrate this:

![Dallas](https://user-images.githubusercontent.com/93131399/156880991-0a49b193-a655-4a86-8da6-4bf5b0aced2c.jpg)

(I hope the image does not get somehow converted by Github...)

My test code is as follows:
```
package test;

import com.drew.imaging.ImageMetadataReader;
import com.drew.imaging.ImageProcessingException;
import com.drew.metadata.Metadata;
import com.drew.metadata.MetadataException;
import com.drew.metadata.exif.ExifIFD0Directory;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import net.sf.jasperreports.engine.util.ExifOrientationEnum;

public class MetadataExtractorTest {
  public static void main(String[] args) throws ImageProcessingException, IOException, MetadataException {
    InputStream is = new FileInputStream("/media/sf_Transfer/Dallas.jpg");
    Metadata metadata = ImageMetadataReader.readMetadata(is);
    ExifIFD0Directory directory = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
    if (directory != null) {
      //if(directory.containsTag(ExifIFD0Directory.TAG_ORIENTATION)) {
        ExifOrientationEnum exifOrientation = ExifOrientationEnum.getByValue(directory.getInt(ExifIFD0Directory.TAG_ORIENTATION));
      //}
      //else { System.out.println("Does NOT contain: " + ExifIFD0Directory.TAG_ORIENTATION); }
    }
  }
}
```
Note: The commented-out checks.
This code fails with:
```
Exception in thread "main" com.drew.metadata.MetadataException: Tag 'Orientation' has not been set -- check using containsTag() first
	at com.drew.metadata.Directory.getInt(Directory.java:440)
	at test.MetadataExtractorTest.main(MetadataExtractorTest.java:23)
```
To avoid this issue the advice from the Exception message could be easily implemented: Just check for the existence of the Tag (similar to the commented-out lines in the test code).

Hope this helps fixing this.

Best,
Michael

**Comment by teodord** [comment]
Thanks for letting us know. A new master branch snapshot has been published at:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/master-SNAPSHOT/
