### ISSUE TITLE
since 6.5.1, Image is not displayed when page is broken

### ISSUE THREAD

**Issue by sis-yoshiday** [TIBCOSoftware/jasperreports#26]
I tried to reproduce this problem by minimum example, but can't.
So I attached original example in my repository.

https://github.com/sis-yoshiday/jasperreports-issue

**Comment by dadza** [comment]
For the record, the problem seems to be the same as the one reported at https://community.jaspersoft.com/jasperreports-library/issues/10791

Setting the following property in jasperreports.properties should revert to pre 6.5.1 behaviour:
`net.sf.jasperreports.legacy.band.evaluation.enabled=true`

**Comment by sis-yoshiday** [comment]
@dadza 
I tried and worked as I expected.
 
Thanks ! 
And sorry that I didn't notice already reported issue.
