### ISSUE TITLE
CSS visible when exporting reports in HTML since 6.19

### ISSUE THREAD

**Issue by gtoison** [TIBCOSoftware/jasperreports#263]
After upgrading from 6.18 to 6.19 (or 6.19.1) some CSS seem to be visible in the reports exported to HTML:

`#JR_PAGE_ANCHOR_0_1 th {font-weight: normal;} #JR_PAGE_ANCHOR_0_1 ul {list-style-type: disc; padding-inline-start: 40px; margin: 0px;} #JR_PAGE_ANCHOR_0_1 ol {list-style-type: decimal; padding-inline-start: 40px; margin: 0px;}
`

This shows up in the first (top left) cell of the table

![image](https://user-images.githubusercontent.com/86775455/161000450-54e90f09-36f8-4aac-80ea-69cc04103fba.png)

I've also tried with the latest snapshot (https://jaspersoft.jfrog.io/artifactory/jr-ce-snapshots/net/sf/jasperreports/jasperreports/master-SNAPSHOT/jasperreports-master-20220323.162936-16.jar) but it does not seem to solve the issue

**Comment by teodord** [comment]
I have tested the samples in the latest JRL distribution and none of the HTMLs seem present this problem.
Are you embedding the HTML produced by the JRL in your own application Web UI?
Are you cutting it or processing it in any way before embedding it?
Please attach here the HTML produced by your reports.

**Comment by gtoison** [comment]
Thank you very much for the prompt answer, much appreciated!

I looked further into this issue and the problem seems to be that we let the user modify the html in a [Swing JEditorPane](https://docs.oracle.com/javase/7/docs/api/javax/swing/JEditorPane.html) before sending it via email.
Even when the document is not edited the JEditorPane seems to mangle up the style element nested in the table and when we retrieve it from the editor (`editor.getText()`) the CSS is now a row in the table.

So it seems to be an issue with JEditorPane, not Jasperreports. If I'm not mistaken the CSS was added in 6.19 (I don't see it in 6.18). 
Maybe you could add an option to omit this style element nested in the table, for compatibility but I understand that it would be complicated to support so I can probably strip out the style element myself.

```
<table id="JR_PAGE_ANCHOR_0_1" role="none" class="jrPage" data-jr-height="954" cellpadding="0" cellspacing="0" border="0" style="empty-cells: show; width: 1000px; border-collapse: collapse; background-color: white;">
<style type="text/css">
  #JR_PAGE_ANCHOR_0_1 th {font-weight: normal;}
  #JR_PAGE_ANCHOR_0_1 ul {list-style-type: disc; padding-inline-start: 40px; margin: 0px;}
  #JR_PAGE_ANCHOR_0_1 ol {list-style-type: decimal; padding-inline-start: 40px; margin: 0px;}
</style>
<tr role="none" valign="top" style="height:0">
<td style="width:20px"></td>
```
