### ISSUE TITLE
Bold and italics of simsun font in export pdf file do not work.

### ISSUE THREAD

**Issue by cdt2019** [TIBCOSoftware/jasperreports#272]
Bold and italics of simsun font in export pdf file do not work.

net.sf.jasperreports.engine.export.JRPdfExporter.java
line 2567
   isPdfSimulatedBold = jrFont.isBold() && ((pdfFontStyle & java.awt.Font.BOLD) == 0);
   isPdfSimulatedItalic = jrFont.isItalic() && ((pdfFontStyle & java.awt.Font.ITALIC) == 0);

https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/src/net/sf/jasperreports/engine/export/JRPdfExporter.java#L2567

Modify it to the following, it can display bold and italics normally
    isPdfSimulatedBold = jrFont.isBold() && ((pdfFontStyle & java.awt.Font.BOLD) == java.awt.Font.BOLD);
    isPdfSimulatedItalic = jrFont.isItalic() && ((pdfFontStyle & java.awt.Font.ITALIC) == java.awt.Font.ITALIC);

**Comment by cdt2019** [comment]
the test example is in the jasperReportTest.zip file.
[jasperReportTest.zip](https://github.com/TIBCOSoftware/jasperreports/files/8675460/jasperReportTest.zip)

**Comment by shertage** [comment]
In such cases (when you use a single ttf file for all font faces) the <bold/>, <italic/> and <boldItalic/> font faces are optional. 
If they are present in the fonts.xml file, at runtime characters will be collected directly from that ttf file. 
If they are not present in the fonts.xml file, their bold, italic and boldItalic styles will be computed based on the existing ttf file in the <normal/> font face.

So for this particular situation you can use the attached simplified fonts.xml file
[fonts.xml.zip](https://github.com/TIBCOSoftware/jasperreports/files/8677010/fonts.xml.zip)

**Comment by cdt2019** [comment]
fonts.xml.zip, it works! Thank you for the reply! I close this issue.
