### ISSUE TITLE
SAXParseException

### ISSUE THREAD

**Issue by haozige90** [TIBCOSoftware/jasperreports#277]
OS: Ubuntu20.04

JDK version: 1.8.0_333

Java framework: springboot 2.2.13

Jasperreport Maven Config:
`<jasperreports.version>6.17.0</jasperreports.version>`
`<jasperreports-fonts.version>6.17.0</jasperreports-fonts.version>`
`<jasperreports-functions.version>6.17.0</jasperreports-functions.version>`

Jrxml Regarding Info:
`Created with Jaspersoft Studio version 6.19.0.final using JasperReports Library version 6.19.0-646c68931cebf1a58bc65c4359d1f0ca223c5e94`

Issue: 
1. Use JasperCompileManager.compileReport function for pdf generation, it shows exception as below:
`org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 434; Document root element "jasperReport", must match DOCTYPE root "null"."`

2. This issue is only happend in Linux, I have tried Ubuntu and Centos.

3. I have try different Jasperreport java library, 6.17.0 and 6.19.1.

4. Above Program works fine in Windows.

Question:
Dose this issue relate to compatibility between versions? But if so, how can it works fine in Windows?

**Comment by teodord** [comment]
Hi,

Can you download the project distribution and run some of the samples using Ant?
Or have you done that already?
Note that you need Ant build tool with the Apach Ivy plugin added, to be able to run the samples under the /demo/samples folder of the project source distro.

Thank you,
Teodor

**Comment by haozige90** [comment]
Thanks all, already found the issue, I have an old version Jasper lib in my project, old version Jasper use old method cover new version method to parse jrxml.
