### ISSUE TITLE
itext upgrade bouncycastle dependencies

### ISSUE THREAD

**Issue by boskokg** [TIBCOSoftware/jasperreports#281]
Hello,

com.lowagie:itext:2.1.7.js9 depends on org.bouncycastle:xxx-jdk15on

BouncyCastle changed its artifact name suffix from jdk15on to jdk18on in the latest releases, as it now requires at least Java 1.8

Is it possible to update them?

Thanks

**Comment by teodord** [comment]
Hi,

We have upgraded iText to use BC jdk18on artifacts and this will be part of the next release.

Thank you,
Teodor
