### ISSUE TITLE
XLSX Export Not Working

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#315]
Hi Team,

We have jasperreport-6.20.0 library in our application.
We are using "JRXlsxExporter()" to export the jasper report in ".xlsx" format, but exported xlsx file has some content related issue.
Content in XLSX is also not properly formatted.

Getting below pop-up after opening the exported XLSX file:
_**We found a problem with some content in 'report3273696722863870372.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of workbook, click Yes.**_

Whereas same jasper report exporting fine in XLS format.
Same issue observed in "TIBCO JasperSoft Studio". 

Please let us know, if we have any solution for this.
[PFA]

Thanks,
Tushar

![Error1](https://user-images.githubusercontent.com/112681534/202428975-e9a1681f-5073-4e44-b5b0-a1b128cf294d.PNG)
![Error2](https://user-images.githubusercontent.com/112681534/202428980-07b97733-77d2-46f8-97b7-df7ed6b7d94c.PNG)

[NotWorking-XLSX-report3273696722863870372.xlsx](https://github.com/TIBCOSoftware/jasperreports/files/10030755/NotWorking-XLSX-report3273696722863870372.xlsx)
[Working-XLS-report6293415222833221065.xls](https://github.com/TIBCOSoftware/jasperreports/files/10030757/Working-XLS-report6293415222833221065.xls)

**Comment by dadza** [comment]
Hello

Is the XLSX file the one already repaired by Excel?  It opens without errors and the content formatting doesn't seem consistent with what JasperReports produces.

If so, please attach the original XLSX file produced by JasperReports.

Also attach the JRXML of the report that you exported, if there's a problem we need to understand where it comes from.

Regards,
Lucian

**Comment by tuspatil1** [comment]
Hi Lucian,

PFA for JRXML & Un-Repaired exported XLSX.

Thanks.
Tushar
[Data.zip](https://github.com/TIBCOSoftware/jasperreports/files/10033891/Data.zip)

**Comment by dadza** [comment]
The error comes from this:

```
                    <property name="net.sf.jasperreports.style.fontName">
                        <![CDATA[($P{FONT_NAME_CNATTR}!=null)?$P{FONT_NAME_CNATTR}:"Noto Sans CJK JP Regular"]]>
                    </property>
```

What you actually want is 

```
                    <propertyExpression name="net.sf.jasperreports.style.fontName">
                        <![CDATA[($P{FONT_NAME_CNATTR}!=null)?$P{FONT_NAME_CNATTR}:"Noto Sans CJK JP Regular"]]>
                    </propertyExpression>
```

`<property>` does interprets its contents literally and not as an expression, so you end up with a font called `($P{FONT_NAME_CNATTR}!=..`, and the XLSX exporter chokes on that.  The exporter should be made more robust to property handle such font names, but you'd still need to change the property in your report in order to obtain the result you expect.

Regards,
Lucian

**Comment by tuspatil1** [comment]
Thanks Lucian. It worked.
