### ISSUE TITLE
Hyperlinks on the exported report in PDF format are not working

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#318]
Hi Team,

We are using "jasperreports-6.20.0" library for generating jasper reports. We observed that the hyperlinks on the exported PDF report do not work, whereas the same hyperlink works for HTML and XLSX formats. We are using `<hyperlinkReferenceExpression>` for providing hyperlink to textfield.
Same behavior is in "Jasper Studio" as well.

Please let us know, if we have any solution for this.

Thanks,
Tushar

![Screnshot](https://user-images.githubusercontent.com/112681534/207030054-5f6911c4-9fe5-470e-bdb9-f4f9df1b6c71.png)
[report3219232943496564579.pdf](https://github.com/TIBCOSoftware/jasperreports/files/10207308/report3219232943496564579.pdf)
[Change Notice Summary Report.jrxml.txt](https://github.com/TIBCOSoftware/jasperreports/files/10207310/Change.Notice.Summary.Report.jrxml.txt)

**Comment by tuspatil1** [comment]
Hi Team,

Please update on this.

Thanks,
Tushar

**Comment by dadza** [comment]
Hyperlinks with hyperlinkTarget="Blank" are implemented in PDF using the JavaScript for Acrobat API, which works in Adobe Acrobat Reader (and possibly other viewers that implement the API), but not in the PDF viewer embedded in Chrome.

You can switch to hyperlinkTarget="Self" as a workaround until we will have a resolution for this limitation.

Regards,
Lucian

**Comment by tuspatil1** [comment]
Hi Lucian,

Thanks for your prompt response. Do we have any plan to resolve this for hyperlinkTarget="Blank" inside chrome at jasper side.
If yes, please let us know the approx. time require to resolve this.

Thanks,
Tushar

**Comment by dadza** [comment]
At this moment we don't have a time frame for when the bug will be fixed.

Regards,
Lucian

**Comment by teodord** [comment]
Tushar, 

Do you have a PDF in which such hyperlink works as expected when viewed with Chrome?
I mean, a PDF created with some other tool, which exhibits the correct behavior of hyperlinks opening targets in new window/tab as you want.
I am asking because if you absolutely need it to work this way, I assume you've seen other PDFs working correctly in the past.

It would help us identify the correct code to use for the hyperlinks in PDF to achieve the same effect.

Thank you,
Teodor

**Comment by teodord** [comment]
Also, note that even for a hyperlink with target="Self", the user can press the Control key while clicking on the hyperlink and it will open the document in a new browser tab.

I hope this helps.
Teodor

**Comment by tuspatil1** [comment]
Hi Teoder,

Earlier, we were using IBM's Cognos reporting system for generating PDF reports. Same functionality was working perfectly fine in that.

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

I was hoping you could add such PDF to this thread so that we can test it ourselves and hopefully understand how its hyperlinks are made.

Thank you,
Teodor

**Comment by tuspatil1** [comment]
Hi Teodor,

Sorry for the delayed response.It took time to setup the older reporting tool (i.e., IBM Cognos).
Now we have done the setup and PFA for the PDF report generated using it.
All the hyperlinks in the PDF report are working fine.

[Change Notice Summary Report.pdf](https://github.com/TIBCOSoftware/jasperreports/files/10543235/Change.Notice.Summary.Report.pdf)


Thanks,
Tushar

**Comment by tuspatil1** [comment]
Hi Team,

Please update on it.

Thanks,
Tushar

**Comment by dadza** [comment]
The bug has been fixed in https://github.com/TIBCOSoftware/jasperreports/commit/79763b59bdab2f69ed94e07f74e3faf46dd6e6bd, see above.

**Comment by tuspatil1** [comment]
Thanks. Please let us know, In which jasperrports version (community edition) it will be availble for us?

**Comment by AnderRedna** [comment]
> Thanks. Please let us know, In which jasperrports version (community edition) it will be availble for us?

Did you discover?

I am trying to open a link from a PDF in a new tab using _blank, but it doesn't work...

Jaspersoft® Studio 6.20.6

**Comment by teodord** [comment]
6.21.0
