### ISSUE TITLE
Support jakarta namespace

### ISSUE THREAD

**Issue by reda-alaoui** [TIBCOSoftware/jasperreports#321]
Hello,

It would be great if jasperreports could make the move to Jakarta packages.

Maybe blocked by https://github.com/kklisura/chrome-devtools-java-client/issues/82

**Comment by tahitiangabriel** [comment]
We cannot use jasperReports in our spring boot 3 projects because of this.
It would be very nice to implement it...

**Comment by teodord** [comment]
Hi,

Can you provide more details about what exactly prevents you from using JasperReports with Spring Boot 3 or other software that has moved to Jakarta packages?

Thank you,
Teodor

**Comment by reda-alaoui** [comment]
Hello @teodord ,

In our case, we cannot use https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/src/net/sf/jasperreports/j2ee/servlets/ImageServlet.java anymore. We had to duplicate the source code to our project and replace all `javax.*` imports with `jakarta.*` imports.

**Comment by teodord** [comment]
Hi,

I think that for sometime we would have to maintain compatibility with both javax.* and jakarta.* based deployments, so some major refactoring/restructuring of our library is required. We are going to work on it at some point. But at least for now, copying the servlet is the best approach in your case.

Thank you,
Teodor

**Comment by wenbin9** [comment]
@teodord Hi teodord, is there any plan when will release a new version to support spring boot3?

**Comment by teodord** [comment]
Work on the Jakarta migration and other important refactoring of the library has started on this branch:
https://github.com/TIBCOSoftware/jasperreports/tree/release-7.0.0

**Comment by wenbin9** [comment]
> Work on the Jakarta migration and other important refactoring of the library has started on this branch: https://github.com/TIBCOSoftware/jasperreports/tree/release-7.0.0

@teodord Hi teodord, may I know v7 is community verison? Besides, is this Jakarta migration compatible with jakarta EE9/ jakarta EE10 and upgrade to hibernate6?

**Comment by teodord** [comment]
Even with version 7, we are still talking about the same product: JasperReports Library, which will continue to be open source.
I am not aware of any incompatibilities between Jakarta EE9 and Jakarta EE10, so I can only assume things will just work with both.
We'll try a Hibernate upgrade as well. With Hibernate, the problem is that they changed the query API and we need to revisit our query executer implementation and maybe rewrite it.

**Comment by wenbin9** [comment]
> Even with version 7, we are still talking about the same product: JasperReports Library, which will continue to be open source. I am not aware of any incompatibilities between Jakarta EE9 and Jakarta EE10, so I can only assume things will just work with both. We'll try a Hibernate upgrade as well. With Hibernate, the problem is that they changed the query API and we need to revisit our query executer implementation and maybe rewrite it.

@teodord Hi teodord, noted. Thanks your reply! Thanks

**Comment by teodord** [comment]
You can try out snapshots of the release-7.0.0 branch to see the Jakarta Migration progress.
Snapshots are published on Maven repository at:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/7.0.0-SNAPSHOT/

**Comment by wenbin9** [comment]
> You can try out snapshots of the release-7.0.0 branch to see the Jakarta Migration progress. Snapshots are published on Maven repository at: https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/7.0.0-SNAPSHOT/
I will have a try. Thank you so much!

**Comment by lalo-mx** [comment]
Has anyone tested JasperReports using the tool Tomcat Migration Tool for Jakarta EE? https://tomcat.apache.org/download-migration.cgi
