### ISSUE TITLE
RestController Repsonse Type change after upgrade to 6.20

### ISSUE THREAD

**Issue by a19930905a** [TIBCOSoftware/jasperreports#324]
Hello , 
our project is use 6.10 version before and after we upgrade to 6.20 
All our RestController is reply "XML" response instead of "Json" 

I found same issue in : https://stackoverflow.com/questions/71351249/spring-rest-controller-returns-xml-instead-of-json-after-jasperreports-update

is there any advance information can giving to me?

**Comment by teodord** [comment]
Hi,

First of all, let's agree that JasperReports Library has no servlet or REST controller that you use in your application.
This web RestController is part of your own application code and it is you who should control the response headers, especially if you count on them having a certain value.

Judging from the Stackoverflow thread, this change has been experienced by others and it seems to be related to the fact that JasperReports now uses the jackson-dataformat-xml dependency.

The way I see it, your application does not set the response header and somehow relies on some default at JVM level. It just happens that the addition of the jackson-dataformat-xml JAR changes this default.
If this is the case, then the solution is for you to control the response headers in your own application and no longer rely on default that come from unknown places.

We are using Jackson for XML serialization of data adapter files, chart theme files and other types of resources, as we have replaced Castor for the purpose. If you do not use such features, you could remove the jackson-dataformat-xml from your classpath.
But there is nothing for us to fix in our library and we are not going to give up on using Jackson as dependency.

Thank you,
Teodor

**Comment by a19930905a** [comment]
Hi teodord ,
thx for your answer , that is helpful
