### ISSUE TITLE
suggestion using Apache PDFBox for support of PDF/A-2?

### ISSUE THREAD

**Issue by thetuxinator** [TIBCOSoftware/jasperreports#333]
Dear Devs,

I recently discovered Apache PDFBox, which also seems to be a Java PDF Library. Also it seems that PDFBox is capable of PDF/A-2

Apache PDFBox can be found here: https://pdfbox.apache.org/index.html

And an example Project of a PDF/A-2 converter here:
https://github.com/ETDA/PdfAConverter

Maybe using that one could improve future PDF/A-2/3 support.

kind regards

**Comment by teodord** [comment]
Hi,

Maybe you can help write an Apache PDFBox exporter for JasperReports and contribute it to our project?
We have ours based on iText/OpenPDF and we do not have plans to implement ourselves another one from scratch just because of PDFA2 requirements. 

Thank you,
Teodor
