### ISSUE TITLE
Trailing <br> are ignored in 6.20.1 

### ISSUE THREAD

**Issue by mfg92** [TIBCOSoftware/jasperreports#338]
There is a change/regression between Jasper 6.20.0 and 6.20.1 in how `<br>` tags at the end of a HTML-formatted text field are handled. The example below illustrats this, in 6.20.1 the `<br>` at the end is ignored thus the second text field is directly under the first one.

6.20.0:
![6_20_0](https://user-images.githubusercontent.com/11365250/225917662-f4e87b32-f9a5-4f48-80b6-3def4066430e.png)

6.20.1:
![6_20_1](https://user-images.githubusercontent.com/11365250/225918041-301823ba-646e-4ed0-a39f-f8241c5e0e44.png)

In Jasper Studio:
![studio](https://user-images.githubusercontent.com/11365250/225919361-829a23c9-7f28-4e01-b865-9ebd5ae23a95.png)

jrxml of the example:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="br_issue" pageWidth="595" pageHeight="842" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="06086439-4c48-4d5b-b04e-8dd39ccc99e0">
	<detail>
		<band height="125" splitType="Stretch">
			<textField textAdjust="StretchHeight">
				<reportElement x="0" y="0" width="550" height="30" uuid="0da57331-e4c8-42e9-a22e-25ec1b189d29"/>
				<textElement markup="html"/>
				<textFieldExpression><![CDATA["Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.<br>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.<br>"]]></textFieldExpression>
			</textField>
			<textField textAdjust="StretchHeight">
				<reportElement positionType="Float" x="2" y="30" width="550" height="30" uuid="091412af-c030-48e8-8324-1ebd5cfeaf4e"/>
				<textFieldExpression><![CDATA["Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."]]></textFieldExpression>
			</textField>
		</band>
	</detail>
</jasperReport>
```

**Comment by mfg92** [comment]
Thanks for the quick reply.

So for my usecase it would be great if there would be a way of adding an empty newline at the end of a text field. It could simulate this my placing the second text field not directly below the first one, but instead have a gap between them. But doing it that way would mean that I will always have this "newline". What I need is to have this dynamically.

**Comment by teodord** [comment]
Hi,

There are several ways to have that extra space dynamically. The only thing you need to decide is what dynamically means. Do you want it only when the source HTML markup ends with a <br> tag?

You could use a printWhenExpression on that empty text field, coupled with isRemoveLineWhenBlank=true

Another way to create extra space is to use a dynamic style property such as this one, at text field level:
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.style.box.bottomPadding
Bottom padding could be zero or some positive value depending on whether your desired condition is met.
Such style property at element level can be an expression.

I hope this helps.
Teodor
