### ISSUE TITLE
The POM for com.github.librepdf:openpdf:jar:1.3.30.jaspersoft.1 is missing, no dependency information available

### ISSUE THREAD

**Issue by pauli2406** [TIBCOSoftware/jasperreports#339]
It seems like the artifact version required by release 6.20.1 of open pdf (maven/com/github/librepdf/openpdf/1.3.30.jaspersoft.1/openpdf-1.3.30.jaspersoft.1.pom) is not available in mvn central.

Take a look here:
https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports/6.20.1

and here specifically:
https://mvnrepository.com/artifact/com.github.librepdf/openpdf

There is no version called openpdf-1.3.30.jaspersoft.1.pom available.

Does the adjusted version need to be published?

**Comment by dadza** [comment]
The patched version of OpenPDF has been published in a JasperSoft repository located at https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/

It will not be published in the central Maven repository.

Fwiw the JasperReports POM file has a reference to the repository https://github.com/TIBCOSoftware/jasperreports/blob/113169678bb36861828f5507d021846ecd40f7a9/jasperreports/pom.xml#L513

**Comment by rturner-edjuster** [comment]
I get a 404 trying to pull the JAR file from https://jaspersoft.jfrog.io/jaspersoft/jr-ce-snapshots/com/github/librepdf/openpdf/1.3.30.jaspersoft.1/openpdf-1.3.30.jaspersoft.1.jar

{
  "errors": [
    {
      "status": 404,
      "message": "Item jr-ce-snapshots:com/github/librepdf/openpdf/1.3.30.jaspersoft.1 does not exist"
    }
  ]
}

**Comment by rturner-edjuster** [comment]
Okay, I figured out my issue -- it was because we were already including OpenPDF 1.3.30 in our project instead of the lowagie version. Removing that reference allowed things to work.

It would be _nice_ if JasperReports could stop using modified version of third-party libraries....

**Comment by dadza** [comment]
We use a patched version of OpenPDF because we need a fix for https://github.com/LibrePDF/OpenPDF/issues/676

When there will be an OpenPDF release that includes a fix for that bug we will be more than happy to use it.

If you don't mind the effects of the bug you can use the official OpenPDF 1.3.30 version in your project.

**Comment by RainerGanss** [comment]
@dadza The bug you reference to says "Pull requests welcome". Since you already fixed the bug in your repo, could you maybe provide the PR for LibrePDF? Maybe then they would make a release for you in return ;-)
