### ISSUE TITLE
Could not update my Jasperreports server from 8.0.0  to 8.1.1 

### ISSUE THREAD

**Issue by Millen93** [TIBCOSoftware/jasperreports#343]
Jasperreports was installed by .run file
1. I tried updating it by following the instructions in this link( by .bin file) : https://docs.kony.com/konylibrary/konyfabric/kony_analytics_reporting/Content/How_to_Upgrade_JasperServer.htm?TocPath=_____5
2. I also attempted to update it by doing a full install of version 8.1.1.run and copying files from my old installation directory to the new one. These files included:
/opt/jasperreports-server-cp-8.0.0/apache-tomcat/webapps/jasperserver/WEB-INF/applicationContext.xml
/opt/jasperreports-server-cp-8.0.0/apache-tomcat/webapps/jasperserver/WEB-INF/js.jdbc.properties
/opt/jasperreports-server-cp-8.0.0/apache-tomcat/webapps/jasperserver/WEB-INF/classes/esapi/security-config.properties
/opt/jasperreports-server-cp-8.0.0/apache-tomcat/webapps/jasperserver/WEB-INF/classes/esapi/validation.properties
/opt/jasperreports-server-cp-8.0.0/apache-tomcat/webapps/jasperserver-/WEB-INF/classes/esapi/ESAPI.properties
/opt/jasperreports-server-cp-8.0.0/apache-tomcat/conf/Catalina/localhost/jasperserIver-pro.xml
/opt/jasperreports-server-cp-8.0.0/postgresql/data/
3.  I was trying to move /opt/jasper-server-cp-8.0.0/apache-tomcat /opt/jasper-server-cp-8.0.0/postgresql to jasper 8.1.1 
However, none of these attempts were successful.

**Comment by teodord** [comment]
Hi,

This project here is the JasperReports Library. For questions about the JasperReports Server product, you can post here:
https://community.jaspersoft.com/bug-tracker?field_bug_project_target_id=212

Thank you,
Teodor
