### ISSUE TITLE
"Icon + TextBox " in one Frame create 2 different cells in Jasper Report Excel Format. Need solution to club both in one cell.

### ISSUE THREAD

**Issue by Phi-Jasper** [TIBCOSoftware/jasperreports#345]
"Image+ TextBox " in one Frame create 2 different cells in Jasper Report Excel Format. Need solution to club both in one cell.
PFA report with the issue .
[Testing.xlsx](https://github.com/TIBCOSoftware/jasperreports/files/11261462/Testing.xlsx)

want to have image+textBox in first cell. i.e  A1:A1

**Comment by teodord** [comment]
Hi,

Please use Microsoft Excel to create a document with desired output and attach it here.

Thank you,
Teodor

**Comment by Phi-Jasper** [comment]
Hello teodord ,
please find attached excel with desired output . When we add image control and textbox control in Detail band it creates 2 columns (i.e one for each ) . we want icon + textbox in one column ( one cell ) only. Column merge issue is getting created due to above behaviour.

[Desired_Output.xlsx](https://github.com/TIBCOSoftware/jasperreports/files/11279918/Desired_Output.xlsx)

**Comment by teodord** [comment]
In your example, you are using blank space characters to make sure the image does not actually overlap with your text.

**Comment by teodord** [comment]
It is unlikely we are going to implement this thing, so I'm just closing it now.

Thank you,
Teodor
