### ISSUE TITLE
NoSuchMethodError: ...Document.setGlyphSubstitutionEnabled

### ISSUE THREAD

**Issue by Sab3rRid3r** [TIBCOSoftware/jasperreports#350]
Hi, with the change to jasperreports:6.20.1 and openpdf:1.3.30 instead of itext:2.1.7 we hat no problems so far.
Today we tried jasperreports:6.20.3 an got the following Exception:

java.lang.NoSuchMethodError: 'void com.lowagie.text.Document.setGlyphSubstitutionEnabled(boolean)'
        at net.sf.jasperreports.export.pdf.classic.ClassicPdfProducer.createDocument(ClassicPdfProducer.java:128)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportReportToStream(JRPdfExporter.java:835)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:685)
        at net.sf.jasperreports.engine.JasperExportManager.exportToPdfStream(JasperExportManager.java:196)
        at net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfStream(JasperExportManager.java:533)

We use springboot 2.7.10 with Java 17 and XML as Datasource.
Thanks in advance
Andreas

**Comment by teodord** [comment]
You need to add this repository to your pom.xml files:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/pom-parent.xml#L100
and make use of this custom version of OpenPDF, at least until our contributions gets accepted into their official release:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/pom.xml#L68

I hope this helps.
Teodor

**Comment by yu-shiba** [comment]
LibrePDF/OpenPDF#904

**Comment by teodord** [comment]
The release 6.20.4 was published to put back mandatory OpenPDF dependency in pom.xml.

**Comment by Sab3rRid3r** [comment]
With jasperreports:6.20.4 & openpdf:1.3.30 I still get the same NoSuchMethodError Exception. Plz reopen.

**Comment by teodord** [comment]
Is there any particular reason for which you insist on using OpenPDF 1.3.30 instead the one I mentioned you in my first reply above?
If you do not want to change the version of OpenPDF, as recommended, why would you change the version of JasperReports then?

**Comment by Sab3rRid3r** [comment]
Sorry, I forgot to mention that we can't use the 1.3.30.jaspersoft.2 because the buildprocess of our application gets the dependencies from mvnrepository: com.github.librepdfhttps://mvnrepository.com/artifact/com.github.librepdf/openpdf and 1.3.30 is the latest official version.
I thought with jasperreports:6.20.4 the access to Document.setGlyphSubstitutionEnabled is removed, which I guess I was wrong about. So it would be interesting to know at which version jasper starts working again with official published dependencies.
The reason for updating jasper is because the renovate bot found the new version and we try to stay up to data and find bugs as early as possible.
