### ISSUE TITLE
Non thread safe filling text elements with markup=html

### ISSUE THREAD

**Issue by albfernandez** [TIBCOSoftware/jasperreports#352]
In JRFillTextElement.java, the markup processor is stored in a static cache:
https://github.com/TIBCOSoftware/jasperreports/blob/f6d0eba512678ec460324830bfad33eeffa535c7/jasperreports/src/net/sf/jasperreports/engine/fill/JRFillTextElement.java#L109

This makes this  processor object (in this case a instance of net.sf.jasperreports.engine.util.HtmlEditorKitMarkupProcessor) unique for all threads of the application.

HtmlEditorKitMarkupProcessor is not thread safe, having a lot of attributes modified in the call to the convert method.
This cause mixing of text between distinct reports in heavy threaded operations.

To fix this, there are at least two options.
 1. Don't cache the processor, creating a new instance for every parse call. I'll provide a pull request for this case.
 2. make HtmlEditorKitMarkupProcessor, extracting all the attributes of the object to a new object "state", and pass this "state" across the calls to the processElement method

**Comment by teodord** [comment]
Alberto,

Thank you very much for spotting this! Very much appreciated!

Cheers!
Teodor
