### ISSUE TITLE
Set maxSize property for virtualizer in jasperreports-6.20.1 community edition

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#356]
Hi Team,

We want to set the "maxSize" property for virtualizer as mentioned in the documentation below:
Refer: https://community.jaspersoft.com/wiki/virtualizers-jasperreports

```
<!--report virtualizers-->
<bean id="fileVirtualizerFactory"
      class="com.jaspersoft.jasperserver.api.engine.common.service.impl.FileVirtualizerFactory">
    <property name="maxSize" value="300"/>
    <property name="directory" value="${java.io.tmpdir}"/>
</bean>
```

Is it possible to use this configuration with jasperreports-6.20.1 **community edition**? If yes, can you please let us know how to do this?
Your early response will be very helpful for us.

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

The snippet you posted from the article is from a Spring configuration file of JasperReports Server product.
We are here in a tracker of the JasperReports Library.
Which product are you actually using?

Thank you,
Teodor

**Comment by tuspatil1** [comment]
Hi Teodor,

We just have jasperreports-6.20.1.jar (community edition). We use this library to generate jasper report.
And we want to check, if we have option to configure the above mentioned "maxSize" setting in jasperreports-6.20.1.

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

You are using JasperReports Library programatically, so you need to setup a virtualizer programatically as well.
You can see it being done in one of our samples:
https://jasperreports.sourceforge.net/sample.reference/virtualizer/index.html#virtualizer

Check the Javadoc for details about what can be configured on each virtualizer implementation.

I hope this helps.
Teodor

**Comment by teodord** [comment]
One more thing:
When the issue is not about a potential bug, but rather about trying to get some information about how to achieve something, please consider using the discussion forums at:
https://community.jaspersoft.com/project/jasperreports-library/answers

Thank you,
Teodor
