### ISSUE TITLE
Publish javaflow variant on Maven central

### ISSUE THREAD

**Issue by jnehlmeier** [TIBCOSoftware/jasperreports#357]
I would like to see the javaflow variant to be published on Maven central as well.

If you want to consume the javaflow variant using Maven/Gradle you need to
1. Download jasperreports-javaflow.jar from Github releases
2. Download jasperreports.pom from Maven central
3. Replace `<artifactId>jasperreports</artifactId>` with `<artifactId>jasperreports-javaflow</artifactId>` in the downloaded pom file.
4. Use `mvn deploy:deploy-file` to upload the jasperreports-javaflow artifact to a private maven repository in order to consume it.

Would be nice if one could avoid that by directly consuming jasperreports-javaflow from Maven central.

**Comment by jnehlmeier** [comment]
Oh and if you would really publish it to maven central then the `pom.xml` of the javaflow variant probably wants to make the dependency to `net.tascalate.javaflow:net.tascalate.javaflow.api:2.7.3` required instead of optional.

**Comment by jnehlmeier** [comment]
@teodord Looks fine. It is basically identical to what I have in the private maven repository.

**Comment by teodord** [comment]
We'll proceed. Thank you!
Teodor

**Comment by teodord** [comment]
I hope this works:
https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports-javaflow/6.20.5/

Thank you,
Teodor
