### ISSUE TITLE
Markup html <div> Tag behaviour 

### ISSUE THREAD

**Issue by flohauer** [TIBCOSoftware/jasperreports#358]
The behaviour of the HTML `<div>-tag` ist different to the standard behaviour.  `javax.swing.JEditorPane.java` seems to treat it like the standard - every `<div>` a new row.
  
**Generated with JasperStudio 6.2.0 ( correct behaviour)**
![grafik](https://github.com/TIBCOSoftware/jasperreports/assets/81151809/9ec4a1fd-2143-4a59-9646-d0df288555de)
  
**Generated with JasperStudio 6.20.0**
![grafik](https://github.com/TIBCOSoftware/jasperreports/assets/81151809/1200c4c3-4d74-4cb6-91de-1d8292dd407a)
  
For the example we used a static-text field but it concerns every field with `markup = html` . 
**html-text:**
`<div>Row 1</div><div>Row 2<div><div>Row 3</div><div>Row 4</div>`

**Comment by teodord** [comment]
This has been fixed since version 6.20.1.
https://github.com/TIBCOSoftware/jasperreports/commit/c6f81fc861e78d5693531d8e64486b5a6af2c24b

Thanks,
Teodor
