### ISSUE TITLE
Error occured when switching from 6.20.1 to 6.20.2

### ISSUE THREAD

**Issue by missaouib** [TIBCOSoftware/jasperreports#359]
An error is occured like below
java.lang.NoSuchMethodError: 'void com.lowagie.text.Document.setGlyphSubstitutionEnabled(boolean)'

**Comment by dadza** [comment]
Previously reported at https://github.com/TIBCOSoftware/jasperreports/issues/350, upgrade to 6.20.5 to avoid the error.
