### ISSUE TITLE
Add Compression on embedded SVG bytes in JasperReport after 2d conversion 

### ISSUE THREAD

**Issue by elvisbegovic** [TIBCOSoftware/jasperreports#361]
Dear team,

First of all, I don’t know if the way I am using this is correct or not. Let me know if this is a good candidate to add feature request of « compression » on pdf having svg converted to 2D context.

actually single SVG of 12ko will increase pdf more than 10times. 

I tried to set true or false option « force SVG shapes » nothing change same size. Does this option pretend solve this size increase (reading Java doc https://javadoc.io/static/net.sf.jasperreports/jasperreports/6.4.3/net/sf/jasperreports/export/PdfReportConfiguration.html#isForceSvgShapes-- from team)

while I use adobe PRO, it will reduce pdf size considerably without affecting image or font, it seems it only remove duplicates objects (x object forms).

![image](https://github.com/TIBCOSoftware/jasperreports/assets/2789203/16b54b61-4621-4d70-94c4-dfafbd510915)

When I analyse the space used in pdf "12 pages svg no-compress.pdf" Adobe Pro tell me that 95% of file is used by "X Object Forms".

When I compress (optimize pdf) using adobe pro , only this "X Object Forms" is reduced more thant 10 times. 

As image or font, does "X Object Forms" (if same in pdf file) because each pdf page have same graphical object, can this exist only once and not n-timesin a doc ? Or there is no room of improvement here ? maybe I should use another solution to keep "fonts in svg , converted as font in pdf and not to X Object Forms".

What you think ?

**Comment by elvisbegovic** [comment]
Dear @teodord what you think, what is your expertise on this
Is my request clear or I am missing st

**Comment by teodord** [comment]
Hi,

This has to do with the fact that when we export SVGs into PDF, we are actually "drawing" them using an iText/OpenPDF provided Graphics2D implementation.
We need to find the way to "embed" the SVG into PDF and reuse it across multiple instances when it repeats in the same PDF.
This is something that needs to be investigated. We've seen this issue in the past, but did not have time to look into it.

Thank you,
Teodor

**Comment by elvisbegovic** [comment]
Dear Teodor, thank you for your input.
May I ask 2 questions: 
1. When you say embed SVG you speak about finality not to embed svg content in pdf, because I was thinking pdf doesn’t know vector word.
2. Do you mean or think this need to be enhanced on itext side? Because jasper juste make use of itext  function?

**Comment by elvisbegovic** [comment]
@teodord thank you lot to get a look into this. 

May I ask, how this is different than previous version, i tried 6.20.5 and 6.20.6 and output size is same.

**Comment by teodord** [comment]
It would simply be easier if you upload here an example showing how you use SVG in the report. 
It is pointless for me to explain what we changed in the code as it would not be immediately apparent why it does not work for you.
