### ISSUE TITLE
Performance drop between version 6.20.0 and 6.20.1 when export to pdf with background image

### ISSUE THREAD

**Issue by JackLaian25** [TIBCOSoftware/jasperreports#362]
Hi,  
I noticed a heavy performance drop when exporting to pdf using background images between version 6.20.0 and 6.20.1.
I use the following code and a simple test report that is attached:

```
 public static void main(String[] args) throws IOException {
        for(int i = 0; i< 20; i++) {
            long start = System.currentTimeMillis();
            String masterReportPath = "PathTo\\SimpleReport.jasper";
            String reportDataPath = "PathTo\\simpleData.json";
            Map<String, Object> parameterMap = new HashMap<>();
            byte[] reportBytes = createReport(masterReportPath, reportDataPath, parameterMap);
            FileUtils.writeByteArrayToFile(new File("C:\\temp\\simpletestWithBackground_6.20.0.pdf"), reportBytes);
            long stop = System.currentTimeMillis();
            System.out.println(stop - start);
        }
    }

public static byte[] createReport(String masterReportPath, String reportDataPath, Map<String,Object> parameterMap) {
        try (InputStream masterReportInputStream = new FileInputStream(masterReportPath)) {
            JasperReport masterReport = (JasperReport) JRLoader.loadObject(masterReportInputStream);
            InputStream reportDataInputStream = new FileInputStream(reportDataPath);
            parameterMap.put(JsonQueryExecuterFactory.JSON_INPUT_STREAM, reportDataInputStream);
            SimpleJasperReportsContext jrContext = new SimpleJasperReportsContext();
            JasperFillManager fillManager = JasperFillManager.getInstance(jrContext);
            JasperPrint jasperPrint = fillManager.fill(masterReport, parameterMap);
            JRPdfExporter exporter = new JRPdfExporter();
            SimpleExporterInput exporterInput = new SimpleExporterInput(jasperPrint);
            exporter.setExporterInput(exporterInput);
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            SimpleOutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(outputStream);
            exporter.setExporterOutput(exporterOutput);
            exporter.exportReport();
            return outputStream.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

My performance messuring shows the following results in milliseconds. The file size is increased as well:   
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/t02078a/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/t02078a/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Jasper version | 6.20.0 | 6.20.1
-- | -- | --
File size | 49 KB | 177 KB
1 first run | 3198 | 4234
2 | 101 | 892
3 | 101 | 674
4 | 84 | 669
5 | 84 | 707
6 | 82 | 644
7 | 69 | 668
8 | 71 | 654
9 | 63 | 676
10 | 64 | 642
11 | 63 | 636
12 | 53 | 622
13 | 52 | 629
14 | 53 | 629
15 | 48 | 626
16 | 49 | 643
17 | 43 | 639
18 | 44 | 630
19 | 43 | 631
20 | 47 | 631
  |   |  
Avg. without first run | 64 | 660

</body>

</html>  

Any idea what causes this problem?

[TestData.zip](https://github.com/TIBCOSoftware/jasperreports/files/11703544/TestData.zip)

**Comment by albfernandez** [comment]
I think it's caused by the OpenPdf migration.

OpenPDF has removed al custom image parsing and delegate to the JVM codecs. These JVM codecs seems to be slow.

[https://github.com/LibrePDF/OpenPDF/issues/596](https://github.com/LibrePDF/OpenPDF/issues/596)

**Comment by JackLaian25** [comment]
Hi,
thank you for your answer. Yes this seems to be the problem. OpenPDF uses ImageIO.read which uses com.sun.imageio.plugins.png.PNGImageReader that has a unefficent way of reading the png file. 
It is possible to replace this ImageReader with a different implementation of PNGReader within ImageIO using the ImageReaderSpi service provider. Maybe someone can find a more efficent way of reading png when using jasper reports.

**Comment by JackLaian25** [comment]
Oh sorry, forgot to attache it. It's attached now.

**Comment by dadza** [comment]
I ran your test and there is a clear major performance drop in 6.20.1.

However the numbers do not quite match what you're reporting.

What I'm seeing are the following numbers for 6.20.0:
```
avg time 364
size 189329
```

And these for 6.20.1:
```
avg time 570
size 180301
```

So the performance drop is around 50-60% and there is no PDF size increase.

Can you run the following command in the attached project (maven based)?
`mvn clean package exec:java -Dexec.mainClass=gh362.GH362`

We need to understand if there something in your environment that explains the different numbers.

[gh362-project.zip](https://github.com/TIBCOSoftware/jasperreports/files/11707979/gh362-project.zip)

**Comment by Postremus** [comment]
@dadza
Also facing the performance drop. Just as another datapoint here are my results using different jdks on windows 10.

java:
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

6.20.0:
```
avg time 426
size 189330
```

6.20.1
```
avg time 520
size 180302
```




java:
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

6.20.0:
```
avg time 468
size 189330
```

6.20.1
```
avg time 529
size 180302
```

java:
openjdk 19 2022-09-20
OpenJDK Runtime Environment Temurin-19+36 (build 19+36)
OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode, sharing)

6.20.0:
```
avg time 416
size 189330
```

6.20.1
```
avg time 519
size 180302
```



java:
openjdk 21-ea 2023-09-19
OpenJDK Runtime Environment (build 21-ea+25-2212)
OpenJDK 64-Bit Server VM (build 21-ea+25-2212, mixed mode, sharing)

6.20.0:
```
avg time 429
size 189330
```

6.20.1
```
avg time 508
size 180302
```

**Comment by JackLaian25** [comment]
I was editing the png file before uploding it here. If I use the original png file you can see the performance as discribed in my first post. I attach the original png file. Please run your test with that png file.

![LN2215](https://github.com/TIBCOSoftware/jasperreports/assets/48066953/323248ef-015a-40fd-8307-a30adadc4165)

**Comment by dadza** [comment]
@JackLaian25 thank you, the latest PNG does indeed result in times similar to what you reported initially.

The reason that PNG is so fast with iText is that there's an optimization to directly copy the compressed image data from the PNG file into the PDF document when some conditions are met (grayscale color type, etc).  That's much faster than decoding the PNG image data and recompressing it as a PDF image, which is what happens when the optimization doesn't apply in iText and always in OpenPDF (with ImageIO instead of the iText PNG decoder).

**Comment by teodord** [comment]
We have put iText behind us. Whatever reasons OpenPDF had to remove these image processing techniques from their iText fork, either related to copyright issues or anything else, it is unlikely that we are going patch OpenPDF ourselves to put them back.
We just need to accept the fact that these optimisations that existed for very special types of images are no longer there.

**Comment by JackLaian25** [comment]
Hello teodord,
thank you very much for your answer. I understand the reasons for changing from iText 2 to OpenPDF. Would it be a solution if we use this exporter implementation?  
https://github.com/Jaspersoft/jasperreports-pdf-lib7/tree/master
Is it still maintained or is it obsolete since itext is removed completly in version 6.20.1
Best regards.

**Comment by teodord** [comment]
The JasperReports Library PDF exporter based on iText 7+ that we published at:
https://github.com/Jaspersoft/jasperreports-pdf-lib7
is an attempt we had to support iText 7 for those who want to go that route.
As far as we can tell right now, the project did not get much traction, although we still plan to maintain it going forward.

The problem is that due to lack of traction/interest, we could not afford to put too much effort into it, as the PDF exporter tends to be very delicate and rich in functionality. Thus we were not able to achieve the same level of quality we have in our classical exporter. Also, some features have changed in iText and reimplementation of our exporter features to adapt to those is very tedious work.

Note that iText 7 is released under AGPL license, which prevents use in commercial products, unless commercial license is acquired from iText. That's why we had to create a separate AGPL project ourselves, to be compliant with AGPL of iText 7 (viral license).

I think that for now, the lib7 exporter is not up-to-date and production ready. It might be in the future, but we do not have specific plans for it right now.

Thank you,
Teodor

**Comment by andreasrosdal** [comment]
A pull request to fix this in OpenPDF would be welcome.

"The reason that PNG is so fast with iText is that there's an optimization to directly copy the compressed image data from the PNG file into the PDF document when some conditions are met (grayscale color type, etc). That's much faster than decoding the PNG image data and recompressing it as a PDF image,"
