### ISSUE TITLE
gray boxes where barcodes should be

### ISSUE THREAD

**Issue by Postremus** [TIBCOSoftware/jasperreports#363]
In my pdf reports I often use barbecue barcodes.

Since 6.20.1, I noticed that my barcodes are phyiscally print (to paper) as gray boxes when activating the option "Farbe/Toner sparen" (save color/toner) in Adobe Acrobat Reader.

This is the setting I mean:
![image](https://github.com/TIBCOSoftware/jasperreports/assets/1223135/d97a7529-1f5d-4e71-9705-07ead8e35997)

My jrxml:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.20.1.final using JasperReports Library version 6.20.1-7584acb244139816654f64e2fd57a00d3e31921e  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="Blank_A4" pageWidth="595" pageHeight="842" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="9d29a04f-4476-4e7a-88e8-08c55519d8b7">
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="One Empty Record"/>
	<queryString>
		<![CDATA[]]>
	</queryString>
	<background>
		<band splitType="Stretch"/>
	</background>
	<title>
		<band height="79" splitType="Stretch"/>
	</title>
	<pageHeader>
		<band height="35" splitType="Stretch"/>
	</pageHeader>
	<columnHeader>
		<band height="61" splitType="Stretch"/>
	</columnHeader>
	<detail>
		<band height="130" splitType="Stretch">
			<componentElement>
				<reportElement x="60" y="10" width="440" height="120" uuid="fa9b9997-6c66-4181-98de-8ef30ec9d5be"/>
				<jr:barbecue xmlns:jr="http://jasperreports.sourceforge.net/jasperreports/components" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports/components http://jasperreports.sourceforge.net/xsd/components.xsd" type="Code128" drawText="false" checksumRequired="false" barHeight="80" evaluationTime="Page">
					<jr:codeExpression><![CDATA["00340373630102567301"]]></jr:codeExpression>
				</jr:barbecue>
			</componentElement>
		</band>
	</detail>
	<columnFooter>
		<band height="130" splitType="Stretch">
			<componentElement>
				<reportElement x="120" y="0" width="455" height="103" uuid="cdb2fda0-cdfa-441c-b89d-504630b4a647"/>
				<jr:Code128 xmlns:jr="http://jasperreports.sourceforge.net/jasperreports/components" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports/components http://jasperreports.sourceforge.net/xsd/components.xsd">
					<jr:codeExpression><![CDATA["00340373630102567301"]]></jr:codeExpression>
				</jr:Code128>
			</componentElement>
		</band>
	</columnFooter>
	<pageFooter>
		<band height="54" splitType="Stretch"/>
	</pageFooter>
	<summary>
		<band height="42" splitType="Stretch"/>
	</summary>
</jasperReport>
```

This is the printed result (added text in paint for clarification):
![1687156055156](https://github.com/TIBCOSoftware/jasperreports/assets/1223135/1562a912-aa34-4c61-9a0b-7aa6a36d0735)

You can also reproduce this without wasting paper.
* Select "save color" in adobe
* select an pdf printer (like the microsoft print to pdf one)
* erweitert
* ![image](https://github.com/TIBCOSoftware/jasperreports/assets/1223135/424e1a6d-5510-49c3-b0d8-16db75338780)
* and then print.
* A .prn file will be created
* open the .prn in adobe (just drag the file into adobe acrobat reader)
* gray boxes where the barcodes should be

**Comment by teodord** [comment]
The problem seems to be coming from the replacement of iText with OpenPDF and is not isolated to barcodes, but also present for charts and other graphics.

Thank you,
Teodor

**Comment by dadza** [comment]
OpenPDF changed the way images are decoded as compared to iText.  With the OpenPDF image decoder, the color from a transparent GIF used by the PDF exporter interfered with the Save Color/Toner print setting.

The problem has been fixed by using a transparent PNG image instead of the original GIF.  We are also working on removing the use of a transparent image in the exporter (at least in the cases in which it's not necessary).
