### ISSUE TITLE
Export Blank Pdf 

### ISSUE THREAD

**Issue by panchal20bhavin** [TIBCOSoftware/jasperreports#365]
Hi,

I found one bug in jasper library. Basically I export pdf using Jasper library code not using Jasper studio. 
Here is my code which export the blank pdf,
	
	@Override
	public void run(String... args) throws Exception {
	
	   Map<String, Object> parameters = new HashMap<>();
        parameters.put("parameter1", "First Parameter");
        parameters.put("parameter2", "Second Parameter");
			

		JasperReport jasperReport;
		JasperDesign jDesign = getJasperDesign();
		jasperReport = JasperCompileManager.compileReport(jDesign);

		JasperPrint jPrint = JasperFillManager.fillReport(jasperReport, parameters);
		
		 File theDir = new File("F:\\Bhavin\\Temp");
         if(!theDir.exists()) {
             theDir.mkdirs();
         }
		  JasperExportManager.exportReportToPdfFile(jPrint,
				  "F:\\Bhavin\\Temp" + "\\exportFile.pdf");
		System.out.println("finished.....");
	}

	private JasperDesign getJasperDesign() throws Exception {
		// TODO Auto-generated method stub
		JasperDesign jasperDesign = new JasperDesign();
		jasperDesign.setName("exportFile");
		jasperDesign.setPageWidth(595);
		jasperDesign.setPageHeight(842);
		jasperDesign.setColumnWidth(555);
		jasperDesign.setLeftMargin(20);
		jasperDesign.setRightMargin(20);
		jasperDesign.setTopMargin(20);
		jasperDesign.setBottomMargin(20);
		jasperDesign.setOrientation(OrientationEnum.LANDSCAPE);

		JRDesignParameter parameter = new JRDesignParameter();
		parameter.setName("parameter1");
		parameter.setValueClass(java.lang.String.class);
		jasperDesign.addParameter(parameter);
		
		JRDesignField field = new JRDesignField();
		field.setValueClass(String.class);
		field.setName("field");
		jasperDesign.addField(field);
		
		JRDesignParameter parameter1 = new JRDesignParameter();
		parameter1.setName("parameter2");
		parameter1.setValueClass(java.lang.String.class);
		jasperDesign.addParameter(parameter1);

		JRDesignBand band = null;
		/* Title Band */
		band = new JRDesignBand();
		band.setHeight(265);
		band.setSplitType(SplitTypeEnum.IMMEDIATE);

		JRDesignTextField textField;
		JRDesignStaticText staticText;
		JRDesignRectangle rectagle;
		JRPen pen;
		JRDesignGraphicElement graphic;
		JRLineBox box;
		JRDesignImage img;
		JRDesignLine line;
		JRDesignExpression jrExpression;

		textField = new JRDesignTextField();
		textField.setX(39);
		textField.setY(-1);
		textField.setWidth(179);
		textField.setHeight(20);
		textField.setFontSize(16f);
		textField.setBold(Boolean.TRUE);
		textField.setForecolor(Color.decode("#093B5C"));
		box = textField.getLineBox();
		pen = box.getPen();
		pen.setLineWidth(new Float(0.0));
		pen.setLineStyle(LineStyleEnum.SOLID);
		JRBoxPen topPen = box.getTopPen();
		topPen.setLineWidth(new Float(0.0));
		topPen.setLineStyle(LineStyleEnum.SOLID);
		topPen.setLineColor(Color.decode("#000000"));
		JRBoxPen leftPen = box.getLeftPen();
		leftPen.setLineWidth(new Float(0.0));
		leftPen.setLineStyle(LineStyleEnum.SOLID);
		leftPen.setLineColor(Color.decode("#000000"));
		JRBoxPen bottomPen = box.getBottomPen();
		bottomPen.setLineWidth(new Float(0.0));
		bottomPen.setLineColor(Color.decode("#000000"));
		bottomPen.setLineStyle(LineStyleEnum.SOLID);
		JRBoxPen rightPen = box.getRightPen();
		rightPen.setLineWidth(new Float(0.0));
		rightPen.setLineStyle(LineStyleEnum.SOLID);
		rightPen.setLineColor(Color.decode("#000000"));
		jrExpression = new JRDesignExpression();
		jrExpression.setText("$P{parameter1}");
		textField.setExpression(jrExpression);
		band.addElement(textField);

		textField = new JRDesignTextField();
		textField.setX(41);
		textField.setY(21);
		textField.setWidth(259);
		textField.setHeight(15);
		textField.setFontSize(10f);
		textField.setForecolor(Color.decode("#093B5C"));
		jrExpression = new JRDesignExpression();
		jrExpression.setText("$P{parameter2}");
		textField.setExpression(jrExpression);
		band.addElement(textField);
		// set title
		jasperDesign.setTitle(band);

		/* detail Band */
		band = new JRDesignBand();
		band.setHeight(650);
		band.setSplitType(SplitTypeEnum.IMMEDIATE);
		((JRDesignSection) jasperDesign.getDetailSection()).addBand(band);
		return jasperDesign;
	}

}
 

But if I add one field then I got printed PDF.
Here modify code which export with data,

      List<Map<String, ?>> preparedData = new ArrayList<>();
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("field", "new Project");
        preparedData.add(map);
        
        JasperPrint jPrint = JasperFillManager.fillReport(jasperReport, parameters, new JRBeanCollectionDataSource(preparedData));
        

I am using v6.20.5 net.sf.jasperreports. And it is mandatory to add minimum one field in jasper design?
Because without field i can not generate the pdf.

**Comment by dadza** [comment]
It's not a bug, it's the intended behaviour.  See https://community.jaspersoft.com/wiki/empty-report-problem

If you want the report to display the title band without a data source, you need to set

`jasperDesign.setWhenNoDataType(WhenNoDataTypeEnum.ALL_SECTIONS_NO_DETAIL);`
