### ISSUE TITLE
Native Support?

### ISSUE THREAD

**Issue by korkutkose** [TIBCOSoftware/jasperreports#366]
Hi everyone,
Is there a plan on your road map to support native images? Currently we are forced to generate necessary reflections with tracing agent and update necessary parts of the project for the reflections and proxies.
It would be awesome to have out of box support or support via graalvm's reachability metadata perhaps.
Cheers.

**Comment by teodord** [comment]
Hi,

There is no plan for this on our side yet. If you have expertise in this field, maybe you can help us prepare for it.

Thank you,
Teodor
