### ISSUE TITLE
avoid Class.forName - use ServiceLoader Pattern - SaveContributors

### ISSUE THREAD

**Issue by stbischof** [TIBCOSoftware/jasperreports#370]
https://github.com/TIBCOSoftware/jasperreports/blob/6f6ede1a55668923afe97158a602e32d5880dae0/jasperreports/src/net/sf/jasperreports/view/SaveContributorUtils.java#L46-L76

**Comment by teodord** [comment]
Fixed at https://github.com/TIBCOSoftware/jasperreports/commit/7d72d055ddd476fc0b0c044a553e42eccaae0755

Thank you,
Teodor
