### ISSUE TITLE
Support jfreechart v1.5.x

### ISSUE THREAD

**Issue by eyinsma** [TIBCOSoftware/jasperreports#373]
Currently jasperreports only support jfreechart v1.0.x, which was released 10 years back, Request to upgrade to use jfreechart v1.5.x.

**Comment by shertage** [comment]
Hi,

After switching to jfreecharts v1.5.x, the former free jfreecharts 3D charts won't be available/supported anymore. They were migrated to a different charting library (under GPL license): [http://www.object-refinery.com/orsoncharts/index.html](http://www.object-refinery.com/orsoncharts/index.html)
Would you consider to use 2D-only charts in your projects, after this upgrade?

Thank you,
Sanda

**Comment by LuciferSam86** [comment]
For me I am using 3D charts outside, making them with matplotlib via webservice and save them as png. 

I would like to see a more updated 2D charts only in Jasper.

**Comment by mmonetha-sobis** [comment]
+1

**Comment by teodord** [comment]
JFreeChart has been upgraded to 1.5.4 in the upcoming 7 release.

Thanks,
Teodor
