### ISSUE TITLE
When could move to jakarta name space

### ISSUE THREAD

**Issue by wenbin9** [TIBCOSoftware/jasperreports#378]
Dear Jasperreport teams,

Currently we plan move to spring boot3, but it seems latest jasperreport  version do not support jakarta servlets.
Is there any plan when jasperreport could support jakarta servlet、spring6 and hibernate6? 
Thanks so much!

**Comment by teodord** [comment]
Hi,

This is currently tracked here:
https://github.com/TIBCOSoftware/jasperreports/issues/321

Thank you,
Teodor

**Comment by wenbin9** [comment]
@teodord Thanks for quick response!

**Comment by teodord** [comment]
You can try out snapshots of the release-7.0.0 branch to see the Jakarta Migration progress.
Snapshots are published on Maven repository at:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/7.0.0-SNAPSHOT/
