### ISSUE TITLE
Editing Rotate Property for both (Field & Static) Text

### ISSUE THREAD

**Issue by halimpuckjava** [TIBCOSoftware/jasperreports#388]
hi

i suggest to add custom angle to rotate texts

**Comment by teodord** [comment]
I'm not sure which export format are you targeting. Not all export formats support arbitrary rotation of text and we want to be consistent as much as possible across all export formats.

**Comment by halimpuckjava** [comment]
hi @teodord 

i think you dont understand what i suggest, when using static text or field etxt i want to rotate it with custom angle (property rotate i want to make it editable)

**Comment by teodord** [comment]
I think I understood that. But still, you did not say which export format you are interested in: HTML, PDF, DOCX, Excel?...
Not all of them support custom rotation angles.

**Comment by halimpuckjava** [comment]
hi

only PDF & DOCX & XLSX formats

**Comment by halimpuckjava** [comment]
@teodord 

you say you rotate with 90, 180, 270 degree, so why not add more measures like 30, 45 degre, or more why not make this property editable

**Comment by teodord** [comment]
Please attach here a PDF, an Excel file and a DOCX file, all showing how you expect a text element to be rotated and an arbitrary angle, let's say 45 degrees to the left. Please use a text element that has border and background color. Hopefully all 3 files would present the same text field scenario so that we can compare the expected output across the 3 document formats.

Thank you,
Teodor

**Comment by teodord** [comment]
Are you talking about watermark images in the background of the document page?
Is this the only reason you want to rotate text?
If so, why can't you use an SVG and put in an image element in the background section of the report?
You can see us using a watermark background image in the /demo/samples/query sample here:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/demo/samples/query/reports/QueryReport.jrxml#L64

And BTW, how would you expect this rotated text in the background to work in a Excel worksheet?

Thank you,
Teodor

**Comment by halimpuckjava** [comment]
hi

no i dont want to put image in background, just i want to make a text in background with custom rotation

**Comment by teodord** [comment]
I am still waiting for PDF, DOCX and especially Excel files that would demonstrate the exact output you expect from such rotated texts. So far, you only provided a GIF, which I'm not even sure what document format it presents in the screenshot.

I assume that if you are asking for such a specific thing: arbitrary rotates texts, you must have seen them before, so you can share some of these documents with us to better understand expectations. I'm particularily interested in seeing an Excel one, as you mentioned you target Excel files.

Thank you,
Teodor

**Comment by halimpuckjava** [comment]
until now you dont understand me, i just want to put text in background section (as watermark) and change rotation property for this text, that what i want

**Comment by teodord** [comment]
We are not going to write hundreds of lines of code to achieve something that can already be done with the product today.
You say you don't want to use SVG, but text elements. OK, it is up to you. It is your preference.

I am attaching here a PDF that has been generated using our /demo/samples/table sample from the project distribution using an SVG placed in the background section.

[TableReport.pdf](https://github.com/TIBCOSoftware/jasperreports/files/12583292/TableReport.pdf)

![sample](https://github.com/TIBCOSoftware/jasperreports/assets/2511035/789564d7-48c5-4601-aa2d-9010bbef04e3)

[TableReport.jrxml.zip](https://github.com/TIBCOSoftware/jasperreports/files/12583309/TableReport.jrxml.zip)
