### ISSUE TITLE
Could not GET 'https://repo.spring.io/plugins-snapshot/com/github/librepdf/openpdf/1.3.30.jaspersoft.2/openpdf-1.3.30.jaspersoft.2.pom'. Received status code 401 from server: 

### ISSUE THREAD

**Issue by gourigs123** [TIBCOSoftware/jasperreports#390]

**Comment by teodord** [comment]
Have you put the OpenPDF 1.3.30.jaspersoft.2 dependency in your own pom.xml file or are you getting it transiently through the jasperreports dependency?

**Comment by teodord** [comment]
Anyway. What I wanted to say is that the OpenPDF is actually coming into the build transiently from the jasperreports dependency, which has the jaspersoft.jfrog.io artifactory declared in its own pom.xml file.
So you should have not problem with OpenPDF coming into your build transiently this way.
But if you declared the OpenPDF version 1.3.30.jaspersoft.2 explicitly into your own pom.xml, then you need to declare also the Maven repo where it is avaiable and you can see it here:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/pom-parent.xml#L90
