### ISSUE TITLE
Is extending to the "JRXmlDataSource.class" in our custom datasource allowed?

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#393]
Hi Team,

We want to create the custom XML datasource by inheriting the jasper's JRXmlDataSource datasource.
Can you please let us know, is extending "JRXmlDataSource" class is supported?

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

We don't plan to make dramatic changes to this class that would break subclasses. An indication that such thing is unlikely is if you look at the git history of the file.
Not sure what you mean by "supported". If you are looking for support services, you might want  to contact Jaspersoft.com.

Thank you,
Teodor

**Comment by tuspatil1** [comment]
Hi Teodor,

Supported means, we just want to clarify that, is extending(inheritance) the "JRXmlDataSource.class" in our custom datasource class is allowed? Or does TIBCO not recommend this?

Thanks,
Tushar

**Comment by tuspatil1** [comment]
Hi Teodor,

Supported means, we just want to clarify that, is extending(inheritance) the "JRXmlDataSource.class" in our custom datasource class is allowed? Or does TIBCO not recommend this?

Thanks,
Tushar

**Comment by tuspatil1** [comment]
Hi Teodor,

Can you please respond on my last query?

Thanks,
Tushar

**Comment by tuspatil1** [comment]
Hi Teodor,

Can you please respond on my last query?

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

If you need to extend a class to achieve something, than I guess that's what you have to do then. So go for it!
In my previous reply I already mentioned such classes do not tend to change much for years and years.
I don't see why we would make backward incompatible changes to it any time soon.

We cannot offer you recommendations about which classes to subclass or not. In Java, we usually go by the rule that interfaces should not change. But implementing classes, there is not necessarily a rule.

I'm not sure what kind of guarantees you are looking for. How firm such a promise should be? Who knows what the future reserves to us? It is more important to be able to adapt to future and evolve than to get stuck with things that never change.

If something is guaranteed not to change, than there is no chance for it to ever get better, if needed.

I hope this helps.
Teodor

**Comment by tuspatil1** [comment]
Thanks Teodor for response. I undestood.
