### ISSUE TITLE
WebP support in PDF generation

### ISSUE THREAD

**Issue by woprandi** [TIBCOSoftware/jasperreports#394]
On Jasper Studio I have an error when trying to preview a PDF report with a WebP image inside. 
`Reason java.io.IOException: The byte array is not a reconized imageformat`
I was unable to find any information about supported image formats except searching in the source code itself... Is WebP format supported for PDF ? I guess not

**Comment by teodord** [comment]
This has been fixed for the next release. As long as you have an ImageIO extension with support for WEBP images in your classpath, it will work. In our sample, we now use:
https://search.maven.org/artifact/org.sejda.imageio/webp-imageio/0.1.6/jar

**Comment by woprandi** [comment]
@teodord Do you have an ETA ?

**Comment by teodord** [comment]
Probably a few weeks. For sure a new release would be out before the end of the year.
