### ISSUE TITLE
runReportToPdf throws Unknown property for java records

### ISSUE THREAD

**Issue by vukmanovicmilos** [TIBCOSoftware/jasperreports#396]
`JasperRunManager.runReportToPdf(jasperReport, params, dataSource);`
 throws java.lang.NoSuchMethodException: Unknown property when datasource is 
`JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(listOfRecords);` because trying to call **get** method on a record, when create custom method in a record that name start with get it works.

**Comment by teodord** [comment]
You need to provide the entire stack trace of the exception.
This is probably caused by a mismatch between a field name in the report dataset and the getter method of the property you try to read from the current record bean in the collection.
