### ISSUE TITLE
Getting heap size full with JRFileVirtualizer

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#397]
Hi Team,

We are using jasperreports-6.20.1 community edidtion.
We are doing the performance testing of three virtualizers at our side with 10+ concurrent executions. We observed that the report on the "x" amount of a large dataset is getting generated successfully with **JRGzipVirtualizer** , but the same report on the same dataset is failing with **JRFileVirtualizer**. As per our logs, heap size is getting highly utilized by **JRFileVirtualizer**.

Can you please help us to understand if this is observed at the Jaspersoft side as well, that JRFileVirtualizer utilizes more heap size than JRGzipVirtualizer? Or can you please suggest, if there is any way to optimize the heap size utilization for **JRFileVirtualizer**?

Thanks,
Tushar

**Comment by dadza** [comment]
No, we haven't seen a case in which JRFileVirtualizer uses more heap than JRGzipVirtualizer.

Please attach a self contained test case to reproduce what you're seeing on our side.

Regards,
Lucian

**Comment by teodord** [comment]
Hi,

Feel free to reopen this if you can provide more details about this.

Thank you,
Teodor
