### ISSUE TITLE
Replace custom fork of OpenPDF with newly released version on Maven Central

### ISSUE THREAD

**Issue by zimmi** [TIBCOSoftware/jasperreports#398]
Hi,

OpenPDF 1.3.32 is now available on [Maven Central](https://repo1.maven.org/maven2/com/github/librepdf/openpdf/1.3.32/), which contains the fix for https://github.com/LibrePDF/OpenPDF/issues/676 (PR: https://github.com/LibrePDF/OpenPDF/pull/903). If I'm understanding correctly, this was the reason to use a custom fork of OpenPDF in JasperReports. That means we can switch to the official 1.3.32 now, correct?

References:
https://github.com/LibrePDF/OpenPDF/issues/961
https://github.com/LibrePDF/OpenPDF/issues/974
https://github.com/TIBCOSoftware/jasperreports/issues/339
https://github.com/TIBCOSoftware/jasperreports/issues/351

Best regards,
zimmi

**Comment by zimmi** [comment]
Awesome, thank you for doing this @dadza ! :)

**Comment by arvera** [comment]
Am I crazy or this broken on implementation 'net.sf.jasperreports:jasperreports:6.21.0 ? I am getting error for the PDF creation

**Comment by arvera** [comment]
Hmm there is something funny.. do I need to add dependancy explicitly? 

i am getting the following error even with 6.20.6: 

```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.librepdf:openpdf:1.3.30.jaspersoft.3.
     Required by:
         project : > net.sf.jasperreports:jasperreports:6.20.6
```

**Comment by arvera** [comment]
Okay.. I got everything working using: 
```
        implementation 'net.sf.jasperreports:jasperreports:6.20.6'
	//implementation 'com.lowagie:itext:2.1.7'
	implementation 'com.itextpdf:itextpdf:5.5.13.3'
	implementation 'com.github.librepdf:openpdf:1.3.32'
```

I can now create a PDF sucessfuly without getting the NoClassDefFound for several classes

**Comment by zimmi** [comment]
@arvera Judging by the [release page for 6.21.0](https://github.com/TIBCOSoftware/jasperreports/releases/tag/6.21.0), the fix is in a commit that happened after the release. So we'll have to wait for the next release.
