### ISSUE TITLE
Implementation-Version manifest entry value is not up to date

### ISSUE THREAD

**Issue by InfiniteLoop90** [TIBCOSoftware/jasperreports#40]
The `Implementation-Version` manifest entry defined [here](https://github.com/TIBCOSoftware/jasperreports/blob/ec68934751f1fecb7227a56f95cf2a4e3064634b/jasperreports/src/META-INF/MANIFEST.MF#L7) was not updated for the 6.7.0 release.

This results in calls to `Package.getPackage("net.sf.jasperreports.engine").getImplementationVersion();` at runtime report that it's JasperReports version 6.6.0, not 6.7.0. This is done in a few spots in the JasperReports source code such as in the [PDF exporter](https://github.com/TIBCOSoftware/jasperreports/blob/ec68934751f1fecb7227a56f95cf2a4e3064634b/jasperreports/src/net/sf/jasperreports/engine/export/JRPdfExporter.java#L774).

I'm unsure if the final JAR for this project is built with Maven or Ivy, but if it's built with Maven it might be worth applying filtering to the MANIFEST.MF file and use `${pom.version}` as the value of the `Implementation-Version` manifest entry so that it doesn't have to be manually changed each time there's a new JasperReports version.

**Comment by teodord** [comment]
Thanks for catching this. Unfortunately, it is too late for 6.7.0, as it was already published with Maven and has spread out far and wide. Can't take it back. Will pay attention next time.

**Comment by InfiniteLoop90** [comment]
Sounds good.

@teodord When this project gets built for release, is it done using Maven or Ivy? If it’s Maven, I’d be happy to open a PR to implement my above suggestion.
