### ISSUE TITLE
Is "jasperreports-html-component.jar" mandatory to export jasper reports?

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#401]
Hi Team,

We are using the "jasperreports-6.20.1" library [community edition] to generate the jasper reports.
As per our understanding, "jasperreports-html-component.jar" is not officially supported by TIBCO; hence, we are trying to remove this library from our classpath, but we are getting the below exception while exporting jasperprint in HTML, PDF, XLSX, and CSV using HtmlExporter, JRPdfExporter, ExcelAbstractExporter, and JRCsvExporter, respectively:

**_java.lang.NoClassDefFoundError: net/sf/jasperreports/extensions/HtmlElementHandlerBundle_**

Please let us know if "jasperreports-html-component.jar" is mandatory to export Jasper reports. OR Is there any alternative to skip the uses of this jar?

Thanks,
Tushar

**Comment by teodord** [comment]
This component is not mandatory. None of our samples have it in their classpath and they all work fine.

Seeing the entire stack trace with the exception you get might help understand what is wrong in your case.

**Comment by tuspatil1** [comment]
[Logs-2311081128-5530-log4j.zip](https://github.com/TIBCOSoftware/jasperreports/files/13304847/Logs-2311081128-5530-log4j.zip)
Hi Teodor,

Please refer attached logs for stacktrace.

Thanks,
Tushar

**Comment by dadza** [comment]
`	at com.ptc.jasperreports.extensions.CustomHtmlElementExtensionsRegistryFactory$1.getExtensions(CustomHtmlElementExtensionsRegistryFactory.java:33)
`

The com.ptc.jasperreports... class is not part of JasperReports or any other TIBCO products, please check with the author of that class.

Regards,
Lucian
