### ISSUE TITLE
Provide a migration guide to prevent usage of the net.sf.jasperreports.legacy.text.measuring that appeared in 6.20.5

### ISSUE THREAD

**Issue by ulk200** [TIBCOSoftware/jasperreports#405]
The generation of some of our reports changed after migrating to [6.20.5](https://github.com/TIBCOSoftware/jasperreports/releases/tag/6.20.5)
We had to set the new property `net.sf.jasperreports.legacy.text.measuring` to `true` to fix this.
We understand that this is a temporary fix and that this property may disappear in the future, since it's flagged as deprecated since day one.

Is there a way to check all of our reports that are affected by this to that we can change them ? And what is the "official" way to fix it to remain pixel perfect before and after ?

Thanks

**Comment by teodord** [comment]
All reports having textAdjust="StretchHeight" (or formed isStretchWithOverflow="true") are supposed to be affected.
The only recommendation about migration that I could do is to use the legacy property at report level and allow new reports to be designed according to the new behaviour, to minimise impact in case in case some day the legacy behaviour would be eliminated (not planning to do so any time soon).
