### ISSUE TITLE
JasperReports Library 7 branch

### ISSUE THREAD

**Issue by stbischof** [TIBCOSoftware/jasperreports#408]
The README.MD describes the existance of an `JasperReports Library 7 branch`. Where could this be found?

We Would like to help with tome OSGi support.

**Comment by abdorah** [comment]
@stbischof Yeah I am really excited for the new fixes: 
![image](https://github.com/TIBCOSoftware/jasperreports/assets/37270435/2e234d54-6165-4b1c-804b-43b9cd710bf8)
 especially getting rid of this log (sorry but it's annoying).
 
Thank you everyone for your work!

**Comment by stbischof** [comment]
As soon the Release 7 branch is accessible i would  to help on this.

**Comment by teodord** [comment]
release-7.0.0 branch is public again:
https://github.com/TIBCOSoftware/jasperreports/tree/release-7.0.0
