### ISSUE TITLE
pdfa (pdfa1a) usage in JasperReports produces invalid format when a hyperlink is used

### ISSUE THREAD

**Issue by jwkaltz** [TIBCOSoftware/jasperreports#410]
When setting a JasperReports JRXML file to be PDF/A-1A compliant (pdfa1a), the validation of the compliance by a tool such as VeraPDF is successful. But when the JRXML file contains a Hyperlink, the PDF which is output by JasperReports is no longer compliant. Validation fails with this rule:
_"An annotation dictionary shall contain the F key. The F key's Print flag bit shall be set to 1 and its Hidden, Invisible and NoView flag bits shall be set to 0."_
See details at https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-653-2

After consulting the current options in documentation and code, I think there is currently no way to produce a fully compliant PDF/A-1A file with JasperReports which includes a hyperlink - or am I missing something?

Please see attached a minimal example which showcases this issue; in the file without a hyperlink the PDF/A-1A compliance is verified, in the file with the hyperlink, it fails:
[example_for_jasper_with_hyperlink.zip](https://github.com/TIBCOSoftware/jasperreports/files/13787127/example_for_jasper_with_hyperlink.zip)

**Comment by teodord** [comment]
Can you please try the latest 6.21.2 release which uses OpenPDF 1.3.32?

**Comment by vuilleumierc** [comment]
I can confirm it works with 6.21.2 (annotations are PDF/A conform)
