### ISSUE TITLE
java 17

### ISSUE THREAD

**Issue by shycoldii** [TIBCOSoftware/jasperreports#414]
Hello! Do you now have full support for java 17? If yes, then from which version?
Thanks for answer.

**Comment by teodord** [comment]
Did you try JasperReports with Java 17 and it did not work?

**Comment by shycoldii** [comment]
Yes, I tried it - it general works. It would be convenient to have a description of supported versions in the README (due to transitive dependencies, many libraries have not been updated). Because on the Internet in the question/answers the issue on this matter has not been closed, perhaps there could be some problems in some situations.

thanks.
