### ISSUE TITLE
Question: Where is JasperStudio source code repository?

### ISSUE THREAD

**Issue by LuciferSam86** [TIBCOSoftware/jasperreports#415]
Hello there,
I keep seeing JasperStudio is "Open Source" under the EPL license, but I don't see the source repo.

Where is it?
Did it change the license and the description like here https://sourceforge.net/projects/jasperstudio/ is wrong?

**Comment by teodord** [comment]
This has been addressed on the Jaspersoft community website:
https://community.jaspersoft.com/forums/topic/68147-updates-to-the-jaspersoft-community-edition-download/#comment-161895
