### ISSUE TITLE
Getting "PatchedPdfLibraryUnavailableException" after upgrading to jasperreports-6.20.5/6

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#416]
Hi Lucian

As per below link, if we upgrade to **OpenPDF 1.3.32**, then we don't need patched version of OpenPDF. Right?
[https://github.com/TIBCOSoftware/jasperreports/issues/398](url)

If yes, is this applicable to community & commercial version jasperreports-6.21.0 both?

Thanks,
Tushar

_Originally posted by @tuspatil1 in https://github.com/TIBCOSoftware/jasperreports/issues/395#issuecomment-1923767867_

**Comment by tuspatil1** [comment]
Hi Team

Can anyone please update on this?

Thanks,
Tushar

**Comment by teodord** [comment]
As you can see, the commit mentioned when the tracker was closed is not part of any release yet. It is present only in master branch, which is yet to be released at a future date.

**Comment by tuspatil1** [comment]
Hi Teodor,

Thanks for your response.
Is it possible to comment on approx release date for same?

Thanks,
Tushar
