### ISSUE TITLE
About link pointing to non-existing page

### ISSUE THREAD

**Issue by danielpeintner** [TIBCOSoftware/jasperreports#422]
see  
![image](https://github.com/TIBCOSoftware/jasperreports/assets/11281461/954c87f3-d296-43b0-be27-b6443ca514ef)

points to https://community.jaspersoft.com/project/jasperreports-library which does no longer exist.

Maybe it is https://community.jaspersoft.com/downloads/community-edition/ ?

BTW, I noticed there is a major refactoring taking place but I do not see any easy way to download the JasperStudio on https://community.jaspersoft.com/downloads/community-edition/  ... there is no "download" link.

**Comment by teodord** [comment]
Thank you for letting us know about the link.

Jaspersoft Studio is available for download on the Download button on the right:
![image](https://github.com/TIBCOSoftware/jasperreports/assets/2511035/98252f31-52c1-4c14-913c-28d251ea5bdd)

**Comment by danielpeintner** [comment]
> Jaspersoft Studio is available for download on the Download button on the right:

I see, I forgot to sign in first ...
