### ISSUE TITLE
Very old version of antlr used

### ISSUE THREAD

**Issue by Roberto-Mol** [TIBCOSoftware/jasperreports#423]
Hi,

I ran into an issue where antlr/TokenStream could not be found while generating a report. That's when I noticed I had to include version 2.7.7 of antlr/antlr, which is from 2007.

Are there any plans to use org.antlr/antlr4-runtime? Or even org.antlr/antlr-runtime?

Thanks in advance!

**Comment by teodord** [comment]
For now, we stayed by the engineering principle mentioned at the beginning of this Antlr4 migration guide that says:
"If ain't broke, don't fix it."
https://tomassetti.me/migrating-from-antlr2-to-antlr4/

**Comment by Roberto-Mol** [comment]
That is indeed a good principle to follow. I also had no idea the migration would take weeks, so considering that there are no vulnerabilities in that library, I will close this issue.

Thanks for the quick reply!
