### ISSUE TITLE
PDF Export: Stretch - truncation instead of stretch

### ISSUE THREAD

**Issue by lenoch7** [TIBCOSoftware/jasperreports#429]
I have very weird problem with stretching.
I created very simple jrxml to demonstrate this problem (is attached), in reality DataSource is used of course.
I am using Linux and I tested it with version 6.20.5 and 6.21.2.

[stretch-truncation-reports.zip](https://github.com/TIBCOSoftware/jasperreports/files/14772275/stretch-truncation-reports.zip)

```
<?xml version="1.0" encoding="UTF-8"?>
<jasperReport
  xmlns="http://jasperreports.sourceforge.net/jasperreports"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"
  name="SimpleStretchTest"
  pageWidth="595"
  pageHeight="842"
  leftMargin="20"
  rightMargin="20"
  topMargin="30"
  bottomMargin="30"
  uuid="a09b55bb-d25f-4b19-a103-ef479d2e3c41"
>
  <detail>
    <band height="600">
      <!-- Wrong, truncation to ab-abcdefghijkl.mnopqrstuvwxyz012345 (3 lines) -->
      <textField textAdjust="StretchHeight">
        <reportElement x="0" y="0" width="100" height="16" uuid="4f38e741-082f-424e-a035-3b7568005a98"/>
        <textElement>
          <font size="12"/>
        </textElement>
        <textFieldExpression><![CDATA["ab-abcdefghijkl.mnopqrstuvwxyz0123456789"]]></textFieldExpression>
      </textField>
    </band>
  </detail>
</jasperReport>
```

The problem here is that text is truncated to `ab-abcdefghijkl.mnopqrstuvwxyz012345` (3 lines) (`6789` is missing). I attached pdf file too.

It seems like there is a problem with `-` (dash) or `.` (dot) characters, because:
* if I changed `-` to "usual" letter, than it works
* if I moved `.` character, than it works (sometimes? probably depends on dot character position)

IMHO, there is a some problem with height calculation in context of `BreakInterator`.

I hope, I am not completely wrong (I mean jrxml file), but if I tested similar/same jrxml file (`textAdjust` vs `isStretchWithOverflow`) with very old version 4.5.0 it works as is expected (or at least it seems like it).

**Comment by dadza** [comment]
Set the [net.sf.jasperreports.export.pdf.force.linebreak.policy](https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.pdf.force.linebreak.policy) property to true to make sure that the same line break policy is applied when measuring the texts and on PDF exporting.

Also, if you need to use a font extension with a embedded PDF font (for instance DejaVu Sans from [jasperreports-fonts](https://central.sonatype.com/artifact/net.sf.jasperreports/jasperreports-fonts/versions)) to ensure that the font metrics used for text measuring are consistent with the PDF export.

**Comment by lenoch7** [comment]
Thank you for quick answer. This configuration solves the problem.

I am sorry for stupid question and for creating this issue (now I see it in `JRPdfExporter` javadoc too). I knew  about difference between AWT measurement and PDF exporting, but I completely missed `ForceLineBreakPolicy`. I am sorry again.
