### ISSUE TITLE
When will jasperreports.jar(Community Edition) adapt to Jakarta EE specifications rather than Java EE?

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#431]
Hi Team,

As we are aware, Java EE has been transitioned to Jakarta EE; hence, we need to change all the class import statements from "javax.*" to "jakarta.*" from our code, but we observed that jasperreports-6.21.2.jar is still using the Java specification (i.e., "javax.*") instead of the Jakarta specification. As per our analysis, there are 23 classes which contains Java specific imports(i.e., "javax.*").

Can you please let us know if there is any plan for jasperreports.jar to adapt the Jakarta specification?

We have raised same issue on jasper community portal, but didn't recieved response, hence raised here on github by re-articulating exact concern.
https://community.jaspersoft.com/forums/topic/68423-is-jasperreports-6212-community-edition-library-comapatible-with-tomcat-10/

Thanks,
Tushar

**Comment by teodord** [comment]
This has been discussed here:
https://github.com/TIBCOSoftware/jasperreports/issues/321
https://github.com/TIBCOSoftware/jasperreports/issues/378
https://github.com/TIBCOSoftware/jasperreports/issues/430
