### ISSUE TITLE
Is Jasper-reports are supported on Graalvm native-image feature or any plans to support?

### ISSUE THREAD

**Issue by ctoabidmaqbool1** [TIBCOSoftware/jasperreports#432]
[GraalVM](https://www.graalvm.org/) is next generation emerging technology in the worlds of JVM.

And it have a feature called [native-image](https://www.graalvm.org/22.0/reference-manual/native-image/) which make code to System native executable App.

Now, [Gluon Maven Plugin](https://github.com/gluonhq/gluonfx-maven-plugin) or [Gluon Gradle Plugin](https://github.com/gluonhq/gluonfx-gradle-plugin) liverge Javafx and GraalVM to make native app using Javafx. 

Is there any plans to support GraalVM native-image feature or is there already support?

**Comment by teodord** [comment]
This has been asked before. We would welcome any help we can get with it as we lack the expertise in this area:
https://github.com/TIBCOSoftware/jasperreports/issues/366

**Comment by melloware** [comment]
I am working on this for Quarkus and JasperReports presents some unique challenges for GRaalVM: https://github.com/quarkiverse/quarkus-jasperreports/pull/99

That is my progress so far and what I have discovered.

**Comment by melloware** [comment]
I have it fully working in GraalVM with Quarkus now. 

https://github.com/quarkiverse/quarkus-jasperreports

**Comment by teodord** [comment]
Hi,

I am glad you were able to pull this off and wanted to congratulate you for the great work you've done.
If there is anything that needs to be improved in JasperReports to better support GraalVM, let us know by opening new trackers.
It is not clear to me if you had to modify anything in our code to make it work with GraalVM. But if you did, let us know what was that.

I'm closing this for now as fixed.

Thank you,
Teodor

**Comment by melloware** [comment]
The only two things I would recommend I submitted PR's for to make my life easier and reduce depedencies.  One is getting rid of Collections 3.2 and the other is a small OpenLibre fix
