### ISSUE TITLE
Is Jaspersoft Studio Opensource?

### ISSUE THREAD

**Issue by seenukarthi** [TIBCOSoftware/jasperreports#434]
According to the [README.md](https://github.com/TIBCOSoftware/jasperreports/blob/a74eb53a58718c209347574d23cb2f05ab9bc50b/README.md), Jaspersoft Studio is open-source software.

>Jaspersoft® Studio - report designer for the JasperReports Library
>
>The report templates for the JasperReports Library are XML files which can be edited using a powerful, open source, Eclipse-based report designer called [Jaspersoft Studio](https://community.jaspersoft.com/downloads/community-edition/). Using Jaspersoft Studio, reports can be built out of any data source and can have their look and feel formatted for printing or on-screen reading, or can be deployed to a JasperReports Server instance, JasperReports IO repository or to a custom application using the JasperReports Library implementation and exported to a wide range of output document formats.

If so, where is the source?

**Comment by teodord** [comment]
No, Jaspersoft Studio is no longer open source, but free to use. I have modified the readme file to reflect this.

Thank you,
Teodor

**Comment by seenukarthi** [comment]
That's unfortunate.

**Comment by teodord** [comment]
Were there any fixes or enhancements that you made onto Jaspersoft Studio? I'm asking in case you would like to contribute them back to the project.

Thank you,
Teodor

**Comment by seenukarthi** [comment]
I want to use Jaspersoft Studio as a plugin in Eclipse instead of a separate standalone application.

**Comment by teodord** [comment]
The availability of the Jaspersoft Studio in the form of an Eclipse plugin as opposed to standalone RCP application has nothing to do with the open source nature of the project. In theory, we could very well have a closed source plugin that is free to use.
But you are right in the sense that the plugin distribution is no longer available.

**Comment by seenukarthi** [comment]
@teodord Thanks. One more clarification: where should I raise the issues with Jaspersoft Studio?

**Comment by teodord** [comment]
You can raise it on the Jaspersoft Community website here:
https://community.jaspersoft.com/forums/

**Comment by krishnasdfw** [comment]
It will be nice if the CommunityLogin code in the Studio utilized useSystemProperties for taking in HTTP Proxy settings via the ini file vm command Arguments. Most people are experiencing connection timeout.
