### ISSUE TITLE
Docx Export:  Last Page Footer overflow to the next page

### ISSUE THREAD

**Issue by dev000il** [TIBCOSoftware/jasperreports#435]
hi there:
when i tryed to set the property 'net.sf.jasperreports.export.docx.flexible.row.hegiht' to the report，i found some static text of element Last Page Footer overflow to the next page, it is not corrected loaction on the foot of the last page.
i was new to the jasper , hope for some advice
Thanks

**Comment by teodord** [comment]
You need to attach some files here so that we can see the problem. The JRXML is important.

Thanks,
Teodor

**Comment by dev000il** [comment]
here is my report file
[ReturnOrderForMoney.zip](https://github.com/TIBCOSoftware/jasperreports/files/15301375/ReturnOrderForMoney.zip)

**Comment by teodord** [comment]
Are you sure that the font you are using (微软雅黑) exists both on the machine that generates the report and also on the machine where the DOCX file is viewed? If it indeed exists, is it really the same TTF as the one you have mentioned in your JRXML (MSYH.TTF)?
The recommended way to ensure the font exists on the machine that runs the report is to package it up as a JasperReports font extension (using Jaspersoft Studio). If you do that, you would not need the pdfFontName, pdfEncoding and isPdfEmbedded attributes in JRXML anymore as they are somewhat deprecated by the introduction of font extensions many years ago.
Also, to ensure the font exists on the machine that views the DOCX file, you can embed the font into the DOCX by setting this property:
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.docx.embed.fonts

I hope this helps.
Teodor
