### ISSUE TITLE
JaspersoftStudio v7 for testing

### ISSUE THREAD

**Issue by bjorndarri** [TIBCOSoftware/jasperreports#437]
I'd love to try out the new v7 of JasperReports.

I managed to get everything working using your snapshot repository, but I had no way of converting my old report designs to the new version, since I couldn't find a snapshot of JaspersoftStudio 7. I tried to convert some simple designs manually, but that turned out to be a lot of work.

So, is there any way for me (and others) to get access to v7 of JaspersoftStudio?

**Comment by teodord** [comment]
Thank you for your interest in our new release 7.
Jaspersoft Studio CE 7 should be available in a couple of weeks or so. Hopefully.

Thank you,
Teodor
