### ISSUE TITLE
The SQL field order is changing the value of the fields in the report

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [TIBCOSoftware/jasperreports#439]
I'm having a problem, when I change the order of the fields in the query, the data is different, when it shouldn't be.

Example:

```
select 
t2.desc as desc3,t3.desc
FROM table1
left JOIN table2 AS t2 on (table1.id_1=t2.id)   
left JOIN table2 AS t3 on (table1.id_2=t3.id)
WHERE table1.id=1
```
Mysql Workbench: 
![image](https://github.com/TIBCOSoftware/jasperreports/assets/3578953/8ed72e16-a766-4e65-8849-9c69bb1d8397)
Jasper:
![image](https://github.com/TIBCOSoftware/jasperreports/assets/3578953/b623e542-616c-4bd4-9159-449dbbcfb37f)

The result is different when the order of fields is changed:

```
select 
t3.desc,t2.desc as desc3
FROM table1
left JOIN table2 AS t2 on (table1.id_1=t2.id)   
left JOIN table2 AS t3 on (table1.id_2=t3.id)
WHERE table1.id=1
```
Mysql Workbench: 
![image](https://github.com/TIBCOSoftware/jasperreports/assets/3578953/8ed72e16-a766-4e65-8849-9c69bb1d8397)
Jasper
![image](https://github.com/TIBCOSoftware/jasperreports/assets/3578953/773b0687-832d-449b-aa29-0b5010cf5d63)

I have attached files below necessary to reproduce the problem. Change the order of the fields to understand the problem. Jasper presents a different result than what appears in MySQL Workbench, for example.
[Blank_A4.zip](https://github.com/user-attachments/files/15825478/Blank_A4.zip)

**Comment by teodord** [comment]
I'm afraid I don't understand what you mean. Maybe you can describe it in more detail and attach some screenshots or something as we don't have your database to make tests on our own.

Thank you,
Teodor

**Comment by erickdeoliveiraleal** [comment]
Well, I had already added a file with the creation of the tables in the database and necessary data and also the JRXML file used to reproduce the problem, but I edited it and added some more details that may be relevant.
