### ISSUE TITLE
Jasper reports 7 release date

### ISSUE THREAD

**Issue by SATISHEEEK** [TIBCOSoftware/jasperreports#440]
Dear Jasper team,
we've been using the JasperReports library in our application for a long time for almost 7 years. 

Unfortunately, for the last few weeks, we've been struggling due to the Jakarta upgrade.  Our whole application has been migrated and report modules are the only ones waiting. 

Would you be, please, be that nice and share with us an expected release date of JasperReports library v7?
We don't need anything specific, but a clarification if we can expect it in days / weeks / months would be nice.  

Could you, please, do that? 

Also, if you have any snapshots available, the link would be appreciated. 

Thank you in advance.
Kind regards,
Jan

**Comment by teodord** [comment]
Snapshots have been available for sometime now on our JFrog.io repository at:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/7.0.0-SNAPSHOT/

The final 7.0.0 artifacts have been published today:
https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports/7.0.0/

I hope this helps.
Teodor
