### ISSUE TITLE
Converting .jrxml for 7.0 compatibility

### ISSUE THREAD

**Issue by gtoison** [TIBCOSoftware/jasperreports#442]
Hello and congratulations on releasing 7.0!
The new version requires a conversion of jrxml templates, according to the changelog iReport can perform the conversion.
Is there some kind of utility class I can use to convert as well? We have quite a few templates so it does not seem practical to use iReport for that, even if the conversion is one-off

**Comment by kzander91** [comment]
In general I'd also appreciate more detailed instructions on how to convert the jrxml files.
The release notes claim that Jaspersoft Studio 7 can convert them, but the linked page offers 6.21.3 as the latest version (https://community.jaspersoft.com/download-jaspersoft/community-edition/).

I also tried the commercial edition and couldn't find any conversion tool in there...

**Comment by teodord** [comment]
Jaspersoft Studio 7 is now available:
https://community.jaspersoft.com/download-jaspersoft/community-edition/

Thank you,
Teodor
