### ISSUE TITLE
[WARNING] Found duplicate and different resources in [net.sf.jasperreports:jasperreports-pdf:7.0.0, net.sf.jasperreports:jasperreports:7.0.0]:

### ISSUE THREAD

**Issue by grg5811** [TIBCOSoftware/jasperreports#448]
Good morning,
I can't compile the server and shared modules in scout with eclipse 2024-06.
Previously I had version 6.21.3 and everything worked normally.

pom.xml shared:

		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>${jasperreports.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

pom.xml server:

		<dependency>
			<groupId>org.eclipse.scout.apps</groupId>
			<artifactId>lavorcarni.shared</artifactId>
		</dependency>

		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-pdf</artifactId>
			<version>${jasperreports.version}</version>
			<exclusions>
				<exclusion>
					<groupId>net.sf.jasperreports</groupId>
					<artifactId>jasperreports</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

jasperreports.version = '7.0.0'

During compilation I get error messages:

duplicate-finder:2.0.1:check

[WARNING] Found duplicate and different resources in [net.sf.jasperreports:jasperreports-pdf:7.0.0, net.sf.jasperreports:jasperreports:7.0.0]:
[WARNING]   properties-metadata.json
[WARNING] Found duplicate classes/resources in compile classpath.
[WARNING] Found duplicate and different resources in [net.sf.jasperreports:jasperreports-pdf:7.0.0, net.sf.jasperreports:jasperreports:7.0.0]:
[WARNING]   properties-metadata.json
[WARNING] Found duplicate classes/resources in runtime classpath.
[WARNING] Found duplicate and different resources in [net.sf.jasperreports:jasperreports-pdf:7.0.0, net.sf.jasperreports:jasperreports:7.0.0]:
[WARNING]   properties-metadata.json
[WARNING] Found duplicate classes/resources in test classpath.

[ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:2.0.1:check (default) on project ....server Found duplicate classes/resources -> [Help 1]

How can it be solved?

Thank you in advance

**Comment by teodord** [comment]
I suspect the "duplicate-finder-maven-plugin" that you are using has a way in which you can configure which classpath duplicated resources to be ignored.
In version 7, the various JAR files that make up the JasperReports library have a file called properties-metadata.json in their root package. This is not an issue and you just need to configure your plugin to ignore this.

I hope this helps.
Teodor

**Comment by grg5811** [comment]
Thank you very much, I added in main pom.xml

        <plugin>
          <groupId>org.basepom.maven</groupId>
          <artifactId>duplicate-finder-maven-plugin</artifactId>
            <configuration>
            <ignoredResourcePatterns>
              <ignoredResourcePattern>.*ico$</ignoredResourcePattern>
              <ignoredResourcePattern>.*jpg$</ignoredResourcePattern>
              <ignoredResourcePattern>.*jpeg$</ignoredResourcePattern>
              <ignoredResourcePattern>.*png$</ignoredResourcePattern>
              <ignoredResourcePattern>.*gif$</ignoredResourcePattern>
              <ignoredResourcePattern>.*html$</ignoredResourcePattern>
              <ignoredResourcePattern>.*htm$</ignoredResourcePattern>
              <ignoredResourcePattern>.*xml$</ignoredResourcePattern>
              <ignoredResourcePattern>.*txt$</ignoredResourcePattern>
              <ignoredResourcePattern>.*.api_description$</ignoredResourcePattern>
              <ignoredResourcePattern>.*options$</ignoredResourcePattern>
              <ignoredResourcePattern>.*properties$</ignoredResourcePattern>
              <ignoredResourcePattern>.*gitkeep$</ignoredResourcePattern>
              <ignoredResourcePattern>.*sql$</ignoredResourcePattern>
              <ignoredResourcePattern>.*xjb$</ignoredResourcePattern>
              <ignoredResourcePattern>.*exsd$</ignoredResourcePattern>
              <ignoredResourcePattern>.*about.ini$</ignoredResourcePattern>
              <ignoredResourcePattern>.*file-list$</ignoredResourcePattern>

              <ignoredResourcePattern>.*properties-metadata.json</ignoredResourcePattern>

            </ignoredResourcePatterns>
            </configuration>
        </plugin>

 and now the compilation works.
