### ISSUE TITLE
7.0.0 missing classes 

### ISSUE THREAD

**Issue by SATISHEEEK** [TIBCOSoftware/jasperreports#459]
Hi Guys, 
I am facing an issue with missing classes while migrating our application to jasper 7. 

Issue is kinda similiar like https://github.com/TIBCOSoftware/jasperreports/issues/458

except that my missing class is _net.sf.jasperreports.engine.query.JsonQueryExecuterFactory_

I assume that its been also moved to another module and I am missing a dependency. But could you, please, give me a hint which one? 

Also, if you have any documentation or "process" how to find missing dependencies in the future, it would be hugely appreciated. 

Thank you.

Kind regards,
Jan

**Comment by SATISHEEEK** [comment]
EDIT:
found new location import net.sf.jasperreports.json.query.JsonQueryExecuterFactory; 
and 		
```
<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-json</artifactId>
			<version>7.0.0</version>
		</dependency>
```

but still. Do you have any documentation where could I read what was moved where? Or whats the recommended process if I struggle to find one of originally used classes?

Thank you in advance for any kind of response!

**Comment by SATISHEEEK** [comment]
@teodord Thank you for your response!

I found a "way" how to quickly find a location if needed, but if I put class name into search bar and click on the result, I've got access denied error.

![image](https://github.com/user-attachments/assets/27d8e0ed-771f-4ca7-a560-ad5e55b44a8a)

do you think you could make it work? It would be easier to just copy the path afterwards..

Thank you!
Jan

**Comment by teodord** [comment]
I am not familiar with this javadoc.io website and I'm not sure what we need to do to make it work for you.

Thank you,
Teodor
