### ISSUE TITLE
Jasperreports is not working with Apache POI 4.0.0 - HSSFColor#WHITE and other colors are removed.

### ISSUE THREAD

**Issue by lurajon** [TIBCOSoftware/jasperreports#46]

**Comment by lurajon** [comment]
We need to upgrade to Apache POI v.4.0.0, but this causes JasperReports to fail when exporting Excel spreadsheets.

**Comment by teodord** [comment]
We upgraded to POI 4.0.1 in the master branch and this will be part of the next release.

**Comment by zeronius** [comment]
Awesome, thanks.
