### ISSUE TITLE
Values Overlap When Column Count Set Higher Than 1

### ISSUE THREAD

**Issue by jayeshsony** [TIBCOSoftware/jasperreports#464]
When I set the column count to more than 1 in my JasperReports report to display values side by side, I'm encountering an issue where the values from adjacent columns overlap. This overlap makes the report difficult to read and understand.

**Comment by teodord** [comment]
You have to attach the JRXML here.

**Comment by jayeshsony** [comment]
It's not supporting the jrxml format, So can you suggest me how can I upload the file?

**Comment by teodord** [comment]
You can rename your file as *.txt and attach it.

**Comment by jayeshsony** [comment]
[custom-menu-report.txt](https://github.com/user-attachments/files/16377809/custom-menu-report.txt)

**Comment by teodord** [comment]
You need to check our /demo/samples/jasper and /demo/samples/horizontal sample reports to better understand what multi-column reports mean.
They are documented here:
https://jasperreports.sourceforge.net/sample.reference/horizontal/README.html#horizontal

In your detail section you have a single text element having width 511 pixels. And you want to render it on two columns of 277 pixels width. Well, of course it does not look right, with the second column overlapping the first. Not sure what you want to achieve, but if you make the text field width 277, it might be what you expect.

Thank you,
Teodor
