### ISSUE TITLE
JasperReportsLibrary 7 need to throw a better error for NON converted files

### ISSUE THREAD

**Issue by meshpaul** [TIBCOSoftware/jasperreports#469]
Hi,

 So I have used JasperReports Studio CE 7 to convert files.  It say it does but it d. Well it converted one report file correctly.  And there was another report file that report claims it converted but it didn't  [see](https://github.com/TIBCOSoftware/jasperreports/issues/468#issuecomment-2273849846).  I am not sure how to report that error please advise?

But when I try to use JRL 7 after I ensure the files is saved the library fails (technically JSS CE 7 failed to save changes to actual file).

I am getting the following Error.   That should be more specific to new JRL 7 format

```ERROR
Unable to load report
net.sf.jasperreports.engine.JRException: Unable to load report
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:172)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:149)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:120)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:107)
```

**Comment by teodord** [comment]
You are probably facing this JSS CE 7 bug detailed here:
https://github.com/TIBCOSoftware/jasperreports/issues/453

I hope this helps.
Teodor

**Comment by meshpaul** [comment]
Thanks @teodord for proposed work-around.  But the underlining issue remains.  I'll be happy to put a PR for this as developers will waste time figuring out what happened.

**Comment by teodord** [comment]
The mentioned JSS CE 7 bug has already been fixed and will be available with the next release soon.

Thank you,
Teodor
