### ISSUE TITLE
Adjust data on single page if there are very few records on new page

### ISSUE THREAD

**Issue by jayeshsony** [TIBCOSoftware/jasperreports#471]
I am currently facing a challenge in JasperReports where I aim to display all items of a category on a single page without empty space. I'm displaying each new category in new page so if the're more items then it will print some items on new page, so if there's 1-2 items in new page so the other space is stay remained.

Is there a way to ensure that all items of a category are accommodated on one page, and only if there are more than 2-3 items, a new page is initiated? I am seeking insights and techniques to dynamically adjust the layout in JasperReports based on the number of items to display, ensuring an efficient use of space.

**Comment by teodord** [comment]
If you have 12 items and only 10 can fit on a page, what would you want to do? Make them smaller so that all 12 fit?

Thanks,
Teodor

**Comment by teodord** [comment]
Asuming this is what you want, I can only tell you it is not possible. You can ask questions on the public forums at:
https://community.jaspersoft.com/forums/

Thanks,
Teodor
