### ISSUE TITLE
Best way to responsibly disclose a vulnerability

### ISSUE THREAD

**Issue by JamieSlome** [TIBCOSoftware/jasperreports#472]
What is the best way to disclose a vulnerability or security issue for this repository? Is there an e-mail address or process?

Should we create a `SECURITY.md` to make this clear in the future for future security researchers?

**Comment by dadza** [comment]
Please write an email to [js-product-team@cloud.com](mailto:js-product-team@cloud.com) describing the issue.

We will consider writing a SECURITY.md for future reports.

Thank you for reporting your research findings.

**Comment by JamieSlome** [comment]
Thank you for sharing 🙌
