### ISSUE TITLE
JasperReport 7 Fonts not available to the JVM

### ISSUE THREAD

**Issue by ro199** [TIBCOSoftware/jasperreports#473]
I have a report created and compiled in jasperstudio 7, at the moment of rendering it from my spring boot application, it gives me the following error
`[nio-8090-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [net.sf.jasperreports.engine.util.JRFontNotFoundException: Font “Arial<EOL><EOL>” is not available to the JVM. See the Javadoc for more details].`
I have implemented the solution that says in this documentation [fonts](https://jasperreports.sourceforge.net/sample.reference/fonts/README.html#fonts), I created a project and added the fonts, and others, that jar was added, and still presents the same message.
The JVM is checked, to see the available fonts. 
```
GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fontNames = ge.getAvailableFontFamilyNames();
        for (String fontName : fontNames) {
            System.out.println(fontName);
        }
```
And Arial font peeks out, so why jasper doesn't detect it.
With version 6.20.0 reports that are compiled in jasper studio 7 and have the Arial font, it works perfectly, but with reports created and compiled in jasper studio 7, is there any solution or any idea to solve this problem.

Translated with DeepL.com (free version)

**Comment by ro199** [comment]
Also at the docker level I created the image, I created my project, I installed the fonts that it needs.
`
# Utiliza una imagen base de Debian
FROM debian:bullseye-slim

# Instalar OpenJDK 17 y herramientas necesarias
RUN apt-get update && \
    apt-get install -y \
    openjdk-17-jdk \
    fontconfig \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN echo "deb http://deb.debian.org/debian/ bullseye main contrib" > /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y \
        ttf-mscorefonts-installer \
        cabextract \
        fonts-liberation \
        libmspack0 \
        xfonts-encodings \
        xfonts-utils && \
    rm -rf /var/lib/apt/lists/*

# Reconfigure the installer if necessary
RUN dpkg-reconfigure ttf-mscorefonts-installer

# Definir una variable de entorno para la ubicación de archivos
ENV REPORTEAPPHOME=/app/plantillas

# Copiar archivos adicionales necesarios para la aplicación
COPY ./plantillas/ /app/plantillas/

# Copiar el archivo JAR de la aplicación al contenedor
COPY ./reportes-api/target/reportes-api-6.0.0.jar /app/reportes-api.jar

# Configurar la variable de entorno para opciones adicionales de JVM
ENV JAVA_OPTS="-Djava.awt.headless=true -Dsun.java2d.fontpath=/usr/share/fonts/truetype/msttcorefonts -Dnet.sf.jasperreports.awt.ignore.missing.font=true"
# Set the entry point to use JAVA_OPTS
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app/reportes-api.jar"]
`
But I keep getting the same message of 
`Resolved [net.sf.jasperreports.engine.util.JRFontNotFoundException: Font “Arial<EOL><EOL>” is not available to the JVM. See the Javadoc for more details].`

**Comment by teodord** [comment]
Please attach here the JRXML report you are running and also the font extension that you use to package your desired font.

Thanks, 
Teodor

**Comment by ro199** [comment]
Hello, sorry for the delay after struggling a little I found the problem, which was caused by the program Jasper Studio Comunity, I generated a style called fontName=“Arial&#xd;&#xa;”, at the time of changing the styles by one of the library jasperreports-fonts, and compile and test and review how to integrate the fontName, I changed that style to “Arial” and it worked.

![image](https://github.com/user-attachments/assets/61b636bf-d9c9-48f0-86de-2a8d7e6241ff)
