### ISSUE TITLE
Can't Export PDF, XLS in JRViewer

### ISSUE THREAD

**Issue by wai-yan-hein** [TIBCOSoftware/jasperreports#474]
![Screenshot (133)](https://github.com/user-attachments/assets/de0d13e7-0fed-45d1-a291-508687b40325)
screenshoot version is jasper 6.21.3
can't see and  export pdf and xls in version 7 ?

**Comment by wai-yan-hein** [comment]
thank you dadza, and i want to try recompile 6.21.3 version example.jaser , open in Jasper Studio 7 , can't open example.jaser, normally in 6.21.3 decompile jrxml file when open jasper file

**Comment by dadza** [comment]
Jaspersoft Studio 7 does not support opening *.jasper files compiled by Studio/JasperReports 6.x (or older).

You'll have to open the 6.x *.jasper file with Studio 6.x, save it as a *.jrxml and then open the *.jrxml file in Studio 7.
