### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by pioro90** [TIBCOSoftware/jasperreports#475]
Hi,
Is there any project releases roadmap ? When new version with bugs fixes will bee released ?

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by teodord** [comment]
We do not have a public roadmap. Never had. We implement new features, improvements and make fixes on a regular basis depending on various criteria. Jaspersoft, the company behind this project does have a roadmap that it shares with its customers.

Thank you,
Teodor
