### ISSUE TITLE
Export to PDFs takes significant longer time comparing to xlsxs.

### ISSUE THREAD

**Issue by haaddii** [TIBCOSoftware/jasperreports#478]
I now have a pretty large report to export and it have about 60,000 lines of query data.
And when I export it to excel, it only takes around 27s. When I export it to pdf, it takes about 110s. (using pyreportjasper, which use jpype to utilize the APIs.)

And it uses `net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfStream` to convert a JasperPrint object to pdf stream. And use `net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter` to export xls files.

What leads to this difference and is there anyway to resolve / compensate the slow export of PDFs?

**Comment by teodord** [comment]
I don't know how to answer your question, but I have another question for you:
What is the difference between the Excel/XLSX file format and the PDF file format?
Do you think they are similar enough so that the time it takes to generate each of them is similar?

Thank you,
Teodor

**Comment by haaddii** [comment]
Sorry for the silly question. I would try if there's any other ways to compensate the speed gap.
