### ISSUE TITLE
How we can change the default file creation path

### ISSUE THREAD

**Issue by shinurag** [TIBCOSoftware/jasperreports#479]
Could you please let me know how to change the temporary file creation location to a different folder path for the following line of execution?

jPrintFile = JasperFillManager.fillReport(jReport, params, jrbcds);
// jReport : JasperReport
// params: HashMap<String, Object> params = new HashMap<>();
// jrbcds: JRBeanCollectionDataSource

**Comment by teodord** [comment]
Which temporary files are we talking about and why would their location be important to worth changing?

Thank you, 
Teodor

**Comment by shinurag** [comment]
I developed a JAR file for generating PDF files, but the process terminates at `jPrintFile = JasperFillManager.fillReport(jReport, params, jrbcds);` While this JAR file functions correctly in the lower environment, it only works intermittently in production, where it often fails. To address this, we plan to change the file creation folder to determine if it resolves the issue.

**Comment by dadza** [comment]
What JasperReports version are you using?

**Comment by shinurag** [comment]
@dadza JasperReport version is using 4.7.1

**Comment by dadza** [comment]
You can change the Java temporary files folder by passing an argument like -Djava.io.tmpdir=/path/to/temp/folder when starting the Java process.  Note that this will apply to other temporary files created by the Java process.
