### ISSUE TITLE
Not able to get hindi font correctly

### ISSUE THREAD

**Issue by yogeshpaliyal** [TIBCOSoftware/jasperreports#48]
Not able to load correct hindi font on pdf when sending from java, it is working in preview section of jasper soft studio & i am using font extension for custom font
Example :
sending parameter दिनेश
in preview it shows correct but when loading from java it shows
[like this](https://community.jaspersoft.com/sites/default/files/user_uploads/djohnson53/untitled.png)

**Comment by dadza** [comment]
Did you export the font extension as a jar and added it to your application's classpath?
