### ISSUE TITLE
Jasper Studio v7.0.0 unable to configure charts

### ISSUE THREAD

**Issue by sibusiso41** [TIBCOSoftware/jasperreports#482]
Good day,

I am unable to configure any charts on japser studio 7.0.0

If I add chart on the designer, the i can't get passed the window below, whether i double click a chart or select it and click next button nothing happens.

I tried on both Mac and Windows

![image](https://github.com/user-attachments/assets/4896cd28-c42e-46f4-a997-6ff1da8cf0ed)

**Comment by maxrabbi** [comment]
The bug will be fixed in the next upcoming release. 
Thanks for reporting the issue.

Regards,
Massimo.

**Comment by sibusiso41** [comment]
Do you have the dates for the next release for me?

**Comment by teodord** [comment]
JSS CE 7.0.1 available here:
https://community.jaspersoft.com/download-jaspersoft/community-edition/jaspersoft-studio_7.0.1
