### ISSUE TITLE
Attribute 'uuid' is not allowed to appear in element 'jasperReport'

### ISSUE THREAD

**Issue by sanjayan-kv** [TIBCOSoftware/jasperreports#484]
I'm using Jasper Studio 7.0 and Jasper Server 8.2 on Ubuntu machine (Community Edition).
While I tried publish a report created on Jasper Studio to Jasper Server I'm getting an error
"JRXML.content" is invalid  
![Screenshot from 2024-10-05 00-34-25](https://github.com/user-attachments/assets/cd302bcc-bfe8-4f34-9adc-9eb8204ae5d1)

While checking further Jasper Server log says 
Attribute 'uuid' is not allowed to appear in element 'jasperReport'
[error_log.txt](https://github.com/user-attachments/files/17263064/error_log.txt)

Please let me know how to solve this issue?

**Comment by dadza** [comment]
Please attach the report JRXML here.

**Comment by sanjayan-kv** [comment]
@dadza 
Please find below
[employee_list.zip](https://github.com/user-attachments/files/17266948/employee_list.zip)

**Comment by dadza** [comment]
For JasperServer 8.2.0 you need to set JasperReports 6.20.2 as Source .jrxml Version under compatibility level under Settings/Jaspersoft Studio/Compatibility.

**Comment by sanjayan-kv** [comment]
@dadza 

I've updated the settings 
![Screenshot from 2024-10-06 17-35-48](https://github.com/user-attachments/assets/1d272be1-8751-42c2-b250-9361e1893fd0)

Modified the file 
.jrxml file got updated using JasperReports Library version 6.20.2
[employee_list_1.zip](https://github.com/user-attachments/files/17269289/employee_list_1.zip)
Issue still persists
