### ISSUE TITLE
Missing release information about v7.0.1

### ISSUE THREAD

**Issue by pp7En** [TIBCOSoftware/jasperreports#485]
I noticed that version v7.0.1 of the project is available in the Maven Repository ([link](https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports/7.0.1)), but there is no mention of this release on the project website or in the GitHub repository. There is no changelog or release notes for this version either.

Given the growing concern about supply chain attacks, it would be helpful to confirm whether version v7.0.1 is an official release. Additionally, could you please provide release notes or changelog for this version?

Thank you for your help!

**Comment by teodord** [comment]
Done:
https://github.com/TIBCOSoftware/jasperreports/releases/tag/7.0.1

Thanks,
Teodor
