### ISSUE TITLE
Does a JasperReport template support mixed Landscape and Portrait orientations?

### ISSUE THREAD

**Issue by tianyusumizhou** [TIBCOSoftware/jasperreports#489]
I have a requirement to insert a portrait A4 page into a landscape A4 template for printing. I tried inserting a portrait A4 as a subreport, but it prompted me that the height exceeded the limit. Is there a solution for this kind of requirement?

**Comment by ahmedqasid** [comment]
I had a similar problem, and the solution was to use report books
normally, sub-reports should be the same size or smaller than the main report they are inside, books allow different page sizes in subreports
Check the documentation here: 
https://community.jaspersoft.com/knowledgebase/faq/report-books-jaspersoft-studio/
Please note I am a community member as you, I am not a part of jasperreports team.

**Comment by teodord** [comment]
Thank you for your answer, Ahmen. Report books are indeed the way to go.

Thanks,
Teodor

**Comment by teodord** [comment]
If you have questions like this about our library features, please use the discussion forums at:
https://community.jaspersoft.com/forums/
instead of logging them as bugs here.

Thank you,
Teodor
