### ISSUE TITLE
Poor performance for large reports

### ISSUE THREAD

**Issue by TomaszBelina** [TIBCOSoftware/jasperreports#49]
Hi,

Are there any plans to implement cache mentioned in this line:
https://github.com/TIBCOSoftware/jasperreports/blob/77e2179637460f657a806c7a0ef2d0548a230f9a/jasperreports/src/net/sf/jasperreports/engine/fill/SimpleTextLineWrapper.java#L567

I actually hit the wall here and cache here would improve performance a lot for large size reports.

**Comment by teodord** [comment]
Hi,

We would need more details about your reports and the conditions you are running them on. There might be other ways to improve performance before making changes to the code, which we are not sure would actually help in your case.

For example, if you have large reports, do you use a virtualizer? How much memory do you allocate to the JVM? Can we have a report template to test on our side?

Thanks,
Teodor

**Comment by teodord** [comment]
Closing due to lack of feedback.
