### ISSUE TITLE
Speed regression in JRAntCompileTask when migrating from java 8 to java 17.

### ISSUE THREAD

**Issue by pohart** [TIBCOSoftware/jasperreports#491]
I'm compiling 143 reports using JRAntCompileTask with Jasperreport 6.17. Under Java 8 it takes 40-45 seconds. Under Java 17 it take 110-155 seconds.

**Comment by teodord** [comment]
What is your operating system? Do you have the ECJ (Eclipse Compiler for Java) JAR in your classpath?

Thank you,
Teodor
