### ISSUE TITLE
Formatting issue with a new MS Word version 2409

### ISSUE THREAD

**Issue by lucgrass** [TIBCOSoftware/jasperreports#494]
I want to export a Jasper report with a simple table to Microsoft Word. I encountered a formatting issue with the table starting from MS Word version 2409, while in earlier versions, the layout appears correct. I tried different Jasper versions (6.20.1, 6.23.1, and 7.0.1), but the issue persists.

Here are the details:
 
In Jaspersoft Studio, the table displays correctly in the preview.
When I export the table to Word (.docx) and open it in a Word version prior to 2409, the layout matches the preview in Jaspersoft Studio.

![preview](https://github.com/user-attachments/assets/26e7b3d2-a926-40e5-a267-10db616d9053)
 
However, in Word version 2409, the result changes significantly: the column widths are altered, making the report less readable.

![word_2409](https://github.com/user-attachments/assets/6a0161d3-ff8d-4e20-a562-fea054cac4c5)
  
I would like to know if this is a known issue and if there are any solutions to resolve it. 

Thanks in advance.

**Comment by teodord** [comment]
Hi,

My understanding is that this issue appears only with this very specific MS Word version, 2409.
If that's the case, then wouldn't it be fair to suspect this is a MS Word bug?

Thanks,
Teodor

**Comment by teodord** [comment]
This sounds similar:
https://techcommunity.microsoft.com/discussions/word/newest-office365-word-update-damages-tables/4279141

**Comment by lucgrass** [comment]
I’m currently using an older version of JasperReports (6.x) and have encountered issues where some classes are not found due to changes or deprecations in the newer versions. 

I’m reaching out to ask:

1) Is there an official release planned to address the patch in object ?
2) If so, will this modification be released as part of the 6.x version series, or will it only be available in newer versions?

Refactoring my code to align with the latest API changes would require significant effort, so I’d like to understand whether support or backporting to version 6 is being considered.

Thank you for your time and assistance.
Luca

**Comment by teodord** [comment]
Hard to tell. This is not a bug with our product. There is definitely something wrong in the MS Word version starting with version 2409.
If you are a Microsoft Word customer, I encourage you to report it to them.
This column size issue is not the only one. You'll probably notice that words no longer break at character when the cell width is too small for a word to fit, and we do not have a workaround for that. At least not yet.

Thank you,
Teodor

**Comment by lucgrass** [comment]
Hi @teodord 
 
Thank you for your response. However, I just want to clarify that my question was not regarding the issue on the Microsoft Word side, but rather about the official release and patch for the problem I encountered exporting from JasperReports.
 
I was specifically asking whether your patch will be officially released for this issue and, if so, whether it will be available only in version 7, or if there are any plans to include it in the 6.x series as well.
 
Thank you again for your time and assistance. I look forward to your clarification.
 
Best regards,
Luca

**Comment by teodord** [comment]
What I wanted to say is that we usually do not make "old" releases. 6.21.4 was an exception and unless other critical issue surface, there will be no more 6.21.x releases in the future.
This MS Word is not really critical, especially since it is not us who introduced it in the first place.

Thank you,
Teodor
