### ISSUE TITLE
Spring rest controller @ExceptionHandler return xml content instead of json, only on errors

### ISSUE THREAD

**Issue by ortixxx** [TIBCOSoftware/jasperreports#495]
So I have a @RestController 's and @ControllerAdvice over the Exceptions. I have custom Exceptions with custom HttpStatus. When upgrade to jasper 6.21.x, notice that a client's response results in a different object (xml in this case).

BEFORE upgrade
![image](https://github.com/user-attachments/assets/f4be3904-9307-470d-9aff-9f48c4f1cbe8)

AFTER upgrade
![image](https://github.com/user-attachments/assets/298f3e18-15f2-4f87-ae47-5449b9b51187)

I look for a  fix or solution, ty

**Comment by teodord** [comment]
Hi,

I do not understand how this has anything to do with JasperReports.

Thank you,
Teodor
