### ISSUE TITLE
Jasper 7.0.1 - Text fields not expanding in "Detail" band but work in "Group" band

### ISSUE THREAD

**Issue by pvncoder** [TIBCOSoftware/jasperreports#496]
I am experiencing an issue with a subreport in JasperReports that is configured to display data in two columns. The subreport contains three text fields, and I need the text fields to expand if the content is too large. I have set the "Text Adjust" property to **StretchHeight** and the "Stretch Type" to **ContainerHeight** to allow for the expansion of the fields.

However, the issue occurs in the **Detail** band: the fields do not expand as expected, even though the properties are correctly set. When I move the fields to a **Group** band, they expand correctly. The problem with using the **Group** band is that the report no longer respects the 2-column layout, and everything is printed in a single column.

Please take a look at the item highlighted in red in the screenshots below.

With detail ([detail_jrxml.zip](https://github.com/user-attachments/files/17725859/detail.zip)):
![image](https://github.com/user-attachments/assets/72ff5aea-d681-497e-9a7b-b027621a8d09)

With group ([group_jrxml.zip](https://github.com/user-attachments/files/17725901/group_jrxml.zip)):
![image](https://github.com/user-attachments/assets/94fd54a1-6a6d-4bda-8daf-a7f66e8d9d4d)

I would appreciate any help or suggestions.

**Comment by teodord** [comment]
Hi,

You have printOrder="Horizontal" . It is meant to work this way. Detail band does not stretch in horizontal print order multi column templates. This type of print order is more suitable for label printing, with each label having the same size on each row.

I hope this helps.
Teodor

**Comment by teodord** [comment]
If you still think you need the detail records to flow horizontally on two rows, you would need to use a list component with printOrder=Horizontal.

I hope this helps.
Teodor

**Comment by pvncoder** [comment]
Hi Teodor.

Thank you for the quick response.

I am indeed trying to use a List component with `printOrder=Horizontal`, but I haven’t been able to get it to work as expected. Even when I set the List to be half the width of the `group (band)`, it only prints vertically. If I set Ignore `width=true`, I do see the elements print side by side, but they seem to extend infinitely rather than wrapping into just two columns.

I'm following the example in the [documentation](https://jasperreports.sourceforge.net/sample.reference/list/README.html), but I'm not sure what I might be doing wrong. Do you have any ideas?

Here's my jrxml ([list_component_jrxml.zip](https://github.com/user-attachments/files/17736574/list_component_jrxml.zip)).
