### ISSUE TITLE
Unchecked or Unsafe Operations Log when Compiling Generated Report Java File On-The-Fly

### ISSUE THREAD

**Issue by raphaelNguyen** [TIBCOSoftware/jasperreports#497]
# Summary
## Versions Used
* jdk: `17.0.12`
* jasperreports: `7.0.1` (issue was not encountered previously on `6.21.3`)
  * Using `core` and `pdf` packages
## Issue
The log message below is shown at runtime when producing the report.
```
Nov 20, 2024 4:42:43 PM net.sf.jasperreports.engine.design.JRJdk13Compiler compileClasses
INFO: Note: [path-to-report-file.java] uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
# Details
I'm in the middle of transitioning from `jasperreports:6.21.3` to `7.0.1`. After regenerating the report and template xmls, I noticed the log message above whenever the application produce a report.

Prodding at this a bit further, I can see that the application has chosen the `JRJdk13Compiler` to do on-the-fly compilation of the generated report java classes.

After intercepting one of these generated java files, I noticed that it contains the following raw usages of `Map`, which would explain the unchecked/unsafe complaint from the compiler.

Do you think these could be parameterised or annotated with `@SuppressWarnings("unchecked")` to avoid these log messages?

Thank you for your time.

```java
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_DATA = (JRFillParameter)pm.get("REPORT_DATA");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
    }
```

**Comment by teodord** [comment]
Hi,

Add the jasperreports-jdt-x.x.x.jar extension to you classpath along with its required dependency, the ECJ compiler jar.

I hope this helps.
Teodor

**Comment by raphaelNguyen** [comment]
Thanks @teodord for the quick response. I did not realised this is one of the packages being split off.
