### ISSUE TITLE
Toc Scriplet Functionality is not accessible inside jasper table

### ISSUE THREAD

**Issue by LokeshJonwal** [TIBCOSoftware/jasperreports#498]
We are currently using 6.21.4 version of jasper studio and when we try to access the TOCScriplet inside table it show parameter not found. Is there any way we can use the scriplet functionality inside table.

**Comment by teodord** [comment]
It is impossible to help you if you don't provide any files.

Thank you,
Teodor

P.S. It is preferable to post such questions on the public forums at: https://community.jaspersoft.com/forums/
if the issue is not yet confirmed as a bug.
