### ISSUE TITLE
jasperreports-pdf-7.0.0.jar!/jasperreports_extension.properties net.sf.jasperreports.engine.JRRuntimeException: Class net.sf.jasperreports.pdf.PdfExtensionsRegistryFactory does not implement/extend net.sf.jasperreports.extensions.ExtensionsRegistryFactory.

### ISSUE THREAD

**Issue by dVenkatNaveen** [TIBCOSoftware/jasperreports#499]
I am getting the below error while export PDF. Using jasperreport in module 6.7.0 which gets bundle inside the car file.
PDF export successfully but throws this error on log.

but its pointing my sever/lib which has jasperreport 7.0.0

jasperreports-pdf-7.0.0.jar!/jasperreports_extension.properties
net.sf.jasperreports.engine.JRRuntimeException: Class net.sf.jasperreports.pdf.PdfExtensionsRegistryFactory does not implement/extend net.sf.jasperreports.extensions.ExtensionsRegistryFactory.

**Comment by dVenkatNaveen** [comment]
lib/jasperreports-pdf-7.0.0.jar!/jasperreports_extension.properties
net.sf.jasperreports.engine.JRRuntimeException: Class net.sf.jasperreports.pdf.PdfExtensionsRegistryFactory does not implement/extend net.sf.jasperreports.extensions.ExtensionsRegistryFactory.
        at net.sf.jasperreports.engine.util.ClassUtils.instantiateClass(ClassUtils.java:65)
        
 lib/jasperreports-charts-7.0.0.jar!/jasperreports_extension.properties
net.sf.jasperreports.engine.JRRuntimeException: Class net.sf.jasperreports.charts.ChartsExtensionsRegistryFactory does not implement/extend net.sf.jasperreports.extensions.ExtensionsRegistryFactory.
        at net.sf.jasperreports.engine.util.ClassUtils.instantiateClass(ClassUtils.java:65)
        
 lib/jasperreports-charts-7.0.0.jar!/jasperreports_extension.properties
net.sf.jasperreports.engine.JRRuntimeException: Class net.sf.jasperreports.jackson.util.JacksonMappingExtensionsRegistryFactory does not implement/extend net.sf.jasperreports.extensions.ExtensionsRegistryFactory.
        at net.sf.jasperreports.engine.util.ClassUtils.instantiateClass(ClassUtils.java:65)
        
        its throwing for all the jars that is there in my server/lib

**Comment by dVenkatNaveen** [comment]
@teodord Thanks for the response.
In our module pom i am using jasper 6.7.0 beacause it as dependency on dynamicreports for exporting pdf and excel related task. In other project/module  i am using jasper 7.0.0 for other related task.

How do i mitigate this error because that in the project we use older jasper for pdf etc and newer jasper doesnt come into picture here still throws for new version of jasper.

**Comment by dVenkatNaveen** [comment]
and also any plans for newer dynamicreports release compatiable with new jasperreport 7.0.0?

**Comment by teodord** [comment]
DynamicReports is a third party project we are not involved with. You might want to check with them.

This mixture of versions is for sure the cause of your error. This is not a bug for us.
Maybe posting on the community forums would help:
https://community.jaspersoft.com/forums/

Thank you,
Teodor
