### ISSUE TITLE
upgrade itext dependency

### ISSUE THREAD

**Issue by dangerusslee** [TIBCOSoftware/jasperreports#5]
jasperreports is currently depending on itext 2.1.7.js5, which is pretty old and is depending on other old things such as bctsp-jdk14, among others, which have security vulnerabilities. 

Would it be possible to upgrade jasperreports to use a more recent version of itext, lets say 5.5.11?

<dependency>
    <groupId>com.itextpdf</groupId>
    <artifactId>itextpdf</artifactId>
    <version>5.5.11</version>
</dependency>

**Comment by teodord** [comment]
Hi,

You are probably aware that since version 5, iText has changed its license to AGPL, which prevents its use in commercial products. You would need to purchase a commercial license of iText.
As far as JR Library is concerned, we cannot depend on an AGPL dependency without having to become AGPL ourselves, and this is why we cannot upgrade past 2.1.7.

You can implement your own PDF exporter using iText 5+.

Thank you,
Teodor

**Comment by dangerusslee** [comment]
What about using version 4.2.2?


<dependency>
    <groupId>com.lowagie</groupId>
    <artifactId>itext</artifactId>
    <version>4.2.2</version>
</dependency>

**Comment by JohneDoe** [comment]
@teodord 
Interested in an PdfBox Implementation of the PDF-Exporter?

**Comment by danielpeintner** [comment]
FYI: I recently got to know about the [OpenPDF](https://github.com/LibrePDF/OpenPDF) efforts which might be of interest. It is a fork of iText...

**Comment by teodord** [comment]
For the core JRL distro, we use our own iText 2.1.7 fork in which we have implemented a custom way to deal with fonts that have ligatures. This is now a feature that is tightly related to JRL and does not necessarily make sense in other products that generate PDF (although we've seen it being adopted in the OpenPDF fork of iText).

Not sure if we are going to switch to OpenPDF any time soon, but in the meantime, we have created a new exporter based on iText 5+, which is published under AGPL, to make it compatible with the iText 5+ license.
It is a separate project and you can build it from source and use it in accordance with the AGPL terms:
https://github.com/Jaspersoft/jasperreports-pdf-lib5

**Comment by codecracker2014** [comment]
@teodord support for advance typography(TTF tables processing) has been added to OpenPDF with 1.3.13 release, hope this will address font processing requirements. Please suggest if we can integrate jasperreports with OpenPDF

Refer below:
https://github.com/LibrePDF/OpenPDF/pull/329
https://github.com/LibrePDF/OpenPDF/issues/297
https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.13

-FYI
