### ISSUE TITLE
Release 6.7.0: Incorrect version number "6.6.0"

### ISSUE THREAD

**Issue by alexnb** [TIBCOSoftware/jasperreports#50]
The MANIFEST of jasperreports.jar of release 6.7.0 contains incorrect version number "6.6.0". Unfortunately it even more confusing because this version number is used in the "creator" field of the resulting export file (PDF etc.).

**Comment by dadza** [comment]
Also reported as #40.

**Comment by alexnb** [comment]
thanks @dadza
