### ISSUE TITLE
Feature request: dynamic number of columns and auto-resizing of columns

### ISSUE THREAD

**Issue by woodholly** [TIBCOSoftware/jasperreports#502]
Hi!
Most of financial documents have dynamic number of columns - print tax, or don't print tax, print discount or don't etc, show price without tax or don't.
Why can't we set all possible columns in a table with their respective weights and just disable some columns on demand ?
I really don't understand why this general feature not implemented in so many years.

**Comment by teodord** [comment]
Hi,

Are you referring to the ability to hide columns in the table component, but complain about the fact that they do not resize according to some weights?

Or is there more to it?

Thank you, 
Teodor

**Comment by woodholly** [comment]
Exactly! Right now if we disable some table column during runtime (conditional disabling), those columns just disappear leaving empty space. Why other columns don't fill this space respecting their column weights ?

**Comment by teodord** [comment]
Hi,

You could help us by proposing a more detailed requirement about how such feature should work.
You mentioned "column weights". But how exactly should they work especially considering columns can be grouped in column groups. Should column groups have weights of their own? If so, how to reconcile weights set at different levels?

Thank you,
Teodor

**Comment by woodholly** [comment]
I think it should work like this:
If some of column headers have been grouped, then their weights only influence their width within this group. The width of the group should depend only on the weight of the group itself, not it's child-columns.
In case of grouping on different levels (row span), the width of the group should depend on weight on the same top level columns.

Right now I don't use tables to print invoices. Long ago I replaced it with grid layout inside 1-column table and a combination of all possible headers/cells, it already has weights and everything works fine except runtime hiding/stretching. This workaround is required, because it's impossible to use different sets of table columns.

PS: users struggle without this feature since 2011 - https://stackoverflow.com/questions/4734722/change-size-position-of-jasper-reports-columns

**Comment by teodord** [comment]
I think the stackoverflow thread above is about someone asking how to achieve something that the table component allows: hiding columns. Table component has been introduced in 2010. There are a couple of comments recommending them the table component at the time of the initial post.

But let's get back to the current issue: automatic resizing of columns.
When we talk about a "column weight", what exactly should it be? A percentage? A percentage of what?
When we say remaining columns should benefit from the additional space left in place by columns that are hidden, how exactly should this additional space be calculated? 
Are we talking about the declared design width of the table component itself (table element)?
Or are we talking about the total table width calculated as the sum of all its declared columns (which often times is bigger than the declared table element width)?

For example, if out of 10 declared columns, we hide 9 and only 1 remains, should this remaining column be as wide as the declared table element, or as wide as all the declared columns?
Not that the declared table element width does not act as a limit in any way today, columns being rendered even if they are well beyond table width.

Thank you,
Teodor

**Comment by woodholly** [comment]
>When we talk about a "column weight", what exactly should it be? A percentage? A percentage of what?

Weight is a linear coefficient, the bigger the weight, the more space column will take:

column_width = table_width * column_weight / sum(visible_columns_weights)

Obviously sum(column_width) = table_width

Example (in html syntax):
```
<table width=1000px>
<tr>
<td weight=1>1</td>
<td weight=2>2</td>
<td weight=3>3</td>
```
If all columns visible, they will take: 1000 * 1/6=167px, 1000 * 2/6=333px, 1000 * 3/6=500px
If column 3 disappears: 1000 * 1/3=333px, 1000 * 2/3=667px, 0px

**Comment by woodholly** [comment]
Actually grid component already has this feature (weight) and I use it alot, but it is not dynamic and does not resize grid elements in runtime.

**Comment by teodord** [comment]
What if the table element width is smaller than the sum of all declared columns? Should we allow weighted columns get smaller so that we fit everything into the declared table element width?
Or should the column width always represent a minimum size under which column cannot shrink?

I am asking to see if other properties are needed to control behavior of columns with respect to declared table element width. So far we talked about columns growing to fit extra space, but what about columns shrinking to fit into narrow table elements?

Thank you,
Teodor

**Comment by woodholly** [comment]
>What if the table element width is smaller than the sum of all declared columns? Should we allow weighted columns get smaller so that we fit everything into the declared table element width?

If I understood you correctly -  "declared columns" are columns with static width, not weighted columns. 
If there is no space for weighted columns left, then they should disappear (width=0). If this happens then this is report designer error.
BUT minimum allowed column width, under which weighted column cannot shrink is great idea.

**Comment by teodord** [comment]
Declared columns are all the columns defined in the table, regardless of their width behavior.

Maybe differentiation between growing and shrinking behavior of weighted columns should be controlled by different properties such as growWeight and shrinkWeight, similar to what CSS has with flex-grow and flex-shrink properties.

https://www.w3schools.com/cssref/css3_pr_flex-grow.php
https://www.w3schools.com/cssref/css3_pr_flex-shrink.php

Thank you,
Teodor

**Comment by woodholly** [comment]
I am far from css, but at first look, flex-grow + flex-shrink are better then pure weight, but I think it would be harder to implement and users to understand. As much as I can see, flex-grow and flex-shrink are width-change-aware and were invented for responsive designs.
There is no such thing in jasper-reports, and only the responsive part will be column that disappears. This is now how css flex shrink/grow works.

**Comment by teodord** [comment]
Actually, the interactivity aspect exists with JasperReports as well and I wanted to bring it up.

Table components are interactive when reports are run with JasperReports Server, JasperReports IO and JasperReports Web Studio, where users could interactively hide/show columns, resize and reorder them in the interactive report viewer.

And I wanted to bring up the fact that when the user interactively resizes a column, the "weight" of the column should be reset/discarded, because otherwise, why would the user attempt to manually resize it in the first place?
If the column weight would not be reset by the manual/interactive resize, the column would stay the same as the applied weight would calculate the size and obtain the value it already has, so the resize operation would seem to have no effect.

Resizing means the user really want the column to be the size she/he chose, so the weight of the column, if present, would be eliminated by the resize operation.

**Comment by woodholly** [comment]
That is simpler to make with weight only.  If user manually resizes the column, it changes it's width in pixels. This change can be internally recalculated to respective weight change and stored as column property.
Not so simple with flex-grow/flex-shrink.

**Comment by woodholly** [comment]
Awesome! Thank you! It would be nice if there was an example of using this parameter in the table, I will report if I fail to use it :)

**Comment by teodord** [comment]
Please try it and let us know. Also note that there is also a new horizontalPosition property for table (Left, Center, Right), which controls the alignment of columns within table box.
