### ISSUE TITLE
Nested lists and return value

### ISSUE THREAD

**Issue by asfernandes** [TIBCOSoftware/jasperreports#59]
When two nested lists are created (say, L1 and L11), in JasperStudio's L11 dataset run it was possible and worked (6.2) to return values to the main's report variables. In fact it was the only way, as it cannot return values to L1's variable.

Now with JasperReports 6.8 library this usage is not compiling, saying the variable does not exists.

**Comment by teodord** [comment]
Can you upload here a JRXML that poses this problem?

Thank you,
Teodor

**Comment by teodord** [comment]
Feel free to reopen this if you can provide more details about it.

Thank you,
Teodor
