### ISSUE TITLE
Two additional newlines when exporting to text file

### ISSUE THREAD

**Issue by metalpalo** [TIBCOSoftware/jasperreports#60]
Hi all,
I've created very simple Jasper report in studio, version 6.8.0. My template contains only detail band, all another arreas are removed. I also set Ingore pagination to true to gen fluent file without some break. My problem is that I got extra two end lines in the end of exported file. I summary, file finished with 3 end lines as describen in following threads:
https://stackoverflow.com/questions/43282485/jasperreports-text-file-contains-2-newline-characters-at-the-end-of-every-page
https://community.jaspersoft.com/jasperreports-server/issues/6446

What I found out in second link, only added <property name="net.sf.jasperreports.export.text.page.separator" value=""/> to jrxml works, studio have problem to define empty value

Can somebody help me where is problem? When exporting to csv, file normally is ended with one end line.
thanks
brpalo

**Comment by teodord** [comment]
The page separator will be inhibited after the last page. The fix will be part of the next release.
