### ISSUE TITLE
Ligatures with Myanmar fonts are not applied correctly

### ISSUE THREAD

**Issue by Winterwind83** [TIBCOSoftware/jasperreports#63]
We are trying to create reports (with output as PDFs and images) with Myanmar fonts ('Myanmar Text' and 'Padauk'). We have created font extensions with these fonts, and those extensions are on our application's class path. Unfortunately, we are running into an issue with JasperReports not applying ligatures properly.

The problem can be reproduced with a simple Report consisting of nothing but a single Text Field or Static Text with, for example, the following content:
လက်ကားဖြန့်ချီရေး

This is what the output should look like (generated by JasperReports exporting to html):
![myanmarHtml](https://user-images.githubusercontent.com/18546521/58958748-e56c2680-87a3-11e9-92fc-87514054711e.png)

This is what it looks like instead (generated by JasperReports exporting to pdf):
![myanmarPdf](https://user-images.githubusercontent.com/18546521/58958861-1cdad300-87a4-11e9-9c7f-9ed864440775.png)

The above examples were created with the 'Myanmar Text' font; using other fonts yields results that are different but just as wrong - for example, ignoring ligatures entirely, rather than applying them incorrectly.

In [this Community discussion](https://community.jaspersoft.com/wiki/some-thai-characters-are-not-displaying-properly-pdf-export), a potentially related problem with Thai fonts was discussed; there, adding the following property to the report fixed the issue:
`<property name="net.sf.jasperreports.export.pdf.glyph.renderer.blocks.x" value="thai"/>`
We tried adding that property to the report (replacing "thai" with "myanmar", which is the name of the appropriate Unicode block), and the subsequent output of the JasperReports Library indicates that it can resolve the AWT and PDF fonts and use the glyph rendering then; however, unfortunately this did not affect the actual output whatsoever.

**Comment by dadza** [comment]
What Java/JRE are you using?

With "myanmar" added as net.sf.jasperreports.export.pdf.glyph.renderer.blocks.x, the PDF output relies on the AWT/JRE text layout, so we first need to look into whether the specific Java version is able to properly layout the Myanmar text.

**Comment by Winterwind83** [comment]
We were using an Oracle JRE 1.8.0_201.

Inspired by your query, I tried running the same report with Java 11, and it came out perfectly. So I guess that would explain the issue.

Thank you muchly!
