### ISSUE TITLE
Infinite loop - Date field inside header band

### ISSUE THREAD

**Issue by NabihaOjeil** [TIBCOSoftware/jasperreports#8]
Dear All,

We are facing an infinite loop issue upon trying to retrieve a report having a field of type date in the header band of the report where the size of this element is less than the size of its data content, in case we  will increase the size of this input the report will be generated properly
This issue is appearing under all jasperSoft releases ( release 6.4.0 and lower) 
Is it possible to fix it through the code of jasper instead of fixing it manually, we are working currently on the libraries jasperreports-javaflow-5.5.0.jar and jasperreports-javaflow-6.1.1.jar
Below is the related jrxml , you can test it under any oracle DB , the problematic field in the header is 'DATE_CREATED'

<?xml version="1.0" encoding="UTF-8"?>

<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="fms_cr_f_p" pageWidth="700" pageHeight="850" whenNoDataType="AllSectionsNoDetail" columnWidth="664" leftMargin="18" rightMargin="18" topMargin="18" bottomMargin="18" uuid="ff0fcf35-b5e0-4eef-87de-0eea1a89f061">
	<property name="ireport.zoom" value="1.331000000000003"/>
	<property name="ireport.x" value="0"/>
	<property name="ireport.y" value="0"/>
	<property name="com.jaspersoft.studio.unit." value="pixel"/>
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="IMAL141_DEV_O11"/>
	<property name="com.jaspersoft.studio.data.sql.tables" value=""/>
	<property name="com.jaspersoft.studio.unit.pageHeight" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.pageWidth" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.topMargin" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.bottomMargin" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.leftMargin" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.rightMargin" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.columnWidth" value="pixel"/>
	<property name="com.jaspersoft.studio.unit.columnSpacing" value="pixel"/>
	<queryString>
		<![CDATA[SELECT  SYSDATE AS DATE_CREATED ,'J' AS CUSTOMER_NAME FROM DUAL]]>
	</queryString>
	<field name="DATE_CREATED" class="java.sql.Time">
		<property name="lblname" value="fmsappl_date_created"/>
		<property name="lbltype" value="java.sql.Timestamp"/>
	</field>
	<field name="CUSTOMER_NAME" class="java.lang.String">
		<property name="lblname" value="cif_customer_name"/>
		<property name="lbltype" value="java.lang.String"/>
	</field>
	<pageHeader>
		<band height="80" splitType="Stretch">
			<textField isStretchWithOverflow="true" evaluationTime="Auto" isBlankWhenNull="true">
				<reportElement x="45" y="53" width="45" height="17" forecolor="#000000" uuid="3d18efb2-0aae-45d6-9267-00ea3676624a"/>
				<textElement textAlignment="Left">
					<font fontName="Serif" size="8" isPdfEmbedded="false"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{DATE_CREATED}]]></textFieldExpression>
			</textField>
		</band>
	</pageHeader>
	<detail>
		<band height="734" splitType="Stretch">
			<textField isStretchWithOverflow="true" isBlankWhenNull="true">
				<reportElement x="109" y="23" width="174" height="11" forecolor="#000000" uuid="f553e122-d664-4df5-916c-3ff67d3f9d68"/>
				<textElement textAlignment="Left">
					<font fontName="Arial" size="8" isPdfEmbedded="false"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{CUSTOMER_NAME}]]></textFieldExpression>
			</textField>
		</band>
	</detail>
</jasperReport>

**Comment by NabihaOjeil** [comment]
Dears ,

Kind reminder

Thank you

**Comment by teodord** [comment]
You would need to attach the JRXMLs involved, if it is for us to be able to identify the issue. It's possible that the infinite loop is cause by some element having isPrintWhenDetailOverflows="true".
