### ISSUE TITLE
JavaScript support should include ES6 support (draft patch included).

### ISSUE THREAD

**Issue by ShaheedHaque** [TIBCOSoftware/jasperreports#99]
In following up a [question I posed](https://community.jaspersoft.com/questions/1112271/recipe-and-question-using-jsonql-and-javascript) would like to request that the ES6 support in Rhino be turned on. I have looked at the code in JasperReports, and the Rhino code, and I believe what is needed might be as simple as adding a single call [here](https://github.com/TIBCOSoftware/jasperreports/blob/0682658fd0cb88420019f9c089dda99054b36bdf/jasperreports/src/net/sf/jasperreports/compilers/JavaScriptCompiler.java#L70):

```
		Context context = ContextFactory.getGlobal().enterContext();
+		context.setLanguageVersion(Context.VERSION_ES6);
```

I tried to get Eclipse going so I could create a PR, but failed to get a build running (I've not done Java in a couple of decades...).

Ideally, such a change would be accompanied by an upgrade of the Rhino engine as per [a similar tracker I filed](https://community.jaspersoft.com/jasperreports-library/issues/11641), but it was not clear to me if GitHub or the tracker was the active place for issues/requests.

**Comment by teodord** [comment]
Initial tests seem to indicate that setLanguageVersion(int version) does not seem to have any visible effect. Simply upgrading Rhino in the classpath make ES6 constructs work, without any special setting.
Can you confirm? Or do you have a report expression that would not work just by upgrading to Rhino 1.7.11 in the classpath?

**Comment by ShaheedHaque** [comment]
It is worth saying that the `setLanguageVersion()` thing was a not-very-educated guess on my part. As noted, I did not manage to get a build going to try it.

So, if you have newer syntax, such as arrow "lambda" functions or array spreading working, then I would say the problem is solved :-).

Right now, I am no actively developing

**Comment by teodord** [comment]
Seems like ES6 expressions work in reports just by upgrading Rhino to 1.7.11, so we are not going to add the setLanguageVersion(int version) method for now. Unless someone proves it is really needed.
Upgraded to Rhino 1.7.11 in master branch.
